#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Writes HR, SL, BG, IS ValidationMessages files."""
import os
VDIR = "src/main/resources/i18n/validation/"
FILES = {
"hr": """validation.allergen.name.notBlank=Ime alergena je obavezno
validation.allergen.name.size=Mora imati između 2 i 50 znakova
validation.allergenRequestDTO.name.notBlank=Ime alergena je obavezno
validation.allergenRequestDTO.name.size=Mora imati između 2 i 50 znakova
validation.batchStockMovementRequestDTO.movements.notEmpty=Mora biti uključeno barem jedno kretanje
validation.batchStockMovementRequestDTO.reason.size=Razlog ne smije prelaziti 1000 znakova
validation.changePasswordRequestDTO.newPassword.notBlank=Nova lozinka je obavezna
validation.changePasswordRequestDTO.newPassword.size=Nova lozinka mora imati najmanje 6 znakova
validation.inventoryAudit.actionDescription.size=Opis ne smije prelaziti 500 znakova
validation.inventoryAudit.product.notNull=Proizvod je obavezan
validation.inventoryAudit.quantity.notNull=Količina je obavezna
validation.inventoryAudit.unknown.notBlank=Vrsta kretanja je obavezna
validation.inventoryMovementRequestDTO.movementType.notNull=Vrsta kretanja je obavezna
validation.inventoryMovementRequestDTO.productId.notNull=ID proizvoda je obavezan
validation.inventoryMovementRequestDTO.quantity.decimalMax=Količina ne smije prelaziti 9.999.999,99
validation.inventoryMovementRequestDTO.quantity.notNull=Količina je obavezna
validation.inventoryMovementRequestDTO.quantity.positive=Količina mora biti veća od nule
validation.inventoryMovementRequestDTO.userId.notNull=ID korisnika je obavezan
validation.jwtProperties.expiration.positive=Istek JWT-a mora biti pozitivna vrijednost
validation.jwtProperties.secret.notBlank=JWT tajna je obavezna
validation.loginRequestDTO.name.notBlank=Korisničko ime je obavezno
validation.loginRequestDTO.password.notBlank=Lozinka je obavezna
validation.order.orderDate.notNull=Datum narudžbe je obavezan
validation.order.orderDate.pastOrPresent=Datum narudžbe ne može biti u budućnosti
validation.order.status.notBlank=Status je obavezan
validation.order.users.notNull=Korisnik je obavezan
validation.orderAudit.action.notBlank=Akcija je obavezna
validation.orderAudit.details.size=Detalji ne smiju prelaziti 1000 znakova
validation.orderDetail.order.notNull=Narudžba je obavezna
validation.orderDetail.product.notNull=Proizvod je obavezan
validation.orderDetail.quantity.decimalMin=Količina mora biti veća od 0
validation.orderDetail.quantity.notNull=Tražena količina je obavezna
validation.orderDetail.quantityReceived.decimalMin=Primljena količina ne može biti negativna
validation.orderDetailRequestDTO.productId.notNull=ID proizvoda je obavezan
validation.orderDetailRequestDTO.quantity.decimalMin=Količina mora biti veća od nule
validation.orderDetailRequestDTO.quantity.digits=Količina može imati najviše 10 cijelih i 3 decimalna mjesta
validation.orderDetailRequestDTO.quantity.notNull=Količina je obavezna
validation.orderReceptionDetailRequestDTO.productId.notNull=ID proizvoda je obavezan
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Primljena količina je obavezna
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Primljena količina mora biti nula ili veća
validation.orderReceptionRequestDTO.items.notEmpty=Mora biti naveden barem jedan primljeni proizvod
validation.orderReceptionRequestDTO.orderId.notNull=ID narudžbe je obavezan
validation.orderReceptionRequestDTO.status.notNull=Status je obavezan
validation.orderRequestDTO.details.notEmpty=Narudžba mora imati barem jedan detalj
validation.orderRequestDTO.userId.notNull=ID korisnika je obavezan
validation.product.availabilityPercentage.decimalMax=Postotak dostupnosti ne smije prelaziti 100
validation.product.availabilityPercentage.decimalMin=Postotak dostupnosti ne može biti negativan
validation.product.availabilityPercentage.digits=Nevažeći format dostupnosti
validation.product.currentStock.decimalMin=Zaliha ne može biti negativna
validation.product.currentStock.digits=Nevažeći format zalihe
validation.product.currentStock.notNull=Trenutna zaliha je obavezna
validation.product.minimumStock.decimalMin=Minimalna zaliha ne može biti negativna
validation.product.minimumStock.digits=Nevažeći format minimalne zalihe
validation.product.name.notBlank=Ime proizvoda je obavezno
validation.product.name.size=Mora imati između 2 i 100 znakova
validation.product.productCode.notBlank=Šifra proizvoda je obavezna
validation.product.unit.notBlank=Jedinica mjere je obavezna
validation.product.unitPrice.decimalMin=Cijena mora biti veća od 0
validation.product.unitPrice.digits=Nevažeći format cijene
validation.product.unitPrice.notNull=Jedinična cijena je obavezna
validation.productRequestDTO.availabilityPercentage.decimalMax=Postotak dostupnosti ne smije prelaziti 100
validation.productRequestDTO.availabilityPercentage.decimalMin=Postotak dostupnosti ne može biti negativan
validation.productRequestDTO.availabilityPercentage.digits=Postotak može imati najviše 3 cijela i 2 decimalna mjesta
validation.productRequestDTO.currentStock.decimalMin=Zaliha ne može biti negativna
validation.productRequestDTO.currentStock.digits=Zaliha može imati najviše 10 cijelih i 3 decimalna mjesta
validation.productRequestDTO.currentStock.notNull=Trenutna zaliha je obavezna
validation.productRequestDTO.minimumStock.decimalMin=Minimalna zaliha ne može biti negativna
validation.productRequestDTO.minimumStock.digits=Minimalna zaliha može imati najviše 10 cijelih i 3 decimalna mjesta
validation.productRequestDTO.minimumStock.notNull=Minimalna zaliha je obavezna
validation.productRequestDTO.name.notBlank=Ime proizvoda je obavezno
validation.productRequestDTO.name.size=Mora imati između 2 i 100 znakova
validation.productRequestDTO.productCode.notBlank=Šifra proizvoda je obavezna
validation.productRequestDTO.productCode.size=Šifra ne smije prelaziti 50 znakova
validation.productRequestDTO.unit.notBlank=Jedinica mjere je obavezna
validation.productRequestDTO.unit.size=Jedinica ne smije prelaziti 20 znakova
validation.productRequestDTO.unitPrice.decimalMin=Cijena mora biti veća od nule
validation.productRequestDTO.unitPrice.digits=Cijena može imati najviše 10 cijelih i 2 decimalna mjesta
validation.productRequestDTO.unitPrice.notNull=Jedinična cijena je obavezna
validation.recipe.elaboration.size=Priprema ne smije prelaziti 2000 znakova
validation.recipe.name.notBlank=Ime recepta je obavezno
validation.recipe.name.size=Mora imati između 2 i 150 znakova
validation.recipe.presentation.size=Prezentacija ne smije prelaziti 1000 znakova
validation.recipe.totalCost.decimalMin=Cijena ne može biti negativna
validation.recipeAudit.action.notBlank=Akcija je obavezna
validation.recipeAudit.details.size=Detalji ne smiju prelaziti 1000 znakova
validation.recipeComponent.parentRecipe.notNull=Recept je obavezan
validation.recipeComponent.product.notNull=Proizvod je obavezan
validation.recipeComponent.quantity.decimalMin=Količina mora biti veća od 0
validation.recipeComponent.quantity.notNull=Količina je obavezna
validation.recipeComponentRequestDTO.productId.notNull=ID proizvoda je obavezan
validation.recipeComponentRequestDTO.quantity.decimalMin=Količina mora biti veća od nule
validation.recipeComponentRequestDTO.quantity.digits=Količina može imati najviše 10 cijelih i 3 decimalna mjesta
validation.recipeComponentRequestDTO.quantity.notNull=Količina je obavezna
validation.recipeCookingAudit.details.size=Detalji ne smiju prelaziti 1000 znakova
validation.recipeCookingAudit.quantityCooked.decimalMin=Količina mora biti veća od 0
validation.recipeCookingAudit.quantityCooked.notNull=Pripremljena količina je obavezna
validation.recipeCookingAudit.recipe.notNull=Recept je obavezan
validation.recipeCookingRequestDTO.details.size=Detalji ne smiju prelaziti 500 znakova
validation.recipeCookingRequestDTO.quantity.decimalMin=Količina mora biti veća od 0
validation.recipeCookingRequestDTO.quantity.digits=Količina može imati najviše 10 cijelih i 3 decimalna mjesta
validation.recipeCookingRequestDTO.quantity.notNull=Količina za pripremu je obavezna
validation.recipeCookingRequestDTO.recipeId.notNull=ID recepta je obavezan
validation.recipeCookingRequestDTO.recipeId.positive=ID recepta mora biti pozitivan
validation.recipeRequestDTO.components.notEmpty=Recept mora uključivati barem jedan sastojak
validation.recipeRequestDTO.elaboration.notBlank=Priprema je obavezna
validation.recipeRequestDTO.elaboration.size=Priprema ne smije prelaziti 2000 znakova
validation.recipeRequestDTO.name.notBlank=Ime recepta je obavezno
validation.recipeRequestDTO.name.size=Mora imati između 2 i 150 znakova
validation.recipeRequestDTO.presentation.notBlank=Prezentacija je obavezna
validation.recipeRequestDTO.presentation.size=Prezentacija ne smije prelaziti 1000 znakova
validation.roleEscalationRequestDTO.durationMinutes.max=Maksimalno dopušteno trajanje je 1440 minuta (24 sata)
validation.roleEscalationRequestDTO.durationMinutes.min=Minimalno trajanje mora biti 1 minuta
validation.roleEscalationRequestDTO.durationMinutes.notNull=Trajanje u minutama je obavezno
validation.stockLedger.currentHash.notBlank=Trenutni hash je obavezan
validation.stockLedger.movementType.notNull=Vrsta kretanja je obavezna
validation.stockLedger.previousHash.notBlank=Prethodni hash je obavezan
validation.stockLedger.product.notNull=Proizvod je obavezan
validation.stockLedger.quantityDelta.notNull=Količina je obavezna
validation.stockLedger.resultingStock.notNull=Rezultirajuća zaliha je obavezna
validation.stockLedger.sequenceNumber.notNull=Sekvencijski broj je obavezan
validation.stockLedger.transactionTimestamp.notNull=Vremenska oznaka je obavezna
validation.stockMovementItemDTO.description.size=Opis ne smije prelaziti 500 znakova
validation.stockMovementItemDTO.movementType.notNull=Vrsta kretanja je obavezna
validation.stockMovementItemDTO.productId.notNull=ID proizvoda je obavezan
validation.stockMovementItemDTO.quantityDelta.digits=Količina može imati najviše 10 cijelih i 3 decimalna mjesta
validation.stockMovementItemDTO.quantityDelta.notNull=Količina je obavezna
validation.stockSnapshot.currentStock.notNull=Trenutna zaliha je obavezna
validation.stockSnapshot.integrityStatus.notBlank=Status integriteta je obavezan
validation.stockSnapshot.lastSequenceNumber.notNull=Sekvencijski broj je obavezan
validation.stockSnapshot.lastTransactionHash.notBlank=Posljednji hash je obavezan
validation.stockSnapshot.lastUpdated.notNull=Datum ažuriranja je obavezan
validation.supplier.name.notBlank=Ime dobavljača je obavezno
validation.supplier.name.size=Mora imati između 2 i 100 znakova
validation.supplierRequestDTO.name.notBlank=Ime dobavljača je obavezno
validation.supplierRequestDTO.name.size=Mora imati između 2 i 100 znakova
validation.user.name.notBlank=Ime je obavezno
validation.user.name.size=Mora imati između 2 i 100 znakova
validation.user.password.notBlank=Lozinka je obavezna
validation.user.role.notNull=Uloga je obavezna
validation.user.user.notBlank=Korisničko ime je obavezno
validation.userRequestDTO.name.notBlank=Ime je obavezno
validation.userRequestDTO.name.size=Mora imati između 2 i 100 znakova
validation.userRequestDTO.password.notBlank=Lozinka je obavezna
validation.userRequestDTO.password.size=Lozinka mora imati najmanje 6 znakova
validation.userRequestDTO.user.notBlank=Korisničko ime je obavezno
validation.userRequestDTO.user.size=Korisničko ime ne smije prelaziti 100 znakova
""",

"sl": """validation.allergen.name.notBlank=Ime alergena je obvezno
validation.allergen.name.size=Mora imeti med 2 in 50 znakov
validation.allergenRequestDTO.name.notBlank=Ime alergena je obvezno
validation.allergenRequestDTO.name.size=Mora imeti med 2 in 50 znakov
validation.batchStockMovementRequestDTO.movements.notEmpty=Vključen mora biti vsaj en premik
validation.batchStockMovementRequestDTO.reason.size=Razlog ne sme presegati 1000 znakov
validation.changePasswordRequestDTO.newPassword.notBlank=Novo geslo je obvezno
validation.changePasswordRequestDTO.newPassword.size=Novo geslo mora imeti vsaj 6 znakov
validation.inventoryAudit.actionDescription.size=Opis ne sme presegati 500 znakov
validation.inventoryAudit.product.notNull=Izdelek je obvezen
validation.inventoryAudit.quantity.notNull=Količina je obvezna
validation.inventoryAudit.unknown.notBlank=Vrsta premika je obvezna
validation.inventoryMovementRequestDTO.movementType.notNull=Vrsta premika je obvezna
validation.inventoryMovementRequestDTO.productId.notNull=ID izdelka je obvezen
validation.inventoryMovementRequestDTO.quantity.decimalMax=Količina ne sme presegati 9.999.999,99
validation.inventoryMovementRequestDTO.quantity.notNull=Količina je obvezna
validation.inventoryMovementRequestDTO.quantity.positive=Količina mora biti večja od nič
validation.inventoryMovementRequestDTO.userId.notNull=ID uporabnika je obvezen
validation.jwtProperties.expiration.positive=Potek JWT mora biti pozitivna vrednost
validation.jwtProperties.secret.notBlank=Skrivnost JWT je obvezna
validation.loginRequestDTO.name.notBlank=Uporabniško ime je obvezno
validation.loginRequestDTO.password.notBlank=Geslo je obvezno
validation.order.orderDate.notNull=Datum naročila je obvezen
validation.order.orderDate.pastOrPresent=Datum naročila ne sme biti v prihodnosti
validation.order.status.notBlank=Stanje je obvezno
validation.order.users.notNull=Uporabnik je obvezen
validation.orderAudit.action.notBlank=Dejanje je obvezno
validation.orderAudit.details.size=Podrobnosti ne smejo presegati 1000 znakov
validation.orderDetail.order.notNull=Naročilo je obvezno
validation.orderDetail.product.notNull=Izdelek je obvezen
validation.orderDetail.quantity.decimalMin=Količina mora biti večja od 0
validation.orderDetail.quantity.notNull=Zahtevana količina je obvezna
validation.orderDetail.quantityReceived.decimalMin=Prejeta količina ne sme biti negativna
validation.orderDetailRequestDTO.productId.notNull=ID izdelka je obvezen
validation.orderDetailRequestDTO.quantity.decimalMin=Količina mora biti večja od nič
validation.orderDetailRequestDTO.quantity.digits=Količina ima lahko največ 10 celih in 3 decimalna mesta
validation.orderDetailRequestDTO.quantity.notNull=Količina je obvezna
validation.orderReceptionDetailRequestDTO.productId.notNull=ID izdelka je obvezen
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Prejeta količina je obvezna
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Prejeta količina mora biti enaka ali večja od nič
validation.orderReceptionRequestDTO.items.notEmpty=Določen mora biti vsaj en prejet izdelek
validation.orderReceptionRequestDTO.orderId.notNull=ID naročila je obvezen
validation.orderReceptionRequestDTO.status.notNull=Stanje je obvezno
validation.orderRequestDTO.details.notEmpty=Naročilo mora vsebovati vsaj eno podrobnost
validation.orderRequestDTO.userId.notNull=ID uporabnika je obvezen
validation.product.availabilityPercentage.decimalMax=Odstotek razpoložljivosti ne sme presegati 100
validation.product.availabilityPercentage.decimalMin=Odstotek razpoložljivosti ne sme biti negativen
validation.product.availabilityPercentage.digits=Neveljaven format razpoložljivosti
validation.product.currentStock.decimalMin=Zaloga ne sme biti negativna
validation.product.currentStock.digits=Neveljaven format zaloge
validation.product.currentStock.notNull=Trenutna zaloga je obvezna
validation.product.minimumStock.decimalMin=Najmanjša zaloga ne sme biti negativna
validation.product.minimumStock.digits=Neveljaven format najmanjše zaloge
validation.product.name.notBlank=Ime izdelka je obvezno
validation.product.name.size=Mora imeti med 2 in 100 znakov
validation.product.productCode.notBlank=Koda izdelka je obvezna
validation.product.unit.notBlank=Merska enota je obvezna
validation.product.unitPrice.decimalMin=Cena mora biti večja od 0
validation.product.unitPrice.digits=Neveljaven format cene
validation.product.unitPrice.notNull=Cena na enoto je obvezna
validation.productRequestDTO.availabilityPercentage.decimalMax=Odstotek razpoložljivosti ne sme presegati 100
validation.productRequestDTO.availabilityPercentage.decimalMin=Odstotek razpoložljivosti ne sme biti negativen
validation.productRequestDTO.availabilityPercentage.digits=Odstotek ima lahko največ 3 cela in 2 decimalni mesti
validation.productRequestDTO.currentStock.decimalMin=Zaloga ne sme biti negativna
validation.productRequestDTO.currentStock.digits=Zaloga ima lahko največ 10 celih in 3 decimalna mesta
validation.productRequestDTO.currentStock.notNull=Trenutna zaloga je obvezna
validation.productRequestDTO.minimumStock.decimalMin=Najmanjša zaloga ne sme biti negativna
validation.productRequestDTO.minimumStock.digits=Najmanjša zaloga ima lahko največ 10 celih in 3 decimalna mesta
validation.productRequestDTO.minimumStock.notNull=Najmanjša zaloga je obvezna
validation.productRequestDTO.name.notBlank=Ime izdelka je obvezno
validation.productRequestDTO.name.size=Mora imeti med 2 in 100 znakov
validation.productRequestDTO.productCode.notBlank=Koda izdelka je obvezna
validation.productRequestDTO.productCode.size=Koda ne sme presegati 50 znakov
validation.productRequestDTO.unit.notBlank=Merska enota je obvezna
validation.productRequestDTO.unit.size=Enota ne sme presegati 20 znakov
validation.productRequestDTO.unitPrice.decimalMin=Cena mora biti večja od nič
validation.productRequestDTO.unitPrice.digits=Cena ima lahko največ 10 celih in 2 decimalni mesti
validation.productRequestDTO.unitPrice.notNull=Cena na enoto je obvezna
validation.recipe.elaboration.size=Priprava ne sme presegati 2000 znakov
validation.recipe.name.notBlank=Ime recepta je obvezno
validation.recipe.name.size=Mora imeti med 2 in 150 znakov
validation.recipe.presentation.size=Predstavitev ne sme presegati 1000 znakov
validation.recipe.totalCost.decimalMin=Strošek ne sme biti negativen
validation.recipeAudit.action.notBlank=Dejanje je obvezno
validation.recipeAudit.details.size=Podrobnosti ne smejo presegati 1000 znakov
validation.recipeComponent.parentRecipe.notNull=Recept je obvezen
validation.recipeComponent.product.notNull=Izdelek je obvezen
validation.recipeComponent.quantity.decimalMin=Količina mora biti večja od 0
validation.recipeComponent.quantity.notNull=Količina je obvezna
validation.recipeComponentRequestDTO.productId.notNull=ID izdelka je obvezen
validation.recipeComponentRequestDTO.quantity.decimalMin=Količina mora biti večja od nič
validation.recipeComponentRequestDTO.quantity.digits=Količina ima lahko največ 10 celih in 3 decimalna mesta
validation.recipeComponentRequestDTO.quantity.notNull=Količina je obvezna
validation.recipeCookingAudit.details.size=Podrobnosti ne smejo presegati 1000 znakov
validation.recipeCookingAudit.quantityCooked.decimalMin=Količina mora biti večja od 0
validation.recipeCookingAudit.quantityCooked.notNull=Pripravljena količina je obvezna
validation.recipeCookingAudit.recipe.notNull=Recept je obvezen
validation.recipeCookingRequestDTO.details.size=Podrobnosti ne smejo presegati 500 znakov
validation.recipeCookingRequestDTO.quantity.decimalMin=Količina mora biti večja od 0
validation.recipeCookingRequestDTO.quantity.digits=Količina ima lahko največ 10 celih in 3 decimalna mesta
validation.recipeCookingRequestDTO.quantity.notNull=Količina za pripravo je obvezna
validation.recipeCookingRequestDTO.recipeId.notNull=ID recepta je obvezen
validation.recipeCookingRequestDTO.recipeId.positive=ID recepta mora biti pozitiven
validation.recipeRequestDTO.components.notEmpty=Recept mora vsebovati vsaj eno sestavino
validation.recipeRequestDTO.elaboration.notBlank=Priprava je obvezna
validation.recipeRequestDTO.elaboration.size=Priprava ne sme presegati 2000 znakov
validation.recipeRequestDTO.name.notBlank=Ime recepta je obvezno
validation.recipeRequestDTO.name.size=Mora imeti med 2 in 150 znakov
validation.recipeRequestDTO.presentation.notBlank=Predstavitev je obvezna
validation.recipeRequestDTO.presentation.size=Predstavitev ne sme presegati 1000 znakov
validation.roleEscalationRequestDTO.durationMinutes.max=Največje dovoljeno trajanje je 1440 minut (24 ur)
validation.roleEscalationRequestDTO.durationMinutes.min=Najkrajše trajanje mora biti 1 minuta
validation.roleEscalationRequestDTO.durationMinutes.notNull=Trajanje v minutah je obvezno
validation.stockLedger.currentHash.notBlank=Trenutni zgošček (hash) je obvezen
validation.stockLedger.movementType.notNull=Vrsta premika je obvezna
validation.stockLedger.previousHash.notBlank=Prejšnji zgošček (hash) je obvezen
validation.stockLedger.product.notNull=Izdelek je obvezen
validation.stockLedger.quantityDelta.notNull=Količina je obvezna
validation.stockLedger.resultingStock.notNull=Nastala zaloga je obvezna
validation.stockLedger.sequenceNumber.notNull=Zaporedna številka je obvezna
validation.stockLedger.transactionTimestamp.notNull=Časovni žig je obvezen
validation.stockMovementItemDTO.description.size=Opis ne sme presegati 500 znakov
validation.stockMovementItemDTO.movementType.notNull=Vrsta premika je obvezna
validation.stockMovementItemDTO.productId.notNull=ID izdelka je obvezen
validation.stockMovementItemDTO.quantityDelta.digits=Količina ima lahko največ 10 celih in 3 decimalna mesta
validation.stockMovementItemDTO.quantityDelta.notNull=Količina je obvezna
validation.stockSnapshot.currentStock.notNull=Trenutna zaloga je obvezna
validation.stockSnapshot.integrityStatus.notBlank=Stanje celovitosti je obvezno
validation.stockSnapshot.lastSequenceNumber.notNull=Zaporedna številka je obvezna
validation.stockSnapshot.lastTransactionHash.notBlank=Zadnji zgošček (hash) je obvezen
validation.stockSnapshot.lastUpdated.notNull=Datum posodobitve je obvezen
validation.supplier.name.notBlank=Ime dobavitelja je obvezno
validation.supplier.name.size=Mora imeti med 2 in 100 znakov
validation.supplierRequestDTO.name.notBlank=Ime dobavitelja je obvezno
validation.supplierRequestDTO.name.size=Mora imeti med 2 in 100 znakov
validation.user.name.notBlank=Ime je obvezno
validation.user.name.size=Mora imeti med 2 in 100 znakov
validation.user.password.notBlank=Geslo je obvezno
validation.user.role.notNull=Vloga je obvezna
validation.user.user.notBlank=Uporabniško ime je obvezno
validation.userRequestDTO.name.notBlank=Ime je obvezno
validation.userRequestDTO.name.size=Mora imeti med 2 in 100 znakov
validation.userRequestDTO.password.notBlank=Geslo je obvezno
validation.userRequestDTO.password.size=Geslo mora imeti vsaj 6 znakov
validation.userRequestDTO.user.notBlank=Uporabniško ime je obvezno
validation.userRequestDTO.user.size=Uporabniško ime ne sme presegati 100 znakov
""",

"bg": """validation.allergen.name.notBlank=Името на алергена е задължително
validation.allergen.name.size=Трябва да е между 2 и 50 знака
validation.allergenRequestDTO.name.notBlank=Името на алергена е задължително
validation.allergenRequestDTO.name.size=Трябва да е между 2 и 50 знака
validation.batchStockMovementRequestDTO.movements.notEmpty=Трябва да се включи поне едно движение
validation.batchStockMovementRequestDTO.reason.size=Причината не може да надвишава 1000 знака
validation.changePasswordRequestDTO.newPassword.notBlank=Новата парола е задължителна
validation.changePasswordRequestDTO.newPassword.size=Новата парола трябва да има поне 6 знака
validation.inventoryAudit.actionDescription.size=Описанието не може да надвишава 500 знака
validation.inventoryAudit.product.notNull=Продуктът е задължителен
validation.inventoryAudit.quantity.notNull=Количеството е задължително
validation.inventoryAudit.unknown.notBlank=Типът на движение е задължителен
validation.inventoryMovementRequestDTO.movementType.notNull=Типът на движение е задължително
validation.inventoryMovementRequestDTO.productId.notNull=ID на продукта е задължително
validation.inventoryMovementRequestDTO.quantity.decimalMax=Количеството не може да надвишава 9 999 999,99
validation.inventoryMovementRequestDTO.quantity.notNull=Количеството е задължително
validation.inventoryMovementRequestDTO.quantity.positive=Количеството трябва да бъде по-голямо от нула
validation.inventoryMovementRequestDTO.userId.notNull=ID на потребителя е задължително
validation.jwtProperties.expiration.positive=Изтичането на JWT трябва да бъде положителна стойност
validation.jwtProperties.secret.notBlank=Тайната на JWT е задължителна
validation.loginRequestDTO.name.notBlank=Потребителското име е задължително
validation.loginRequestDTO.password.notBlank=Паролата е задължителна
validation.order.orderDate.notNull=Датата на поръчката е задължителна
validation.order.orderDate.pastOrPresent=Датата на поръчката не може да бъде в бъдещето
validation.order.status.notBlank=Състоянието е задължително
validation.order.users.notNull=Потребителят е задължителен
validation.orderAudit.action.notBlank=Действието е задължително
validation.orderAudit.details.size=Подробностите не могат да надвишават 1000 знака
validation.orderDetail.order.notNull=Поръчката е задължителна
validation.orderDetail.product.notNull=Продуктът е задължителен
validation.orderDetail.quantity.decimalMin=Количеството трябва да бъде по-голямо от 0
validation.orderDetail.quantity.notNull=Поисканото количество е задължително
validation.orderDetail.quantityReceived.decimalMin=Полученото количество не може да бъде отрицателно
validation.orderDetailRequestDTO.productId.notNull=ID на продукта е задължително
validation.orderDetailRequestDTO.quantity.decimalMin=Количеството трябва да бъде по-голямо от нула
validation.orderDetailRequestDTO.quantity.digits=Количеството може да има най-много 10 цели и 3 десетични цифри
validation.orderDetailRequestDTO.quantity.notNull=Количеството е задължително
validation.orderReceptionDetailRequestDTO.productId.notNull=ID на продукта е задължително
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Полученото количество е задължително
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Полученото количество трябва да бъде нула или по-голямо
validation.orderReceptionRequestDTO.items.notEmpty=Трябва да се посочи поне един получен продукт
validation.orderReceptionRequestDTO.orderId.notNull=ID на поръчката е задължително
validation.orderReceptionRequestDTO.status.notNull=Състоянието е задължително
validation.orderRequestDTO.details.notEmpty=Поръчката трябва да има поне една подробност
validation.orderRequestDTO.userId.notNull=ID на потребителя е задължително
validation.product.availabilityPercentage.decimalMax=Процентът на наличност не може да надвишава 100
validation.product.availabilityPercentage.decimalMin=Процентът на наличност не може да бъде отрицателен
validation.product.availabilityPercentage.digits=Невалиден формат на наличност
validation.product.currentStock.decimalMin=Запасът не може да бъде отрицателен
validation.product.currentStock.digits=Невалиден формат на запас
validation.product.currentStock.notNull=Текущият запас е задължителен
validation.product.minimumStock.decimalMin=Минималният запас не може да бъде отрицателен
validation.product.minimumStock.digits=Невалиден формат за минимален запас
validation.product.name.notBlank=Името на продукта е задължително
validation.product.name.size=Трябва да е между 2 и 100 знака
validation.product.productCode.notBlank=Кодът на продукта е задължителен
validation.product.unit.notBlank=Мерната единица е задължителна
validation.product.unitPrice.decimalMin=Цената трябва да бъде по-голяма от 0
validation.product.unitPrice.digits=Невалиден формат на цена
validation.product.unitPrice.notNull=Единичната цена е задължителна
validation.productRequestDTO.availabilityPercentage.decimalMax=Процентът на наличност не може да надвишава 100
validation.productRequestDTO.availabilityPercentage.decimalMin=Процентът на наличност не може да бъде отрицателен
validation.productRequestDTO.availabilityPercentage.digits=Процентът може да има най-много 3 цели и 2 десетични цифри
validation.productRequestDTO.currentStock.decimalMin=Запасът не може да бъде отрицателен
validation.productRequestDTO.currentStock.digits=Запасът може да има най-много 10 цели и 3 десетични цифри
validation.productRequestDTO.currentStock.notNull=Текущият запас е задължителен
validation.productRequestDTO.minimumStock.decimalMin=Минималният запас не може да бъде отрицателен
validation.productRequestDTO.minimumStock.digits=Минималният запас може да има най-много 10 цели и 3 десетични цифри
validation.productRequestDTO.minimumStock.notNull=Минималният запас е задължителен
validation.productRequestDTO.name.notBlank=Името на продукта е задължително
validation.productRequestDTO.name.size=Трябва да е между 2 и 100 знака
validation.productRequestDTO.productCode.notBlank=Кодът на продукта е задължителен
validation.productRequestDTO.productCode.size=Кодът не може да надвишава 50 знака
validation.productRequestDTO.unit.notBlank=Мерната единица е задължителна
validation.productRequestDTO.unit.size=Единицата не може да надвишава 20 знака
validation.productRequestDTO.unitPrice.decimalMin=Цената трябва да бъде по-голяма от нула
validation.productRequestDTO.unitPrice.digits=Цената може да има най-много 10 цели и 2 десетични цифри
validation.productRequestDTO.unitPrice.notNull=Единичната цена е задължителна
validation.recipe.elaboration.size=Приготвянето не може да надвишава 2000 знака
validation.recipe.name.notBlank=Името на рецептата е задължително
validation.recipe.name.size=Трябва да е между 2 и 150 знака
validation.recipe.presentation.size=Представянето не може да надвишава 1000 знака
validation.recipe.totalCost.decimalMin=Разходът не може да бъде отрицателен
validation.recipeAudit.action.notBlank=Действието е задължително
validation.recipeAudit.details.size=Подробностите не могат да надвишават 1000 знака
validation.recipeComponent.parentRecipe.notNull=Рецептата е задължителна
validation.recipeComponent.product.notNull=Продуктът е задължителен
validation.recipeComponent.quantity.decimalMin=Количеството трябва да бъде по-голямо от 0
validation.recipeComponent.quantity.notNull=Количеството е задължително
validation.recipeComponentRequestDTO.productId.notNull=ID на продукта е задължително
validation.recipeComponentRequestDTO.quantity.decimalMin=Количеството трябва да бъде по-голямо от нула
validation.recipeComponentRequestDTO.quantity.digits=Количеството може да има най-много 10 цели и 3 десетични цифри
validation.recipeComponentRequestDTO.quantity.notNull=Количеството е задължително
validation.recipeCookingAudit.details.size=Подробностите не могат да надвишават 1000 знака
validation.recipeCookingAudit.quantityCooked.decimalMin=Количеството трябва да бъде по-голямо от 0
validation.recipeCookingAudit.quantityCooked.notNull=Сготвеното количество е задължително
validation.recipeCookingAudit.recipe.notNull=Рецептата е задължителна
validation.recipeCookingRequestDTO.details.size=Подробностите не могат да надвишават 500 знака
validation.recipeCookingRequestDTO.quantity.decimalMin=Количеството трябва да бъде по-голямо от 0
validation.recipeCookingRequestDTO.quantity.digits=Количеството може да има най-много 10 цели и 3 десетични цифри
validation.recipeCookingRequestDTO.quantity.notNull=Количеството за готвене е задължително
validation.recipeCookingRequestDTO.recipeId.notNull=ID на рецептата е задължително
validation.recipeCookingRequestDTO.recipeId.positive=ID на рецептата трябва да бъде положително
validation.recipeRequestDTO.components.notEmpty=Рецептата трябва да включва поне един компонент
validation.recipeRequestDTO.elaboration.notBlank=Приготвянето е задължително
validation.recipeRequestDTO.elaboration.size=Приготвянето не може да надвишава 2000 знака
validation.recipeRequestDTO.name.notBlank=Името на рецептата е задължително
validation.recipeRequestDTO.name.size=Трябва да е между 2 и 150 знака
validation.recipeRequestDTO.presentation.notBlank=Представянето е задължително
validation.recipeRequestDTO.presentation.size=Представянето не може да надвишава 1000 знака
validation.roleEscalationRequestDTO.durationMinutes.max=Максималната разрешена продължителност е 1440 минути (24 часа)
validation.roleEscalationRequestDTO.durationMinutes.min=Минималната продължителност трябва да бъде 1 минута
validation.roleEscalationRequestDTO.durationMinutes.notNull=Продължителността в минути е задължителна
validation.stockLedger.currentHash.notBlank=Текущият хеш е задължителен
validation.stockLedger.movementType.notNull=Типът на движение е задължителен
validation.stockLedger.previousHash.notBlank=Предишният хеш е задължителен
validation.stockLedger.product.notNull=Продуктът е задължителен
validation.stockLedger.quantityDelta.notNull=Количеството е задължително
validation.stockLedger.resultingStock.notNull=Полученият запас е задължителен
validation.stockLedger.sequenceNumber.notNull=Поредният номер е задължителен
validation.stockLedger.transactionTimestamp.notNull=Времевият печат е задължителен
validation.stockMovementItemDTO.description.size=Описанието не може да надвишава 500 знака
validation.stockMovementItemDTO.movementType.notNull=Типът на движение е задължителен
validation.stockMovementItemDTO.productId.notNull=ID на продукта е задължително
validation.stockMovementItemDTO.quantityDelta.digits=Количеството може да има най-много 10 цели и 3 десетични цифри
validation.stockMovementItemDTO.quantityDelta.notNull=Количеството е задължително
validation.stockSnapshot.currentStock.notNull=Текущият запас е задължителен
validation.stockSnapshot.integrityStatus.notBlank=Статусът на цялост е задължителен
validation.stockSnapshot.lastSequenceNumber.notNull=Поредният номер е задължителен
validation.stockSnapshot.lastTransactionHash.notBlank=Последният хеш е задължителен
validation.stockSnapshot.lastUpdated.notNull=Датата на актуализация е задължителна
validation.supplier.name.notBlank=Името на доставчика е задължително
validation.supplier.name.size=Трябва да е между 2 и 100 знака
validation.supplierRequestDTO.name.notBlank=Името на доставчика е задължително
validation.supplierRequestDTO.name.size=Трябва да е между 2 и 100 знака
validation.user.name.notBlank=Името е задължително
validation.user.name.size=Трябва да е между 2 и 100 знака
validation.user.password.notBlank=Паролата е задължителна
validation.user.role.notNull=Ролята е задължителна
validation.user.user.notBlank=Потребителското име е задължително
validation.userRequestDTO.name.notBlank=Името е задължително
validation.userRequestDTO.name.size=Трябва да е между 2 и 100 знака
validation.userRequestDTO.password.notBlank=Паролата е задължителна
validation.userRequestDTO.password.size=Паролата трябва да има поне 6 знака
validation.userRequestDTO.user.notBlank=Потребителското име е задължително
validation.userRequestDTO.user.size=Потребителското име не може да надвишава 100 знака
""",

"is": """validation.allergen.name.notBlank=Nafn ofnæmisvaldsins er nauðsynlegt
validation.allergen.name.size=Verður að vera á milli 2 og 50 stafir
validation.allergenRequestDTO.name.notBlank=Nafn ofnæmisvaldsins er nauðsynlegt
validation.allergenRequestDTO.name.size=Verður að vera á milli 2 og 50 stafir
validation.batchStockMovementRequestDTO.movements.notEmpty=Gera þarf grein fyrir að minnsta kosti einni hreyfingu
validation.batchStockMovementRequestDTO.reason.size=Ástæðan má ekki vera lengri en 1000 stafir
validation.changePasswordRequestDTO.newPassword.notBlank=Nýja lykilorðið er nauðsynlegt
validation.changePasswordRequestDTO.newPassword.size=Nýja lykilorðið verður að vera að minnsta kosti 6 stafir
validation.inventoryAudit.actionDescription.size=Lýsingin má ekki vera lengri en 500 stafir
validation.inventoryAudit.product.notNull=Varan er nauðsynleg
validation.inventoryAudit.quantity.notNull=Magnið er nauðsynlegt
validation.inventoryAudit.unknown.notBlank=Hreyfingartegundin er nauðsynleg
validation.inventoryMovementRequestDTO.movementType.notNull=Hreyfingartegundin er nauðsynleg
validation.inventoryMovementRequestDTO.productId.notNull=Auðkenni vörunnar er nauðsynlegt
validation.inventoryMovementRequestDTO.quantity.decimalMax=Magnið má ekki vera meira en 9.999.999,99
validation.inventoryMovementRequestDTO.quantity.notNull=Magnið er nauðsynlegt
validation.inventoryMovementRequestDTO.quantity.positive=Magnið verður að vera stærra en núll
validation.inventoryMovementRequestDTO.userId.notNull=Auðkenni notandans er nauðsynlegt
validation.jwtProperties.expiration.positive=JWT rennur út verður að vera jákvætt gildi
validation.jwtProperties.secret.notBlank=JWT leyndarmálið er nauðsynlegt
validation.loginRequestDTO.name.notBlank=Notandanafnið er nauðsynlegt
validation.loginRequestDTO.password.notBlank=Lykilorðið er nauðsynlegt
validation.order.orderDate.notNull=Pöntunardagsetningin er nauðsynleg
validation.order.orderDate.pastOrPresent=Pöntunardagsetningin má ekki vera í framtíðinni
validation.order.status.notBlank=Staðan er nauðsynleg
validation.order.users.notNull=Notandinn er nauðsynlegur
validation.orderAudit.action.notBlank=Aðgerðin er nauðsynleg
validation.orderAudit.details.size=Upplýsingarnar mega ekki vera lengri en 1000 stafir
validation.orderDetail.order.notNull=Pöntunin er nauðsynleg
validation.orderDetail.product.notNull=Varan er nauðsynleg
validation.orderDetail.quantity.decimalMin=Magnið verður að vera stærra en 0
validation.orderDetail.quantity.notNull=Umbeðið magn er nauðsynlegt
validation.orderDetail.quantityReceived.decimalMin=Móttekið magn má ekki vera neikvætt
validation.orderDetailRequestDTO.productId.notNull=Auðkenni vörunnar er nauðsynlegt
validation.orderDetailRequestDTO.quantity.decimalMin=Magnið verður að vera stærra en núll
validation.orderDetailRequestDTO.quantity.digits=Magnið má í mesta lagi hafa 10 heiltölur og 3 aukastafi
validation.orderDetailRequestDTO.quantity.notNull=Magnið er nauðsynlegt
validation.orderReceptionDetailRequestDTO.productId.notNull=Auðkenni vörunnar er nauðsynlegt
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Móttekið magn er nauðsynlegt
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Móttekið magn verður að vera núll eða meira
validation.orderReceptionRequestDTO.items.notEmpty=Gera þarf grein fyrir að minnsta kosti einni móttekinni vöru
validation.orderReceptionRequestDTO.orderId.notNull=Auðkenni pöntunarinnar er nauðsynlegt
validation.orderReceptionRequestDTO.status.notNull=Staðan er nauðsynleg
validation.orderRequestDTO.details.notEmpty=Pöntunin verður að hafa að minnsta kosti einn hlut
validation.orderRequestDTO.userId.notNull=Auðkenni notandans er nauðsynlegt
validation.product.availabilityPercentage.decimalMax=Framboðsprósenta má ekki vera meira en 100
validation.product.availabilityPercentage.decimalMin=Framboðsprósenta má ekki vera neikvæð
validation.product.availabilityPercentage.digits=Ógilt framboðssnið
validation.product.currentStock.decimalMin=Birgðir mega ekki vera neikvæðar
validation.product.currentStock.digits=Ógilt birgðasnið
validation.product.currentStock.notNull=Núverandi birgðir eru nauðsynlegar
validation.product.minimumStock.decimalMin=Lágmarksbirgðir mega ekki vera neikvæðar
validation.product.minimumStock.digits=Ógilt snið lágmarksbirgða
validation.product.name.notBlank=Nafn vörunnar er nauðsynlegt
validation.product.name.size=Verður að vera á milli 2 og 100 stafir
validation.product.productCode.notBlank=Vörukóði er nauðsynlegur
validation.product.unit.notBlank=Mælieiningin er nauðsynleg
validation.product.unitPrice.decimalMin=Verðið verður að vera stærra en 0
validation.product.unitPrice.digits=Ógilt verðsnið
validation.product.unitPrice.notNull=Einingaverðið er nauðsynlegt
validation.productRequestDTO.availabilityPercentage.decimalMax=Framboðsprósenta má ekki vera meira en 100
validation.productRequestDTO.availabilityPercentage.decimalMin=Framboðsprósenta má ekki vera neikvæð
validation.productRequestDTO.availabilityPercentage.digits=Prósentan má í mesta lagi hafa 3 heiltölur og 2 aukastafi
validation.productRequestDTO.currentStock.decimalMin=Birgðir mega ekki vera neikvæðar
validation.productRequestDTO.currentStock.digits=Birgðir mega í mesta lagi hafa 10 heiltölur og 3 aukastafi
validation.productRequestDTO.currentStock.notNull=Núverandi birgðir eru nauðsynlegar
validation.productRequestDTO.minimumStock.decimalMin=Lágmarksbirgðir mega ekki vera neikvæðar
validation.productRequestDTO.minimumStock.digits=Lágmarksbirgðir mega í mesta lagi hafa 10 heiltölur og 3 aukastafi
validation.productRequestDTO.minimumStock.notNull=Lágmarksbirgðir eru nauðsynlegar
validation.productRequestDTO.name.notBlank=Nafn vörunnar er nauðsynlegt
validation.productRequestDTO.name.size=Verður að vera á milli 2 og 100 stafir
validation.productRequestDTO.productCode.notBlank=Vörukóði er nauðsynlegur
validation.productRequestDTO.productCode.size=Kóðinn má ekki vera lengri en 50 stafir
validation.productRequestDTO.unit.notBlank=Mælieiningin er nauðsynleg
validation.productRequestDTO.unit.size=Einingin má ekki vera lengri en 20 stafir
validation.productRequestDTO.unitPrice.decimalMin=Verðið verður að vera stærra en núll
validation.productRequestDTO.unitPrice.digits=Verðið má í mesta lagi hafa 10 heiltölur og 2 aukastafi
validation.productRequestDTO.unitPrice.notNull=Einingaverðið er nauðsynlegt
validation.recipe.elaboration.size=Undirbúningurinn má ekki vera lengri en 2000 stafir
validation.recipe.name.notBlank=Nafn uppskriftarinnar er nauðsynlegt
validation.recipe.name.size=Verður að vera á milli 2 og 150 stafir
validation.recipe.presentation.size=Kynningin má ekki vera lengri en 1000 stafir
validation.recipe.totalCost.decimalMin=Kostnaðurinn má ekki vera neikvæður
validation.recipeAudit.action.notBlank=Aðgerðin er nauðsynleg
validation.recipeAudit.details.size=Upplýsingarnar mega ekki vera lengri en 1000 stafir
validation.recipeComponent.parentRecipe.notNull=Uppskriftin er nauðsynleg
validation.recipeComponent.product.notNull=Varan er nauðsynleg
validation.recipeComponent.quantity.decimalMin=Magnið verður að vera stærra en 0
validation.recipeComponent.quantity.notNull=Magnið er nauðsynlegt
validation.recipeComponentRequestDTO.productId.notNull=Auðkenni vörunnar er nauðsynlegt
validation.recipeComponentRequestDTO.quantity.decimalMin=Magnið verður að vera stærra en núll
validation.recipeComponentRequestDTO.quantity.digits=Magnið má í mesta lagi hafa 10 heiltölur og 3 aukastafi
validation.recipeComponentRequestDTO.quantity.notNull=Magnið er nauðsynlegt
validation.recipeCookingAudit.details.size=Upplýsingarnar mega ekki vera lengri en 1000 stafir
validation.recipeCookingAudit.quantityCooked.decimalMin=Magnið verður að vera stærra en 0
validation.recipeCookingAudit.quantityCooked.notNull=Eldað magn er nauðsynlegt
validation.recipeCookingAudit.recipe.notNull=Uppskriftin er nauðsynleg
validation.recipeCookingRequestDTO.details.size=Upplýsingarnar mega ekki vera lengri en 500 stafir
validation.recipeCookingRequestDTO.quantity.decimalMin=Magnið verður að vera stærra en 0
validation.recipeCookingRequestDTO.quantity.digits=Magnið má í mesta lagi hafa 10 heiltölur og 3 aukastafi
validation.recipeCookingRequestDTO.quantity.notNull=Magnið sem á að elda er nauðsynlegt
validation.recipeCookingRequestDTO.recipeId.notNull=Auðkenni uppskriftarinnar er nauðsynlegt
validation.recipeCookingRequestDTO.recipeId.positive=Auðkenni uppskriftarinnar verður að vera jákvætt
validation.recipeRequestDTO.components.notEmpty=Uppskriftin verður að innihalda að minnsta kosti eitt efni
validation.recipeRequestDTO.elaboration.notBlank=Undirbúningurinn er nauðsynlegur
validation.recipeRequestDTO.elaboration.size=Undirbúningurinn má ekki vera lengri en 2000 stafir
validation.recipeRequestDTO.name.notBlank=Nafn uppskriftarinnar er nauðsynlegt
validation.recipeRequestDTO.name.size=Verður að vera á milli 2 og 150 stafir
validation.recipeRequestDTO.presentation.notBlank=Kynningin er nauðsynleg
validation.recipeRequestDTO.presentation.size=Kynningin má ekki vera lengri en 1000 stafir
validation.roleEscalationRequestDTO.durationMinutes.max=Hámarks leyfður tími er 1440 mínútur (24 klukkustundir)
validation.roleEscalationRequestDTO.durationMinutes.min=Lágmarkstími verður að vera 1 mínúta
validation.roleEscalationRequestDTO.durationMinutes.notNull=Tíminn í mínútum er nauðsynlegur
validation.stockLedger.currentHash.notBlank=Núverandi kjötkássa (hash) er nauðsynleg
validation.stockLedger.movementType.notNull=Hreyfingartegundin er nauðsynleg
validation.stockLedger.previousHash.notBlank=Fyrri kjötkássa (hash) er nauðsynleg
validation.stockLedger.product.notNull=Varan er nauðsynleg
validation.stockLedger.quantityDelta.notNull=Magnið er nauðsynlegt
validation.stockLedger.resultingStock.notNull=Birgðir sem afleiðing eru nauðsynlegar
validation.stockLedger.sequenceNumber.notNull=Raðnúmerið er nauðsynlegt
validation.stockLedger.transactionTimestamp.notNull=Tímastimpillinn er nauðsynlegur
validation.stockMovementItemDTO.description.size=Lýsingin má ekki vera lengri en 500 stafir
validation.stockMovementItemDTO.movementType.notNull=Hreyfingartegundin er nauðsynleg
validation.stockMovementItemDTO.productId.notNull=Auðkenni vörunnar er nauðsynlegt
validation.stockMovementItemDTO.quantityDelta.digits=Magnið má í mesta lagi hafa 10 heiltölur og 3 aukastafi
validation.stockMovementItemDTO.quantityDelta.notNull=Magnið er nauðsynlegt
validation.stockSnapshot.currentStock.notNull=Núverandi birgðir eru nauðsynlegar
validation.stockSnapshot.integrityStatus.notBlank=Staða heilleika er nauðsynleg
validation.stockSnapshot.lastSequenceNumber.notNull=Raðnúmerið er nauðsynlegt
validation.stockSnapshot.lastTransactionHash.notBlank=Síðasta kjötkássa (hash) er nauðsynleg
validation.stockSnapshot.lastUpdated.notNull=Uppfærsludagsetningin er nauðsynleg
validation.supplier.name.notBlank=Nafn birgis er nauðsynlegt
validation.supplier.name.size=Verður að vera á milli 2 og 100 stafir
validation.supplierRequestDTO.name.notBlank=Nafn birgis er nauðsynlegt
validation.supplierRequestDTO.name.size=Verður að vera á milli 2 og 100 stafir
validation.user.name.notBlank=Nafnið er nauðsynlegt
validation.user.name.size=Verður að vera á milli 2 og 100 stafir
validation.user.password.notBlank=Lykilorðið er nauðsynlegt
validation.user.role.notNull=Hlutverkið er nauðsynlegt
validation.user.user.notBlank=Notandanafnið er nauðsynlegt
validation.userRequestDTO.name.notBlank=Nafnið er nauðsynlegt
validation.userRequestDTO.name.size=Verður að vera á milli 2 og 100 stafir
validation.userRequestDTO.password.notBlank=Lykilorðið er nauðsynlegt
validation.userRequestDTO.password.size=Lykilorðið verður að vera að minnsta kosti 6 stafir
validation.userRequestDTO.user.notBlank=Notandanafnið er nauðsynlegt
validation.userRequestDTO.user.size=Notandanafnið má ekki vera lengra en 100 stafir
"""
}

for lang, content in FILES.items():
    path = os.path.join(VDIR, f"ValidationMessages_{lang}.properties")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content.strip() + "\n")
    lines = [l for l in content.strip().split("\n") if "=" in l]
    print(f"  {lang}: wrote {len(lines)} keys")
