#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Writes complete FR, IT, PT, CA ValidationMessages files directly to disk."""
import os
VDIR = "src/main/resources/i18n/validation/"

FILES = {
"fr": """validation.allergen.name.notBlank=Le nom de l'allergène est obligatoire
validation.allergen.name.size=Doit contenir entre 2 et 50 caractères
validation.allergenRequestDTO.name.notBlank=Le nom de l'allergène est obligatoire
validation.allergenRequestDTO.name.size=Doit contenir entre 2 et 50 caractères
validation.batchStockMovementRequestDTO.movements.notEmpty=Au moins un mouvement doit être inclus
validation.batchStockMovementRequestDTO.reason.size=La raison ne peut pas dépasser 1000 caractères
validation.changePasswordRequestDTO.newPassword.notBlank=Le nouveau mot de passe est obligatoire
validation.changePasswordRequestDTO.newPassword.size=Le nouveau mot de passe doit comporter au moins 6 caractères
validation.inventoryAudit.actionDescription.size=La description ne peut pas dépasser 500 caractères
validation.inventoryAudit.product.notNull=Le produit est obligatoire
validation.inventoryAudit.quantity.notNull=La quantité est obligatoire
validation.inventoryAudit.unknown.notBlank=Le type de mouvement est obligatoire
validation.inventoryMovementRequestDTO.movementType.notNull=Le type de mouvement est obligatoire
validation.inventoryMovementRequestDTO.productId.notNull=L'identifiant du produit est obligatoire
validation.inventoryMovementRequestDTO.quantity.decimalMax=La quantité ne peut pas dépasser 9 999 999,99
validation.inventoryMovementRequestDTO.quantity.notNull=La quantité est obligatoire
validation.inventoryMovementRequestDTO.quantity.positive=La quantité doit être supérieure à zéro
validation.inventoryMovementRequestDTO.userId.notNull=L'identifiant de l'utilisateur est obligatoire
validation.jwtProperties.expiration.positive=L'expiration JWT doit être une valeur positive
validation.jwtProperties.secret.notBlank=Le secret JWT est obligatoire
validation.loginRequestDTO.name.notBlank=Le nom d'utilisateur est obligatoire
validation.loginRequestDTO.password.notBlank=Le mot de passe est obligatoire
validation.order.orderDate.notNull=La date de commande est obligatoire
validation.order.orderDate.pastOrPresent=La date de commande ne peut pas être dans le futur
validation.order.status.notBlank=Le statut est obligatoire
validation.order.users.notNull=L'utilisateur est obligatoire
validation.orderAudit.action.notBlank=L'action est obligatoire
validation.orderAudit.details.size=Les détails ne peuvent pas dépasser 1000 caractères
validation.orderDetail.order.notNull=La commande est obligatoire
validation.orderDetail.product.notNull=Le produit est obligatoire
validation.orderDetail.quantity.decimalMin=La quantité doit être supérieure à 0
validation.orderDetail.quantity.notNull=La quantité demandée est obligatoire
validation.orderDetail.quantityReceived.decimalMin=La quantité reçue ne peut pas être négative
validation.orderDetailRequestDTO.productId.notNull=L'identifiant du produit est obligatoire
validation.orderDetailRequestDTO.quantity.decimalMin=La quantité doit être supérieure à zéro
validation.orderDetailRequestDTO.quantity.digits=La quantité doit comporter au maximum 10 chiffres entiers et 3 décimales
validation.orderDetailRequestDTO.quantity.notNull=La quantité est obligatoire
validation.orderReceptionDetailRequestDTO.productId.notNull=L'identifiant du produit est obligatoire
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=La quantité reçue est obligatoire
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=La quantité reçue doit être supérieure ou égale à zéro
validation.orderReceptionRequestDTO.items.notEmpty=Au moins un produit reçu doit être spécifié
validation.orderReceptionRequestDTO.orderId.notNull=L'identifiant de la commande est obligatoire
validation.orderReceptionRequestDTO.status.notNull=Le statut est obligatoire
validation.orderRequestDTO.details.notEmpty=La commande doit comporter au moins un détail
validation.orderRequestDTO.userId.notNull=L'identifiant de l'utilisateur est obligatoire
validation.product.availabilityPercentage.decimalMax=Le pourcentage de disponibilité ne peut pas dépasser 100
validation.product.availabilityPercentage.decimalMin=Le pourcentage de disponibilité ne peut pas être négatif
validation.product.availabilityPercentage.digits=Format de disponibilité invalide
validation.product.currentStock.decimalMin=Le stock ne peut pas être négatif
validation.product.currentStock.digits=Format de stock invalide
validation.product.currentStock.notNull=Le stock actuel est obligatoire
validation.product.minimumStock.decimalMin=Le stock minimum ne peut pas être négatif
validation.product.minimumStock.digits=Format de stock minimum invalide
validation.product.name.notBlank=Le nom du produit est obligatoire
validation.product.name.size=Doit contenir entre 2 et 100 caractères
validation.product.productCode.notBlank=Le code produit est obligatoire
validation.product.unit.notBlank=L'unité de mesure est obligatoire
validation.product.unitPrice.decimalMin=Le prix doit être supérieur à 0
validation.product.unitPrice.digits=Format de prix invalide
validation.product.unitPrice.notNull=Le prix unitaire est obligatoire
validation.productRequestDTO.availabilityPercentage.decimalMax=Le pourcentage de disponibilité ne peut pas dépasser 100
validation.productRequestDTO.availabilityPercentage.decimalMin=Le pourcentage de disponibilité ne peut pas être négatif
validation.productRequestDTO.availabilityPercentage.digits=Le pourcentage doit comporter au maximum 3 chiffres entiers et 2 décimales
validation.productRequestDTO.currentStock.decimalMin=Le stock ne peut pas être négatif
validation.productRequestDTO.currentStock.digits=Le stock doit comporter au maximum 10 chiffres entiers et 3 décimales
validation.productRequestDTO.currentStock.notNull=Le stock actuel est obligatoire
validation.productRequestDTO.minimumStock.decimalMin=Le stock minimum ne peut pas être négatif
validation.productRequestDTO.minimumStock.digits=Le stock minimum doit comporter au maximum 10 chiffres entiers et 3 décimales
validation.productRequestDTO.minimumStock.notNull=Le stock minimum est obligatoire
validation.productRequestDTO.name.notBlank=Le nom du produit est obligatoire
validation.productRequestDTO.name.size=Doit contenir entre 2 et 100 caractères
validation.productRequestDTO.productCode.notBlank=Le code produit est obligatoire
validation.productRequestDTO.productCode.size=Le code ne peut pas dépasser 50 caractères
validation.productRequestDTO.unit.notBlank=L'unité de mesure est obligatoire
validation.productRequestDTO.unit.size=L'unité ne peut pas dépasser 20 caractères
validation.productRequestDTO.unitPrice.decimalMin=Le prix doit être supérieur à zéro
validation.productRequestDTO.unitPrice.digits=Le prix doit comporter au maximum 10 chiffres entiers et 2 décimales
validation.productRequestDTO.unitPrice.notNull=Le prix unitaire est obligatoire
validation.recipe.elaboration.size=L'élaboration ne peut pas dépasser 2000 caractères
validation.recipe.name.notBlank=Le nom de la recette est obligatoire
validation.recipe.name.size=Doit contenir entre 2 et 150 caractères
validation.recipe.presentation.size=La présentation ne peut pas dépasser 1000 caractères
validation.recipe.totalCost.decimalMin=Le coût ne peut pas être négatif
validation.recipeAudit.action.notBlank=L'action est obligatoire
validation.recipeAudit.details.size=Les détails ne peuvent pas dépasser 1000 caractères
validation.recipeComponent.parentRecipe.notNull=La recette est obligatoire
validation.recipeComponent.product.notNull=Le produit est obligatoire
validation.recipeComponent.quantity.decimalMin=La quantité doit être supérieure à 0
validation.recipeComponent.quantity.notNull=La quantité est obligatoire
validation.recipeComponentRequestDTO.productId.notNull=L'identifiant du produit est obligatoire
validation.recipeComponentRequestDTO.quantity.decimalMin=La quantité doit être supérieure à zéro
validation.recipeComponentRequestDTO.quantity.digits=La quantité doit comporter au maximum 10 chiffres entiers et 3 décimales
validation.recipeComponentRequestDTO.quantity.notNull=La quantité est obligatoire
validation.recipeCookingAudit.details.size=Les détails ne peuvent pas dépasser 1000 caractères
validation.recipeCookingAudit.quantityCooked.decimalMin=La quantité doit être supérieure à 0
validation.recipeCookingAudit.quantityCooked.notNull=La quantité cuisinée est obligatoire
validation.recipeCookingAudit.recipe.notNull=La recette est obligatoire
validation.recipeCookingRequestDTO.details.size=Les détails ne peuvent pas dépasser 500 caractères
validation.recipeCookingRequestDTO.quantity.decimalMin=La quantité doit être supérieure à 0
validation.recipeCookingRequestDTO.quantity.digits=La quantité doit comporter au maximum 10 chiffres entiers et 3 décimales
validation.recipeCookingRequestDTO.quantity.notNull=La quantité à cuisiner est obligatoire
validation.recipeCookingRequestDTO.recipeId.notNull=L'identifiant de la recette est obligatoire
validation.recipeCookingRequestDTO.recipeId.positive=L'identifiant de la recette doit être positif
validation.recipeRequestDTO.components.notEmpty=La recette doit inclure au moins un composant
validation.recipeRequestDTO.elaboration.notBlank=L'élaboration est obligatoire
validation.recipeRequestDTO.elaboration.size=L'élaboration ne peut pas dépasser 2000 caractères
validation.recipeRequestDTO.name.notBlank=Le nom de la recette est obligatoire
validation.recipeRequestDTO.name.size=Doit contenir entre 2 et 150 caractères
validation.recipeRequestDTO.presentation.notBlank=La présentation est obligatoire
validation.recipeRequestDTO.presentation.size=La présentation ne peut pas dépasser 1000 caractères
validation.roleEscalationRequestDTO.durationMinutes.max=La durée maximale autorisée est de 1440 minutes (24 heures)
validation.roleEscalationRequestDTO.durationMinutes.min=La durée minimale doit être de 1 minute
validation.roleEscalationRequestDTO.durationMinutes.notNull=La durée en minutes est obligatoire
validation.stockLedger.currentHash.notBlank=Le hash actuel est obligatoire
validation.stockLedger.movementType.notNull=Le type de mouvement est obligatoire
validation.stockLedger.previousHash.notBlank=Le hash précédent est obligatoire
validation.stockLedger.product.notNull=Le produit est obligatoire
validation.stockLedger.quantityDelta.notNull=La quantité est obligatoire
validation.stockLedger.resultingStock.notNull=Le stock résultant est obligatoire
validation.stockLedger.sequenceNumber.notNull=Le numéro de séquence est obligatoire
validation.stockLedger.transactionTimestamp.notNull=L'horodatage est obligatoire
validation.stockMovementItemDTO.description.size=La description ne peut pas dépasser 500 caractères
validation.stockMovementItemDTO.movementType.notNull=Le type de mouvement est obligatoire
validation.stockMovementItemDTO.productId.notNull=L'identifiant du produit est obligatoire
validation.stockMovementItemDTO.quantityDelta.digits=La quantité doit comporter au maximum 10 chiffres entiers et 3 décimales
validation.stockMovementItemDTO.quantityDelta.notNull=La quantité est obligatoire
validation.stockSnapshot.currentStock.notNull=Le stock actuel est obligatoire
validation.stockSnapshot.integrityStatus.notBlank=Le statut d'intégrité est obligatoire
validation.stockSnapshot.lastSequenceNumber.notNull=Le numéro de séquence est obligatoire
validation.stockSnapshot.lastTransactionHash.notBlank=Le dernier hash est obligatoire
validation.stockSnapshot.lastUpdated.notNull=La date de mise à jour est obligatoire
validation.supplier.name.notBlank=Le nom du fournisseur est obligatoire
validation.supplier.name.size=Doit contenir entre 2 et 100 caractères
validation.supplierRequestDTO.name.notBlank=Le nom du fournisseur est obligatoire
validation.supplierRequestDTO.name.size=Doit contenir entre 2 et 100 caractères
validation.user.name.notBlank=Le nom est obligatoire
validation.user.name.size=Doit contenir entre 2 et 100 caractères
validation.user.password.notBlank=Le mot de passe est obligatoire
validation.user.role.notNull=Le rôle est obligatoire
validation.user.user.notBlank=Le nom d'utilisateur est obligatoire
validation.userRequestDTO.name.notBlank=Le nom est obligatoire
validation.userRequestDTO.name.size=Doit contenir entre 2 et 100 caractères
validation.userRequestDTO.password.notBlank=Le mot de passe est obligatoire
validation.userRequestDTO.password.size=Le mot de passe doit comporter au moins 6 caractères
validation.userRequestDTO.user.notBlank=Le nom d'utilisateur est obligatoire
validation.userRequestDTO.user.size=Le nom d'utilisateur ne peut pas dépasser 100 caractères
""",

"it": """validation.allergen.name.notBlank=Il nome dell'allergene è obbligatorio
validation.allergen.name.size=Deve contenere tra 2 e 50 caratteri
validation.allergenRequestDTO.name.notBlank=Il nome dell'allergene è obbligatorio
validation.allergenRequestDTO.name.size=Deve contenere tra 2 e 50 caratteri
validation.batchStockMovementRequestDTO.movements.notEmpty=È necessario includere almeno un movimento
validation.batchStockMovementRequestDTO.reason.size=Il motivo non può superare i 1000 caratteri
validation.changePasswordRequestDTO.newPassword.notBlank=La nuova password è obbligatoria
validation.changePasswordRequestDTO.newPassword.size=La nuova password deve avere almeno 6 caratteri
validation.inventoryAudit.actionDescription.size=La descrizione non può superare i 500 caratteri
validation.inventoryAudit.product.notNull=Il prodotto è obbligatorio
validation.inventoryAudit.quantity.notNull=La quantità è obbligatoria
validation.inventoryAudit.unknown.notBlank=Il tipo di movimento è obbligatorio
validation.inventoryMovementRequestDTO.movementType.notNull=Il tipo di movimento è obbligatorio
validation.inventoryMovementRequestDTO.productId.notNull=L'ID del prodotto è obbligatorio
validation.inventoryMovementRequestDTO.quantity.decimalMax=La quantità non può superare 9.999.999,99
validation.inventoryMovementRequestDTO.quantity.notNull=La quantità è obbligatoria
validation.inventoryMovementRequestDTO.quantity.positive=La quantità deve essere maggiore di zero
validation.inventoryMovementRequestDTO.userId.notNull=L'ID dell'utente è obbligatorio
validation.jwtProperties.expiration.positive=La scadenza JWT deve essere un valore positivo
validation.jwtProperties.secret.notBlank=Il segreto JWT è obbligatorio
validation.loginRequestDTO.name.notBlank=Il nome utente è obbligatorio
validation.loginRequestDTO.password.notBlank=La password è obbligatoria
validation.order.orderDate.notNull=La data dell'ordine è obbligatoria
validation.order.orderDate.pastOrPresent=La data dell'ordine non può essere nel futuro
validation.order.status.notBlank=Lo stato è obbligatorio
validation.order.users.notNull=L'utente è obbligatorio
validation.orderAudit.action.notBlank=L'azione è obbligatoria
validation.orderAudit.details.size=I dettagli non possono superare i 1000 caratteri
validation.orderDetail.order.notNull=L'ordine è obbligatorio
validation.orderDetail.product.notNull=Il prodotto è obbligatorio
validation.orderDetail.quantity.decimalMin=La quantità deve essere maggiore di 0
validation.orderDetail.quantity.notNull=La quantità richiesta è obbligatoria
validation.orderDetail.quantityReceived.decimalMin=La quantità ricevuta non può essere negativa
validation.orderDetailRequestDTO.productId.notNull=L'ID del prodotto è obbligatorio
validation.orderDetailRequestDTO.quantity.decimalMin=La quantità deve essere maggiore di zero
validation.orderDetailRequestDTO.quantity.digits=La quantità deve avere al massimo 10 cifre intere e 3 decimali
validation.orderDetailRequestDTO.quantity.notNull=La quantità è obbligatoria
validation.orderReceptionDetailRequestDTO.productId.notNull=L'ID del prodotto è obbligatorio
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=La quantità ricevuta è obbligatoria
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=La quantità ricevuta deve essere maggiore o uguale a zero
validation.orderReceptionRequestDTO.items.notEmpty=È necessario specificare almeno un prodotto ricevuto
validation.orderReceptionRequestDTO.orderId.notNull=L'ID dell'ordine è obbligatorio
validation.orderReceptionRequestDTO.status.notNull=Lo stato è obbligatorio
validation.orderRequestDTO.details.notEmpty=L'ordine deve avere almeno un dettaglio
validation.orderRequestDTO.userId.notNull=L'ID dell'utente è obbligatorio
validation.product.availabilityPercentage.decimalMax=La percentuale di disponibilità non può superare 100
validation.product.availabilityPercentage.decimalMin=La percentuale di disponibilità non può essere negativa
validation.product.availabilityPercentage.digits=Formato di disponibilità non valido
validation.product.currentStock.decimalMin=La giacenza non può essere negativa
validation.product.currentStock.digits=Formato di giacenza non valido
validation.product.currentStock.notNull=La giacenza attuale è obbligatoria
validation.product.minimumStock.decimalMin=La giacenza minima non può essere negativa
validation.product.minimumStock.digits=Formato di giacenza minima non valido
validation.product.name.notBlank=Il nome del prodotto è obbligatorio
validation.product.name.size=Deve contenere tra 2 e 100 caratteri
validation.product.productCode.notBlank=Il codice prodotto è obbligatorio
validation.product.unit.notBlank=L'unità di misura è obbligatoria
validation.product.unitPrice.decimalMin=Il prezzo deve essere maggiore di 0
validation.product.unitPrice.digits=Formato di prezzo non valido
validation.product.unitPrice.notNull=Il prezzo unitario è obbligatorio
validation.productRequestDTO.availabilityPercentage.decimalMax=La percentuale di disponibilità non può superare 100
validation.productRequestDTO.availabilityPercentage.decimalMin=La percentuale di disponibilità non può essere negativa
validation.productRequestDTO.availabilityPercentage.digits=La percentuale deve avere al massimo 3 cifre intere e 2 decimali
validation.productRequestDTO.currentStock.decimalMin=La giacenza non può essere negativa
validation.productRequestDTO.currentStock.digits=La giacenza deve avere al massimo 10 cifre intere e 3 decimali
validation.productRequestDTO.currentStock.notNull=La giacenza attuale è obbligatoria
validation.productRequestDTO.minimumStock.decimalMin=La giacenza minima non può essere negativa
validation.productRequestDTO.minimumStock.digits=La giacenza minima deve avere al massimo 10 cifre intere e 3 decimali
validation.productRequestDTO.minimumStock.notNull=La giacenza minima è obbligatoria
validation.productRequestDTO.name.notBlank=Il nome del prodotto è obbligatorio
validation.productRequestDTO.name.size=Deve contenere tra 2 e 100 caratteri
validation.productRequestDTO.productCode.notBlank=Il codice prodotto è obbligatorio
validation.productRequestDTO.productCode.size=Il codice non può superare i 50 caratteri
validation.productRequestDTO.unit.notBlank=L'unità di misura è obbligatoria
validation.productRequestDTO.unit.size=L'unità non può superare i 20 caratteri
validation.productRequestDTO.unitPrice.decimalMin=Il prezzo deve essere maggiore di zero
validation.productRequestDTO.unitPrice.digits=Il prezzo deve avere al massimo 10 cifre intere e 2 decimali
validation.productRequestDTO.unitPrice.notNull=Il prezzo unitario è obbligatorio
validation.recipe.elaboration.size=L'elaborazione non può superare i 2000 caratteri
validation.recipe.name.notBlank=Il nome della ricetta è obbligatorio
validation.recipe.name.size=Deve contenere tra 2 e 150 caratteri
validation.recipe.presentation.size=La presentazione non può superare i 1000 caratteri
validation.recipe.totalCost.decimalMin=Il costo non può essere negativo
validation.recipeAudit.action.notBlank=L'azione è obbligatoria
validation.recipeAudit.details.size=I dettagli non possono superare i 1000 caratteri
validation.recipeComponent.parentRecipe.notNull=La ricetta è obbligatoria
validation.recipeComponent.product.notNull=Il prodotto è obbligatorio
validation.recipeComponent.quantity.decimalMin=La quantità deve essere maggiore di 0
validation.recipeComponent.quantity.notNull=La quantità è obbligatoria
validation.recipeComponentRequestDTO.productId.notNull=L'ID del prodotto è obbligatorio
validation.recipeComponentRequestDTO.quantity.decimalMin=La quantità deve essere maggiore di zero
validation.recipeComponentRequestDTO.quantity.digits=La quantità deve avere al massimo 10 cifre intere e 3 decimali
validation.recipeComponentRequestDTO.quantity.notNull=La quantità è obbligatoria
validation.recipeCookingAudit.details.size=I dettagli non possono superare i 1000 caratteri
validation.recipeCookingAudit.quantityCooked.decimalMin=La quantità deve essere maggiore di 0
validation.recipeCookingAudit.quantityCooked.notNull=La quantità cucinata è obbligatoria
validation.recipeCookingAudit.recipe.notNull=La ricetta è obbligatoria
validation.recipeCookingRequestDTO.details.size=I dettagli non possono superare i 500 caratteri
validation.recipeCookingRequestDTO.quantity.decimalMin=La quantità deve essere maggiore di 0
validation.recipeCookingRequestDTO.quantity.digits=La quantità deve avere al massimo 10 cifre intere e 3 decimali
validation.recipeCookingRequestDTO.quantity.notNull=La quantità da cucinare è obbligatoria
validation.recipeCookingRequestDTO.recipeId.notNull=L'ID della ricetta è obbligatorio
validation.recipeCookingRequestDTO.recipeId.positive=L'ID della ricetta deve essere positivo
validation.recipeRequestDTO.components.notEmpty=La ricetta deve includere almeno un componente
validation.recipeRequestDTO.elaboration.notBlank=L'elaborazione è obbligatoria
validation.recipeRequestDTO.elaboration.size=L'elaborazione non può superare i 2000 caratteri
validation.recipeRequestDTO.name.notBlank=Il nome della ricetta è obbligatorio
validation.recipeRequestDTO.name.size=Deve contenere tra 2 e 150 caratteri
validation.recipeRequestDTO.presentation.notBlank=La presentazione è obbligatoria
validation.recipeRequestDTO.presentation.size=La presentazione non può superare i 1000 caratteri
validation.roleEscalationRequestDTO.durationMinutes.max=La durata massima consentita è di 1440 minuti (24 ore)
validation.roleEscalationRequestDTO.durationMinutes.min=La durata minima deve essere di 1 minuto
validation.roleEscalationRequestDTO.durationMinutes.notNull=La durata in minuti è obbligatoria
validation.stockLedger.currentHash.notBlank=L'hash attuale è obbligatorio
validation.stockLedger.movementType.notNull=Il tipo di movimento è obbligatorio
validation.stockLedger.previousHash.notBlank=L'hash precedente è obbligatorio
validation.stockLedger.product.notNull=Il prodotto è obbligatorio
validation.stockLedger.quantityDelta.notNull=La quantità è obbligatoria
validation.stockLedger.resultingStock.notNull=La giacenza risultante è obbligatoria
validation.stockLedger.sequenceNumber.notNull=Il numero di sequenza è obbligatorio
validation.stockLedger.transactionTimestamp.notNull=Il timestamp è obbligatorio
validation.stockMovementItemDTO.description.size=La descrizione non può superare i 500 caratteri
validation.stockMovementItemDTO.movementType.notNull=Il tipo di movimento è obbligatorio
validation.stockMovementItemDTO.productId.notNull=L'ID del prodotto è obbligatorio
validation.stockMovementItemDTO.quantityDelta.digits=La quantità deve avere al massimo 10 cifre intere e 3 decimali
validation.stockMovementItemDTO.quantityDelta.notNull=La quantità è obbligatoria
validation.stockSnapshot.currentStock.notNull=La giacenza attuale è obbligatoria
validation.stockSnapshot.integrityStatus.notBlank=Lo stato di integrità è obbligatorio
validation.stockSnapshot.lastSequenceNumber.notNull=Il numero di sequenza è obbligatorio
validation.stockSnapshot.lastTransactionHash.notBlank=L'ultimo hash è obbligatorio
validation.stockSnapshot.lastUpdated.notNull=La data di aggiornamento è obbligatoria
validation.supplier.name.notBlank=Il nome del fornitore è obbligatorio
validation.supplier.name.size=Deve contenere tra 2 e 100 caratteri
validation.supplierRequestDTO.name.notBlank=Il nome del fornitore è obbligatorio
validation.supplierRequestDTO.name.size=Deve contenere tra 2 e 100 caratteri
validation.user.name.notBlank=Il nome è obbligatorio
validation.user.name.size=Deve contenere tra 2 e 100 caratteri
validation.user.password.notBlank=La password è obbligatoria
validation.user.role.notNull=Il ruolo è obbligatorio
validation.user.user.notBlank=Il nome utente è obbligatorio
validation.userRequestDTO.name.notBlank=Il nome è obbligatorio
validation.userRequestDTO.name.size=Deve contenere tra 2 e 100 caratteri
validation.userRequestDTO.password.notBlank=La password è obbligatoria
validation.userRequestDTO.password.size=La password deve avere almeno 6 caratteri
validation.userRequestDTO.user.notBlank=Il nome utente è obbligatorio
validation.userRequestDTO.user.size=Il nome utente non può superare i 100 caratteri
""",
}

for lang, content in FILES.items():
    path = os.path.join(VDIR, f"ValidationMessages_{lang}.properties")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content.strip() + "\n")
    lines = [l for l in content.strip().split("\n") if "=" in l]
    print(f"  {lang}: wrote {len(lines)} keys")

# Verify no Spanish remains
for lang in FILES:
    path = os.path.join(VDIR, f"ValidationMessages_{lang}.properties")
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()
    spanish = content.count("obligatorio") + content.count("obligatoria")
    print(f"  {lang}: Spanish 'obligatori*' count = {spanish} (should be 0)")
