#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Writes EU, GL, NL, SV ValidationMessages files."""
import os
VDIR = "src/main/resources/i18n/validation/"
FILES = {
"eu": """validation.allergen.name.notBlank=Alergenoaren izena beharrezkoa da
validation.allergen.name.size=2 eta 50 karaktere artean izan behar du
validation.allergenRequestDTO.name.notBlank=Alergenoaren izena beharrezkoa da
validation.allergenRequestDTO.name.size=2 eta 50 karaktere artean izan behar du
validation.batchStockMovementRequestDTO.movements.notEmpty=Gutxienez mugimendu bat gehitu behar da
validation.batchStockMovementRequestDTO.reason.size=Arrazoia ezin da 1000 karaktere gainditu
validation.changePasswordRequestDTO.newPassword.notBlank=Pasahitz berria beharrezkoa da
validation.changePasswordRequestDTO.newPassword.size=Pasahitz berriak gutxienez 6 karaktere izan behar ditu
validation.inventoryAudit.actionDescription.size=Deskribapena ezin da 500 karaktere gainditu
validation.inventoryAudit.product.notNull=Produktua beharrezkoa da
validation.inventoryAudit.quantity.notNull=Kopurua beharrezkoa da
validation.inventoryAudit.unknown.notBlank=Mugimendu mota beharrezkoa da
validation.inventoryMovementRequestDTO.movementType.notNull=Mugimendu mota beharrezkoa da
validation.inventoryMovementRequestDTO.productId.notNull=Produktuaren IDa beharrezkoa da
validation.inventoryMovementRequestDTO.quantity.decimalMax=Kopurua ezin da 9.999.999,99 gainditu
validation.inventoryMovementRequestDTO.quantity.notNull=Kopurua beharrezkoa da
validation.inventoryMovementRequestDTO.quantity.positive=Kopuruak zero baino handiagoa izan behar du
validation.inventoryMovementRequestDTO.userId.notNull=Erabiltzailearen IDa beharrezkoa da
validation.jwtProperties.expiration.positive=JWT iraungitzea balio positiboa izan behar da
validation.jwtProperties.secret.notBlank=JWT sekretua beharrezkoa da
validation.loginRequestDTO.name.notBlank=Erabiltzaile izena beharrezkoa da
validation.loginRequestDTO.password.notBlank=Pasahitza beharrezkoa da
validation.order.orderDate.notNull=Eskaeraren data beharrezkoa da
validation.order.orderDate.pastOrPresent=Eskaeraren data ezin da etorkizuneko data izan
validation.order.status.notBlank=Egoera beharrezkoa da
validation.order.users.notNull=Erabiltzailea beharrezkoa da
validation.orderAudit.action.notBlank=Ekintza beharrezkoa da
validation.orderAudit.details.size=Xehetasunak ezin dira 1000 karaktere gainditu
validation.orderDetail.order.notNull=Eskaera beharrezkoa da
validation.orderDetail.product.notNull=Produktua beharrezkoa da
validation.orderDetail.quantity.decimalMin=Kopurua 0 baino handiagoa izan behar da
validation.orderDetail.quantity.notNull=Eskatutako kopurua beharrezkoa da
validation.orderDetail.quantityReceived.decimalMin=Jasotako kopurua ezin da negatiboa izan
validation.orderDetailRequestDTO.productId.notNull=Produktuaren IDa beharrezkoa da
validation.orderDetailRequestDTO.quantity.decimalMin=Kopuruak zero baino handiagoa izan behar du
validation.orderDetailRequestDTO.quantity.digits=Kopuruak gehienez 10 oso eta 3 dezimal izan ditzake
validation.orderDetailRequestDTO.quantity.notNull=Kopurua beharrezkoa da
validation.orderReceptionDetailRequestDTO.productId.notNull=Produktuaren IDa beharrezkoa da
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Jasotako kopurua beharrezkoa da
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Jasotako kopuruak zero edo handiagoa izan behar du
validation.orderReceptionRequestDTO.items.notEmpty=Gutxienez jasotako produktu bat zehaztu behar da
validation.orderReceptionRequestDTO.orderId.notNull=Eskaeraren IDa beharrezkoa da
validation.orderReceptionRequestDTO.status.notNull=Egoera zehaztea beharrezkoa da
validation.orderRequestDTO.details.notEmpty=Eskaerak gutxienez xehetasun bat izan behar du
validation.orderRequestDTO.userId.notNull=Erabiltzailearen IDa beharrezkoa da
validation.product.availabilityPercentage.decimalMax=Eskuragarritasun ehunekoak ezin du 100 gainditu
validation.product.availabilityPercentage.decimalMin=Eskuragarritasun ehunekoa ezin da negatiboa izan
validation.product.availabilityPercentage.digits=Eskuragarritasun formatu baliogabea
validation.product.currentStock.decimalMin=Stocka ezin da negatiboa izan
validation.product.currentStock.digits=Stock formatu baliogabea
validation.product.currentStock.notNull=Egungo stocka beharrezkoa da
validation.product.minimumStock.decimalMin=Gutxieneko stocka ezin da negatiboa izan
validation.product.minimumStock.digits=Gutxieneko stock formatu baliogabea
validation.product.name.notBlank=Produktuaren izena beharrezkoa da
validation.product.name.size=2 eta 100 karaktere artean izan behar du
validation.product.productCode.notBlank=Produktuaren kodea beharrezkoa da
validation.product.unit.notBlank=Neurri unitatea beharrezkoa da
validation.product.unitPrice.decimalMin=Prezioak 0 baino handiagoa izan behar du
validation.product.unitPrice.digits=Prezio formatu baliogabea
validation.product.unitPrice.notNull=Prezioa beharrezkoa da
validation.productRequestDTO.availabilityPercentage.decimalMax=Eskuragarritasun ehunekoak ezin du 100 gainditu
validation.productRequestDTO.availabilityPercentage.decimalMin=Eskuragarritasun ehunekoa ezin da negatiboa izan
validation.productRequestDTO.availabilityPercentage.digits=Ehunekoak gehienez 3 oso eta 2 dezimal izan ditzake
validation.productRequestDTO.currentStock.decimalMin=Stocka ezin da negatiboa izan
validation.productRequestDTO.currentStock.digits=Stockak gehienez 10 oso eta 3 dezimal izan ditzake
validation.productRequestDTO.currentStock.notNull=Egungo stocka beharrezkoa da
validation.productRequestDTO.minimumStock.decimalMin=Gutxieneko stocka ezin da negatiboa izan
validation.productRequestDTO.minimumStock.digits=Gutxieneko stockak gehienez 10 oso eta 3 dezimal izan ditzake
validation.productRequestDTO.minimumStock.notNull=Gutxieneko stocka beharrezkoa da
validation.productRequestDTO.name.notBlank=Produktuaren izena beharrezkoa da
validation.productRequestDTO.name.size=2 eta 100 karaktere artean izan behar du
validation.productRequestDTO.productCode.notBlank=Produktuaren kodea beharrezkoa da
validation.productRequestDTO.productCode.size=Kodea ezin da 50 karaktere gainditu
validation.productRequestDTO.unit.notBlank=Neurri unitatea beharrezkoa da
validation.productRequestDTO.unit.size=Unitatea ezin da 20 karaktere gainditu
validation.productRequestDTO.unitPrice.decimalMin=Prezioak zero baino handiagoa izan behar du
validation.productRequestDTO.unitPrice.digits=Prezioak gehienez 10 oso eta 2 dezimal izan ditzake
validation.productRequestDTO.unitPrice.notNull=Prezioa beharrezkoa da
validation.recipe.elaboration.size=Elaborazioa ezin da 2000 karaktere gainditu
validation.recipe.name.notBlank=Errezetaren izena beharrezkoa da
validation.recipe.name.size=2 eta 150 karaktere artean izan behar du
validation.recipe.presentation.size=Aurkezpena ezin da 1000 karaktere gainditu
validation.recipe.totalCost.decimalMin=Kostua ezin da negatiboa izan
validation.recipeAudit.action.notBlank=Ekintza beharrezkoa da
validation.recipeAudit.details.size=Xehetasunak ezin dira 1000 karaktere gainditu
validation.recipeComponent.parentRecipe.notNull=Errezeta beharrezkoa da
validation.recipeComponent.product.notNull=Produktua beharrezkoa da
validation.recipeComponent.quantity.decimalMin=Kopurua 0 baino handiagoa izan behar da
validation.recipeComponent.quantity.notNull=Kopurua beharrezkoa da
validation.recipeComponentRequestDTO.productId.notNull=Produktuaren IDa beharrezkoa da
validation.recipeComponentRequestDTO.quantity.decimalMin=Kopuruak zero baino handiagoa izan behar du
validation.recipeComponentRequestDTO.quantity.digits=Kopuruak gehienez 10 oso eta 3 dezimal izan ditzake
validation.recipeComponentRequestDTO.quantity.notNull=Kopurua beharrezkoa da
validation.recipeCookingAudit.details.size=Xehetasunak ezin dira 1000 karaktere gainditu
validation.recipeCookingAudit.quantityCooked.decimalMin=Kopurua 0 baino handiagoa izan behar da
validation.recipeCookingAudit.quantityCooked.notNull=Prestatutako kopurua beharrezkoa da
validation.recipeCookingAudit.recipe.notNull=Errezeta beharrezkoa da
validation.recipeCookingRequestDTO.details.size=Xehetasunak ezin dira 500 karaktere gainditu
validation.recipeCookingRequestDTO.quantity.decimalMin=Kopurua 0 baino handiagoa izan behar da
validation.recipeCookingRequestDTO.quantity.digits=Kopuruak gehienez 10 oso eta 3 dezimal izan ditzake
validation.recipeCookingRequestDTO.quantity.notNull=Prestatzeko kopurua beharrezkoa da
validation.recipeCookingRequestDTO.recipeId.notNull=Errezetaren IDa beharrezkoa da
validation.recipeCookingRequestDTO.recipeId.positive=Errezetaren IDa positiboa izan behar da
validation.recipeRequestDTO.components.notEmpty=Errezetak gutxienez osagai bat izan behar du
validation.recipeRequestDTO.elaboration.notBlank=Elaborazioa beharrezkoa da
validation.recipeRequestDTO.elaboration.size=Elaborazioa ezin da 2000 karaktere gainditu
validation.recipeRequestDTO.name.notBlank=Errezetaren izena beharrezkoa da
validation.recipeRequestDTO.name.size=2 eta 150 karaktere artean izan behar du
validation.recipeRequestDTO.presentation.notBlank=Aurkezpena beharrezkoa da
validation.recipeRequestDTO.presentation.size=Aurkezpena ezin da 1000 karaktere gainditu
validation.roleEscalationRequestDTO.durationMinutes.max=Baimendutako gehienezko iraupena 1440 minutukoa da (24 ordu)
validation.roleEscalationRequestDTO.durationMinutes.min=Gutxieneko iraupena minutu 1 izan behar da
validation.roleEscalationRequestDTO.durationMinutes.notNull=Minituen iraupena beharrezkoa da
validation.stockLedger.currentHash.notBlank=Egungo hasha beharrezkoa da
validation.stockLedger.movementType.notNull=Mugimendu mota beharrezkoa da
validation.stockLedger.previousHash.notBlank=Aurreko hasha beharrezkoa da
validation.stockLedger.product.notNull=Produktua beharrezkoa da
validation.stockLedger.quantityDelta.notNull=Kopurua beharrezkoa da
validation.stockLedger.resultingStock.notNull=Emaitzazko stocka beharrezkoa da
validation.stockLedger.sequenceNumber.notNull=Sekuentzia zenbakia beharrezkoa da
validation.stockLedger.transactionTimestamp.notNull=Denbora-marka beharrezkoa da
validation.stockMovementItemDTO.description.size=Deskribapena ezin da 500 karaktere gainditu
validation.stockMovementItemDTO.movementType.notNull=Mugimendu mota beharrezkoa da
validation.stockMovementItemDTO.productId.notNull=Produktuaren IDa beharrezkoa da
validation.stockMovementItemDTO.quantityDelta.digits=Kopuruak gehienez 10 oso eta 3 dezimal izan ditzake
validation.stockMovementItemDTO.quantityDelta.notNull=Kopurua beharrezkoa da
validation.stockSnapshot.currentStock.notNull=Egungo stocka beharrezkoa da
validation.stockSnapshot.integrityStatus.notBlank=Osotasun egoera beharrezkoa da
validation.stockSnapshot.lastSequenceNumber.notNull=Sekuentzia zenbakia beharrezkoa da
validation.stockSnapshot.lastTransactionHash.notBlank=Azken hasha beharrezkoa da
validation.stockSnapshot.lastUpdated.notNull=Eguneratze data beharrezkoa da
validation.supplier.name.notBlank=Hornitzailearen izena beharrezkoa da
validation.supplier.name.size=2 eta 100 karaktere artean izan behar du
validation.supplierRequestDTO.name.notBlank=Hornitzailearen izena beharrezkoa da
validation.supplierRequestDTO.name.size=2 eta 100 karaktere artean izan behar du
validation.user.name.notBlank=Izena beharrezkoa da
validation.user.name.size=2 eta 100 karaktere artean izan behar du
validation.user.password.notBlank=Pasahitza beharrezkoa da
validation.user.role.notNull=Rola beharrezkoa da
validation.user.user.notBlank=Erabiltzailea beharrezkoa da
validation.userRequestDTO.name.notBlank=Izena beharrezkoa da
validation.userRequestDTO.name.size=2 eta 100 karaktere artean izan behar du
validation.userRequestDTO.password.notBlank=Pasahitza beharrezkoa da
validation.userRequestDTO.password.size=Pasahitzak gutxienez 6 karaktere izan behar ditu
validation.userRequestDTO.user.notBlank=Erabiltzailea beharrezkoa da
validation.userRequestDTO.user.size=Erabiltzailea ezin da 100 karaktere gainditu
""",

"gl": """validation.allergen.name.notBlank=O nome do alérxeno é obrigatorio
validation.allergen.name.size=Debe ter entre 2 e 50 caracteres
validation.allergenRequestDTO.name.notBlank=O nome do alérxeno é obrigatorio
validation.allergenRequestDTO.name.size=Debe ter entre 2 e 50 caracteres
validation.batchStockMovementRequestDTO.movements.notEmpty=Debe incluír polo menos un movemento
validation.batchStockMovementRequestDTO.reason.size=A razón non pode exceder 1000 caracteres
validation.changePasswordRequestDTO.newPassword.notBlank=O novo contrasinal é obrigatorio
validation.changePasswordRequestDTO.newPassword.size=O novo contrasinal debe ter polo menos 6 caracteres
validation.inventoryAudit.actionDescription.size=A descrición non pode exceder 500 caracteres
validation.inventoryAudit.product.notNull=O produto é obrigatorio
validation.inventoryAudit.quantity.notNull=A cantidade é obrigatoria
validation.inventoryAudit.unknown.notBlank=O tipo de movemento é obrigatorio
validation.inventoryMovementRequestDTO.movementType.notNull=O tipo de movemento é obrigatorio
validation.inventoryMovementRequestDTO.productId.notNull=O ID do produto é obrigatorio
validation.inventoryMovementRequestDTO.quantity.decimalMax=A cantidade non pode ser maior a 9.999.999,99
validation.inventoryMovementRequestDTO.quantity.notNull=A cantidade é obrigatoria
validation.inventoryMovementRequestDTO.quantity.positive=A cantidade debe ser maior que cero
validation.inventoryMovementRequestDTO.userId.notNull=O ID do usuario é obrigatorio
validation.jwtProperties.expiration.positive=A expiración JWT debe ser un valor positivo
validation.jwtProperties.secret.notBlank=O segredo JWT é obrigatorio
validation.loginRequestDTO.name.notBlank=O nome de usuario é obrigatorio
validation.loginRequestDTO.password.notBlank=O contrasinal é obrigatorio
validation.order.orderDate.notNull=A data do pedido é obrigatoria
validation.order.orderDate.pastOrPresent=A data do pedido non pode ser futura
validation.order.status.notBlank=O estado é obrigatorio
validation.order.users.notNull=O usuario é obrigatorio
validation.orderAudit.action.notBlank=A acción é obrigatoria
validation.orderAudit.details.size=Os detalles non poden exceder 1000 caracteres
validation.orderDetail.order.notNull=O pedido é obrigatorio
validation.orderDetail.product.notNull=O produto é obrigatorio
validation.orderDetail.quantity.decimalMin=A cantidade debe ser maior a 0
validation.orderDetail.quantity.notNull=A cantidade solicitada é obrigatoria
validation.orderDetail.quantityReceived.decimalMin=A cantidade recibida non pode ser negativa
validation.orderDetailRequestDTO.productId.notNull=O ID do produto é obrigatorio
validation.orderDetailRequestDTO.quantity.decimalMin=A cantidade debe ser maior que cero
validation.orderDetailRequestDTO.quantity.digits=A cantidade debe ter un máximo de 10 díxitos enteiros e 3 decimais
validation.orderDetailRequestDTO.quantity.notNull=A cantidade é obrigatoria
validation.orderReceptionDetailRequestDTO.productId.notNull=O ID do produto é obrigatorio
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=A cantidade recibida é obrigatoria
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=A cantidade recibida debe ser maior ou igual a cero
validation.orderReceptionRequestDTO.items.notEmpty=Debe especificar polo menos un produto recibido
validation.orderReceptionRequestDTO.orderId.notNull=O ID do pedido é obrigatorio
validation.orderReceptionRequestDTO.status.notNull=O estado é obrigatorio
validation.orderRequestDTO.details.notEmpty=O pedido debe ter polo menos un detalle
validation.orderRequestDTO.userId.notNull=O ID do usuario é obrigatorio
validation.product.availabilityPercentage.decimalMax=A porcentaxe de dispoñibilidade non pode ser maior a 100
validation.product.availabilityPercentage.decimalMin=A porcentaxe de dispoñibilidade non pode ser negativa
validation.product.availabilityPercentage.digits=Formato de dispoñibilidade inválido
validation.product.currentStock.decimalMin=O stock non pode ser negativo
validation.product.currentStock.digits=Formato de stock inválido
validation.product.currentStock.notNull=O stock actual é obrigatorio
validation.product.minimumStock.decimalMin=O stock mínimo non pode ser negativo
validation.product.minimumStock.digits=Formato de stock mínimo inválido
validation.product.name.notBlank=O nome do produto é obrigatorio
validation.product.name.size=Debe ter entre 2 e 100 caracteres
validation.product.productCode.notBlank=O código do produto é obrigatorio
validation.product.unit.notBlank=A unidade de medida é obrigatoria
validation.product.unitPrice.decimalMin=O prezo debe ser maior a 0
validation.product.unitPrice.digits=Formato de prezo inválido
validation.product.unitPrice.notNull=O prezo unitario é obrigatorio
validation.productRequestDTO.availabilityPercentage.decimalMax=A porcentaxe de dispoñibilidade non pode ser maior a 100
validation.productRequestDTO.availabilityPercentage.decimalMin=A porcentaxe de dispoñibilidade non pode ser negativa
validation.productRequestDTO.availabilityPercentage.digits=A porcentaxe debe ter un máximo de 3 díxitos enteiros e 2 decimais
validation.productRequestDTO.currentStock.decimalMin=O stock non pode ser negativo
validation.productRequestDTO.currentStock.digits=O stock debe ter un máximo de 10 díxitos enteiros e 3 decimais
validation.productRequestDTO.currentStock.notNull=O stock actual é obrigatorio
validation.productRequestDTO.minimumStock.decimalMin=O stock mínimo non pode ser negativo
validation.productRequestDTO.minimumStock.digits=O stock mínimo debe ter un máximo de 10 díxitos enteiros e 3 decimais
validation.productRequestDTO.minimumStock.notNull=O stock mínimo é obrigatorio
validation.productRequestDTO.name.notBlank=O nome do produto é obrigatorio
validation.productRequestDTO.name.size=Debe ter entre 2 e 100 caracteres
validation.productRequestDTO.productCode.notBlank=O código do produto é obrigatorio
validation.productRequestDTO.productCode.size=O código non pode exceder 50 caracteres
validation.productRequestDTO.unit.notBlank=A unidade de medida é obrigatoria
validation.productRequestDTO.unit.size=A unidade non pode exceder 20 caracteres
validation.productRequestDTO.unitPrice.decimalMin=O prezo debe ser maior que cero
validation.productRequestDTO.unitPrice.digits=O prezo debe ter un máximo de 10 díxitos enteiros e 2 decimais
validation.productRequestDTO.unitPrice.notNull=O prezo unitario é obrigatorio
validation.recipe.elaboration.size=A elaboración non pode exceder 2000 caracteres
validation.recipe.name.notBlank=O nome da receita é obrigatorio
validation.recipe.name.size=Debe ter entre 2 e 150 caracteres
validation.recipe.presentation.size=A presentación non pode exceder 1000 caracteres
validation.recipe.totalCost.decimalMin=O custo non pode ser negativo
validation.recipeAudit.action.notBlank=A acción é obrigatoria
validation.recipeAudit.details.size=Os detalles non poden exceder 1000 caracteres
validation.recipeComponent.parentRecipe.notNull=A receita é obrigatoria
validation.recipeComponent.product.notNull=O produto é obrigatorio
validation.recipeComponent.quantity.decimalMin=A cantidade debe ser maior a 0
validation.recipeComponent.quantity.notNull=A cantidade é obrigatoria
validation.recipeComponentRequestDTO.productId.notNull=O ID do produto é obrigatorio
validation.recipeComponentRequestDTO.quantity.decimalMin=A cantidade debe ser maior que cero
validation.recipeComponentRequestDTO.quantity.digits=A cantidade debe ter un máximo de 10 díxitos enteiros e 3 decimais
validation.recipeComponentRequestDTO.quantity.notNull=A cantidade é obrigatoria
validation.recipeCookingAudit.details.size=Os detalles non poden exceder 1000 caracteres
validation.recipeCookingAudit.quantityCooked.decimalMin=A cantidade debe ser maior a 0
validation.recipeCookingAudit.quantityCooked.notNull=A cantidade cociñada é obrigatoria
validation.recipeCookingAudit.recipe.notNull=A receita é obrigatoria
validation.recipeCookingRequestDTO.details.size=Os detalles non poden exceder 500 caracteres
validation.recipeCookingRequestDTO.quantity.decimalMin=A cantidade debe ser maior a 0
validation.recipeCookingRequestDTO.quantity.digits=A cantidade debe ter un máximo de 10 enteiros e 3 decimais
validation.recipeCookingRequestDTO.quantity.notNull=A cantidade a cociñar é obrigatoria
validation.recipeCookingRequestDTO.recipeId.notNull=O ID da receita é obrigatorio
validation.recipeCookingRequestDTO.recipeId.positive=O ID da receita debe ser positivo
validation.recipeRequestDTO.components.notEmpty=A receita debe incluír polo menos un compoñente
validation.recipeRequestDTO.elaboration.notBlank=A elaboración é obrigatoria
validation.recipeRequestDTO.elaboration.size=A elaboración non pode exceder 2000 caracteres
validation.recipeRequestDTO.name.notBlank=O nome da receita é obrigatorio
validation.recipeRequestDTO.name.size=Debe ter entre 2 e 150 caracteres
validation.recipeRequestDTO.presentation.notBlank=A presentación é obrigatoria
validation.recipeRequestDTO.presentation.size=A presentación non pode exceder 1000 caracteres
validation.roleEscalationRequestDTO.durationMinutes.max=A duración máxima permitida é de 1440 minutos (24 horas)
validation.roleEscalationRequestDTO.durationMinutes.min=A duración mínima debe ser de 1 minuto
validation.roleEscalationRequestDTO.durationMinutes.notNull=A duración en minutos é obrigatoria
validation.stockLedger.currentHash.notBlank=O hash actual é obrigatorio
validation.stockLedger.movementType.notNull=O tipo de movemento é obrigatorio
validation.stockLedger.previousHash.notBlank=O hash previo é obrigatorio
validation.stockLedger.product.notNull=O produto é obrigatorio
validation.stockLedger.quantityDelta.notNull=A cantidade é obrigatoria
validation.stockLedger.resultingStock.notNull=O stock resultante é obrigatorio
validation.stockLedger.sequenceNumber.notNull=O número de secuencia é obrigatorio
validation.stockLedger.transactionTimestamp.notNull=O timestamp é obrigatorio
validation.stockMovementItemDTO.description.size=A descrición non pode exceder 500 caracteres
validation.stockMovementItemDTO.movementType.notNull=O tipo de movemento é obrigatorio
validation.stockMovementItemDTO.productId.notNull=O ID do produto é obrigatorio
validation.stockMovementItemDTO.quantityDelta.digits=A cantidade debe ter un máximo de 10 díxitos enteiros e 3 decimais
validation.stockMovementItemDTO.quantityDelta.notNull=A cantidade é obrigatoria
validation.stockSnapshot.currentStock.notNull=O stock actual é obrigatorio
validation.stockSnapshot.integrityStatus.notBlank=O estado de integridade é obrigatorio
validation.stockSnapshot.lastSequenceNumber.notNull=O número de secuencia é obrigatorio
validation.stockSnapshot.lastTransactionHash.notBlank=O último hash é obrigatorio
validation.stockSnapshot.lastUpdated.notNull=A data de actualización é obrigatoria
validation.supplier.name.notBlank=O nome do provedor é obrigatorio
validation.supplier.name.size=Debe ter entre 2 e 100 caracteres
validation.supplierRequestDTO.name.notBlank=O nome do provedor é obrigatorio
validation.supplierRequestDTO.name.size=Debe ter entre 2 e 100 caracteres
validation.user.name.notBlank=O nome é obrigatorio
validation.user.name.size=Debe ter entre 2 e 100 caracteres
validation.user.password.notBlank=O contrasinal é obrigatorio
validation.user.role.notNull=O rol é obrigatorio
validation.user.user.notBlank=O usuario é obrigatorio
validation.userRequestDTO.name.notBlank=O nome é obrigatorio
validation.userRequestDTO.name.size=Debe ter entre 2 e 100 caracteres
validation.userRequestDTO.password.notBlank=O contrasinal é obrigatorio
validation.userRequestDTO.password.size=O contrasinal debe ter polo menos 6 caracteres
validation.userRequestDTO.user.notBlank=O usuario é obrigatorio
validation.userRequestDTO.user.size=O usuario non pode exceder 100 caracteres
""",

"nl": """validation.allergen.name.notBlank=De allergeennaam is verplicht
validation.allergen.name.size=Moet tussen 2 en 50 tekens bevatten
validation.allergenRequestDTO.name.notBlank=De allergeennaam is verplicht
validation.allergenRequestDTO.name.size=Moet tussen 2 en 50 tekens bevatten
validation.batchStockMovementRequestDTO.movements.notEmpty=Er moet minstens één beweging worden opgenomen
validation.batchStockMovementRequestDTO.reason.size=De reden mag niet meer dan 1000 tekens bevatten
validation.changePasswordRequestDTO.newPassword.notBlank=Het nieuwe wachtwoord is verplicht
validation.changePasswordRequestDTO.newPassword.size=Het nieuwe wachtwoord moet minstens 6 tekens bevatten
validation.inventoryAudit.actionDescription.size=De beschrijving mag niet meer dan 500 tekens bevatten
validation.inventoryAudit.product.notNull=Het product is verplicht
validation.inventoryAudit.quantity.notNull=De hoeveelheid is verplicht
validation.inventoryAudit.unknown.notBlank=Het type beweging is verplicht
validation.inventoryMovementRequestDTO.movementType.notNull=Het type beweging is verplicht
validation.inventoryMovementRequestDTO.productId.notNull=Het product-ID is verplicht
validation.inventoryMovementRequestDTO.quantity.decimalMax=De hoeveelheid mag 9.999.999,99 niet overschrijden
validation.inventoryMovementRequestDTO.quantity.notNull=De hoeveelheid is verplicht
validation.inventoryMovementRequestDTO.quantity.positive=De hoeveelheid moet groter zijn dan nul
validation.inventoryMovementRequestDTO.userId.notNull=Het gebruikers-ID is verplicht
validation.jwtProperties.expiration.positive=JWT-verloop moet een positieve waarde zijn
validation.jwtProperties.secret.notBlank=Het JWT-geheim is verplicht
validation.loginRequestDTO.name.notBlank=De gebruikersnaam is verplicht
validation.loginRequestDTO.password.notBlank=Het wachtwoord is verplicht
validation.order.orderDate.notNull=De besteldatum is verplicht
validation.order.orderDate.pastOrPresent=De besteldatum mag niet in de toekomst liggen
validation.order.status.notBlank=De status is verplicht
validation.order.users.notNull=De gebruiker is verplicht
validation.orderAudit.action.notBlank=De actie is verplicht
validation.orderAudit.details.size=Details mogen niet meer dan 1000 tekens bevatten
validation.orderDetail.order.notNull=De bestelling is verplicht
validation.orderDetail.product.notNull=Het product is verplicht
validation.orderDetail.quantity.decimalMin=De hoeveelheid moet groter zijn dan 0
validation.orderDetail.quantity.notNull=De gevraagde hoeveelheid is verplicht
validation.orderDetail.quantityReceived.decimalMin=De ontvangen hoeveelheid mag niet negatief zijn
validation.orderDetailRequestDTO.productId.notNull=Het product-ID is verplicht
validation.orderDetailRequestDTO.quantity.decimalMin=De hoeveelheid moet groter zijn dan nul
validation.orderDetailRequestDTO.quantity.digits=De hoeveelheid mag maximaal 10 gehele getallen en 3 decimalen hebben
validation.orderDetailRequestDTO.quantity.notNull=De hoeveelheid is verplicht
validation.orderReceptionDetailRequestDTO.productId.notNull=Het product-ID is verplicht
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=De ontvangen hoeveelheid is verplicht
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=De ontvangen hoeveelheid moet gelijk zijn aan of groter zijn dan nul
validation.orderReceptionRequestDTO.items.notEmpty=Er moet minstens één ontvangen product worden gespecificeerd
validation.orderReceptionRequestDTO.orderId.notNull=Het bestel-ID is verplicht
validation.orderReceptionRequestDTO.status.notNull=De status is verplicht
validation.orderRequestDTO.details.notEmpty=De bestelling moet minstens één detail bevatten
validation.orderRequestDTO.userId.notNull=Het gebruikers-ID is verplicht
validation.product.availabilityPercentage.decimalMax=Het beschikbaarheidspercentage mag de 100 niet overschrijden
validation.product.availabilityPercentage.decimalMin=Het beschikbaarheidspercentage mag niet negatief zijn
validation.product.availabilityPercentage.digits=Ongeldig beschikbaarheidsformaat
validation.product.currentStock.decimalMin=De voorraad mag niet negatief zijn
validation.product.currentStock.digits=Ongeldig voorraadformaat
validation.product.currentStock.notNull=De huidige voorraad is verplicht
validation.product.minimumStock.decimalMin=De minimale voorraad mag niet negatief zijn
validation.product.minimumStock.digits=Ongeldig formaat minimale voorraad
validation.product.name.notBlank=De productnaam is verplicht
validation.product.name.size=Moet tussen 2 en 100 tekens bevatten
validation.product.productCode.notBlank=De productcode is verplicht
validation.product.unit.notBlank=De meeteenheid is verplicht
validation.product.unitPrice.decimalMin=De prijs moet groter zijn dan 0
validation.product.unitPrice.digits=Ongeldig prijsformaat
validation.product.unitPrice.notNull=De eenheidsprijs is verplicht
validation.productRequestDTO.availabilityPercentage.decimalMax=Het beschikbaarheidspercentage mag de 100 niet overschrijden
validation.productRequestDTO.availabilityPercentage.decimalMin=Het beschikbaarheidspercentage mag niet negatief zijn
validation.productRequestDTO.availabilityPercentage.digits=Het percentage mag maximaal 3 gehele getallen en 2 decimalen hebben
validation.productRequestDTO.currentStock.decimalMin=De voorraad mag niet negatief zijn
validation.productRequestDTO.currentStock.digits=De voorraad mag maximaal 10 gehele getallen en 3 decimalen hebben
validation.productRequestDTO.currentStock.notNull=De huidige voorraad is verplicht
validation.productRequestDTO.minimumStock.decimalMin=De minimale voorraad mag niet negatief zijn
validation.productRequestDTO.minimumStock.digits=De minimale voorraad mag maximaal 10 gehele getallen en 3 decimalen hebben
validation.productRequestDTO.minimumStock.notNull=De minimale voorraad is verplicht
validation.productRequestDTO.name.notBlank=De productnaam is verplicht
validation.productRequestDTO.name.size=Moet tussen 2 en 100 tekens bevatten
validation.productRequestDTO.productCode.notBlank=De productcode is verplicht
validation.productRequestDTO.productCode.size=De code mag niet meer dan 50 tekens bevatten
validation.productRequestDTO.unit.notBlank=De meeteenheid is verplicht
validation.productRequestDTO.unit.size=De eenheid mag niet meer dan 20 tekens bevatten
validation.productRequestDTO.unitPrice.decimalMin=De prijs moet groter zijn dan nul
validation.productRequestDTO.unitPrice.digits=De prijs mag maximaal 10 gehele getallen en 2 decimalen hebben
validation.productRequestDTO.unitPrice.notNull=De eenheidsprijs is verplicht
validation.recipe.elaboration.size=De voorbereiding mag niet meer dan 2000 tekens bevatten
validation.recipe.name.notBlank=De receptnaam is verplicht
validation.recipe.name.size=Moet tussen 2 en 150 tekens bevatten
validation.recipe.presentation.size=De presentatie mag niet meer dan 1000 tekens bevatten
validation.recipe.totalCost.decimalMin=De kosten mogen niet negatief zijn
validation.recipeAudit.action.notBlank=De actie is verplicht
validation.recipeAudit.details.size=Details mogen niet meer dan 1000 tekens bevatten
validation.recipeComponent.parentRecipe.notNull=Het recept is verplicht
validation.recipeComponent.product.notNull=Het product is verplicht
validation.recipeComponent.quantity.decimalMin=De hoeveelheid moet groter zijn dan 0
validation.recipeComponent.quantity.notNull=De hoeveelheid is verplicht
validation.recipeComponentRequestDTO.productId.notNull=Het product-ID is verplicht
validation.recipeComponentRequestDTO.quantity.decimalMin=De hoeveelheid moet groter zijn dan nul
validation.recipeComponentRequestDTO.quantity.digits=De hoeveelheid mag maximaal 10 gehele getallen en 3 decimalen hebben
validation.recipeComponentRequestDTO.quantity.notNull=De hoeveelheid is verplicht
validation.recipeCookingAudit.details.size=Details mogen niet meer dan 1000 tekens bevatten
validation.recipeCookingAudit.quantityCooked.decimalMin=De hoeveelheid moet groter zijn dan 0
validation.recipeCookingAudit.quantityCooked.notNull=De gekookte hoeveelheid is verplicht
validation.recipeCookingAudit.recipe.notNull=Het recept is verplicht
validation.recipeCookingRequestDTO.details.size=Details mogen niet meer dan 500 tekens bevatten
validation.recipeCookingRequestDTO.quantity.decimalMin=De hoeveelheid moet groter zijn dan 0
validation.recipeCookingRequestDTO.quantity.digits=De hoeveelheid mag maximaal 10 gehele getallen en 3 decimalen hebben
validation.recipeCookingRequestDTO.quantity.notNull=De te koken hoeveelheid is verplicht
validation.recipeCookingRequestDTO.recipeId.notNull=Het recept-ID is verplicht
validation.recipeCookingRequestDTO.recipeId.positive=Het recept-ID moet positief zijn
validation.recipeRequestDTO.components.notEmpty=Het recept moet minstens één component bevatten
validation.recipeRequestDTO.elaboration.notBlank=De voorbereiding is verplicht
validation.recipeRequestDTO.elaboration.size=De voorbereiding mag niet meer dan 2000 tekens bevatten
validation.recipeRequestDTO.name.notBlank=De receptnaam is verplicht
validation.recipeRequestDTO.name.size=Moet tussen 2 en 150 tekens bevatten
validation.recipeRequestDTO.presentation.notBlank=De presentatie is verplicht
validation.recipeRequestDTO.presentation.size=De presentatie mag niet meer dan 1000 tekens bevatten
validation.roleEscalationRequestDTO.durationMinutes.max=Maximaal toegestane duur is 1440 minuten (24 uur)
validation.roleEscalationRequestDTO.durationMinutes.min=De minimale duur moet 1 minuut zijn
validation.roleEscalationRequestDTO.durationMinutes.notNull=De duur in minuten is verplicht
validation.stockLedger.currentHash.notBlank=De huidige hash is verplicht
validation.stockLedger.movementType.notNull=Het type beweging is verplicht
validation.stockLedger.previousHash.notBlank=De vorige hash is verplicht
validation.stockLedger.product.notNull=Het product is verplicht
validation.stockLedger.quantityDelta.notNull=De hoeveelheid is verplicht
validation.stockLedger.resultingStock.notNull=De resulterende voorraad is verplicht
validation.stockLedger.sequenceNumber.notNull=Het volgnummer is verplicht
validation.stockLedger.transactionTimestamp.notNull=De tijdstempel is verplicht
validation.stockMovementItemDTO.description.size=De beschrijving mag niet meer dan 500 tekens bevatten
validation.stockMovementItemDTO.movementType.notNull=Het type beweging is verplicht
validation.stockMovementItemDTO.productId.notNull=Het product-ID is verplicht
validation.stockMovementItemDTO.quantityDelta.digits=De hoeveelheid mag maximaal 10 gehele getallen en 3 decimalen hebben
validation.stockMovementItemDTO.quantityDelta.notNull=De hoeveelheid is verplicht
validation.stockSnapshot.currentStock.notNull=De huidige voorraad is verplicht
validation.stockSnapshot.integrityStatus.notBlank=De integriteitsstatus is verplicht
validation.stockSnapshot.lastSequenceNumber.notNull=Het volgnummer is verplicht
validation.stockSnapshot.lastTransactionHash.notBlank=De laatste hash is verplicht
validation.stockSnapshot.lastUpdated.notNull=De updatingsdatum is verplicht
validation.supplier.name.notBlank=De leveranciersnaam is verplicht
validation.supplier.name.size=Moet tussen 2 en 100 tekens bevatten
validation.supplierRequestDTO.name.notBlank=De leveranciersnaam is verplicht
validation.supplierRequestDTO.name.size=Moet tussen 2 en 100 tekens bevatten
validation.user.name.notBlank=De naam is verplicht
validation.user.name.size=Moet tussen 2 en 100 tekens bevatten
validation.user.password.notBlank=Het wachtwoord is verplicht
validation.user.role.notNull=De rol is verplicht
validation.user.user.notBlank=De gebruikersnaam is verplicht
validation.userRequestDTO.name.notBlank=De naam is verplicht
validation.userRequestDTO.name.size=Moet tussen 2 en 100 tekens bevatten
validation.userRequestDTO.password.notBlank=Het wachtwoord is verplicht
validation.userRequestDTO.password.size=Het wachtwoord moet minstens 6 tekens bevatten
validation.userRequestDTO.user.notBlank=De gebruikersnaam is verplicht
validation.userRequestDTO.user.size=De gebruikersnaam mag niet meer dan 100 tekens bevatten
""",

"sv": """validation.allergen.name.notBlank=Allergennamnet krävs
validation.allergen.name.size=Måste vara mellan 2 och 50 tecken
validation.allergenRequestDTO.name.notBlank=Allergennamnet krävs
validation.allergenRequestDTO.name.size=Måste vara mellan 2 och 50 tecken
validation.batchStockMovementRequestDTO.movements.notEmpty=Minst en rörelse måste inkluderas
validation.batchStockMovementRequestDTO.reason.size=Anledningen får inte överstiga 1000 tecken
validation.changePasswordRequestDTO.newPassword.notBlank=Det nya lösenordet krävs
validation.changePasswordRequestDTO.newPassword.size=Det nya lösenordet måste vara minst 6 tecken
validation.inventoryAudit.actionDescription.size=Beskrivningen får inte överstiga 500 tecken
validation.inventoryAudit.product.notNull=Produkten krävs
validation.inventoryAudit.quantity.notNull=Kvantiteten krävs
validation.inventoryAudit.unknown.notBlank=Rörelsetypen krävs
validation.inventoryMovementRequestDTO.movementType.notNull=Rörelsetypen krävs
validation.inventoryMovementRequestDTO.productId.notNull=Produkt-ID krävs
validation.inventoryMovementRequestDTO.quantity.decimalMax=Kvantiteten får inte överstiga 9.999.999,99
validation.inventoryMovementRequestDTO.quantity.notNull=Kvantiteten krävs
validation.inventoryMovementRequestDTO.quantity.positive=Kvantiteten måste vara större än noll
validation.inventoryMovementRequestDTO.userId.notNull=Användar-ID krävs
validation.jwtProperties.expiration.positive=JWT-utgång måste vara ett positivt värde
validation.jwtProperties.secret.notBlank=JWT-hemligheten krävs
validation.loginRequestDTO.name.notBlank=Användarnamnet krävs
validation.loginRequestDTO.password.notBlank=Lösenordet krävs
validation.order.orderDate.notNull=Beställningsdatumet krävs
validation.order.orderDate.pastOrPresent=Beställningsdatumet får inte vara i framtiden
validation.order.status.notBlank=Statusen krävs
validation.order.users.notNull=Användaren krävs
validation.orderAudit.action.notBlank=Åtgärden krävs
validation.orderAudit.details.size=Detaljerna får inte överstiga 1000 tecken
validation.orderDetail.order.notNull=Beställningen krävs
validation.orderDetail.product.notNull=Produkten krävs
validation.orderDetail.quantity.decimalMin=Kvantiteten måste vara större än 0
validation.orderDetail.quantity.notNull=Den begärda kvantiteten krävs
validation.orderDetail.quantityReceived.decimalMin=Den mottagna kvantiteten får inte vara negativ
validation.orderDetailRequestDTO.productId.notNull=Produkt-ID krävs
validation.orderDetailRequestDTO.quantity.decimalMin=Kvantiteten måste vara större än noll
validation.orderDetailRequestDTO.quantity.digits=Kvantiteten får ha maximalt 10 heltal och 3 decimaler
validation.orderDetailRequestDTO.quantity.notNull=Kvantiteten krävs
validation.orderReceptionDetailRequestDTO.productId.notNull=Produkt-ID krävs
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Den mottagna kvantiteten krävs
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Den mottagna kvantiteten måste vara noll eller större
validation.orderReceptionRequestDTO.items.notEmpty=Minst en mottagen produkt måste anges
validation.orderReceptionRequestDTO.orderId.notNull=Order-ID krävs
validation.orderReceptionRequestDTO.status.notNull=Statusen krävs
validation.orderRequestDTO.details.notEmpty=Beställningen måste ha minst en detalj
validation.orderRequestDTO.userId.notNull=Användar-ID krävs
validation.product.availabilityPercentage.decimalMax=Tillgänglighetsprocenten får inte överstiga 100
validation.product.availabilityPercentage.decimalMin=Tillgänglighetsprocenten får inte vara negativ
validation.product.availabilityPercentage.digits=Ogiltigt tillgänglighetsformat
validation.product.currentStock.decimalMin=Lagret får inte vara negativt
validation.product.currentStock.digits=Ogiltigt lagerformat
validation.product.currentStock.notNull=Det aktuella lagret krävs
validation.product.minimumStock.decimalMin=Minimilagret får inte vara negativt
validation.product.minimumStock.digits=Ogiltigt minimilagerformat
validation.product.name.notBlank=Produktnamnet krävs
validation.product.name.size=Måste vara mellan 2 och 100 tecken
validation.product.productCode.notBlank=Produktkoden krävs
validation.product.unit.notBlank=Måttenheten krävs
validation.product.unitPrice.decimalMin=Priset måste vara större än 0
validation.product.unitPrice.digits=Ogiltigt prisformat
validation.product.unitPrice.notNull=Enhetspriset krävs
validation.productRequestDTO.availabilityPercentage.decimalMax=Tillgänglighetsprocenten får inte överstiga 100
validation.productRequestDTO.availabilityPercentage.decimalMin=Tillgänglighetsprocenten får inte vara negativ
validation.productRequestDTO.availabilityPercentage.digits=Procenten får ha maximalt 3 heltal och 2 decimaler
validation.productRequestDTO.currentStock.decimalMin=Lagret får inte vara negativt
validation.productRequestDTO.currentStock.digits=Lagret får ha maximalt 10 heltal och 3 decimaler
validation.productRequestDTO.currentStock.notNull=Det aktuella lagret krävs
validation.productRequestDTO.minimumStock.decimalMin=Minimilagret får inte vara negativt
validation.productRequestDTO.minimumStock.digits=Minimilagret får ha maximalt 10 heltal och 3 decimaler
validation.productRequestDTO.minimumStock.notNull=Minimilagret krävs
validation.productRequestDTO.name.notBlank=Produktnamnet krävs
validation.productRequestDTO.name.size=Måste vara mellan 2 och 100 tecken
validation.productRequestDTO.productCode.notBlank=Produktkoden krävs
validation.productRequestDTO.productCode.size=Koden får inte överstiga 50 tecken
validation.productRequestDTO.unit.notBlank=Måttenheten krävs
validation.productRequestDTO.unit.size=Enheten får inte överstiga 20 tecken
validation.productRequestDTO.unitPrice.decimalMin=Priset måste vara större än noll
validation.productRequestDTO.unitPrice.digits=Priset får ha maximalt 10 heltal och 2 decimaler
validation.productRequestDTO.unitPrice.notNull=Enhetspriset krävs
validation.recipe.elaboration.size=Beredningen får inte överstiga 2000 tecken
validation.recipe.name.notBlank=Receptnamnet krävs
validation.recipe.name.size=Måste vara mellan 2 och 150 tecken
validation.recipe.presentation.size=Presentationen får inte överstiga 1000 tecken
validation.recipe.totalCost.decimalMin=Kostnaden får inte vara negativ
validation.recipeAudit.action.notBlank=Åtgärden krävs
validation.recipeAudit.details.size=Detaljerna får inte överstiga 1000 tecken
validation.recipeComponent.parentRecipe.notNull=Receptet krävs
validation.recipeComponent.product.notNull=Produkten krävs
validation.recipeComponent.quantity.decimalMin=Kvantiteten måste vara större än 0
validation.recipeComponent.quantity.notNull=Kvantiteten krävs
validation.recipeComponentRequestDTO.productId.notNull=Produkt-ID krävs
validation.recipeComponentRequestDTO.quantity.decimalMin=Kvantiteten måste vara större än noll
validation.recipeComponentRequestDTO.quantity.digits=Kvantiteten får ha maximalt 10 heltal och 3 decimaler
validation.recipeComponentRequestDTO.quantity.notNull=Kvantiteten krävs
validation.recipeCookingAudit.details.size=Detaljerna får inte överstiga 1000 tecken
validation.recipeCookingAudit.quantityCooked.decimalMin=Kvantiteten måste vara större än 0
validation.recipeCookingAudit.quantityCooked.notNull=Den tillagade kvantiteten krävs
validation.recipeCookingAudit.recipe.notNull=Receptet krävs
validation.recipeCookingRequestDTO.details.size=Detaljerna får inte överstiga 500 tecken
validation.recipeCookingRequestDTO.quantity.decimalMin=Kvantiteten måste vara större än 0
validation.recipeCookingRequestDTO.quantity.digits=Kvantiteten får ha maximalt 10 heltal och 3 decimaler
validation.recipeCookingRequestDTO.quantity.notNull=Kvantiteten att tillaga krävs
validation.recipeCookingRequestDTO.recipeId.notNull=Recept-ID krävs
validation.recipeCookingRequestDTO.recipeId.positive=Recept-ID måste vara positivt
validation.recipeRequestDTO.components.notEmpty=Receptet måste innehålla minst en komponent
validation.recipeRequestDTO.elaboration.notBlank=Beredningen krävs
validation.recipeRequestDTO.elaboration.size=Beredningen får inte överstiga 2000 tecken
validation.recipeRequestDTO.name.notBlank=Receptnamnet krävs
validation.recipeRequestDTO.name.size=Måste vara mellan 2 och 150 tecken
validation.recipeRequestDTO.presentation.notBlank=Presentationen krävs
validation.recipeRequestDTO.presentation.size=Presentationen får inte överstiga 1000 tecken
validation.roleEscalationRequestDTO.durationMinutes.max=Maximal tillåten varaktighet är 1440 minuter (24 timmar)
validation.roleEscalationRequestDTO.durationMinutes.min=Minsta varaktighet måste vara 1 minut
validation.roleEscalationRequestDTO.durationMinutes.notNull=Varaktigheten i minuter krävs
validation.stockLedger.currentHash.notBlank=Nuvarande hash krävs
validation.stockLedger.movementType.notNull=Rörelsetypen krävs
validation.stockLedger.previousHash.notBlank=Tidigare hash krävs
validation.stockLedger.product.notNull=Produkten krävs
validation.stockLedger.quantityDelta.notNull=Kvantiteten krävs
validation.stockLedger.resultingStock.notNull=Det resulterande lagret krävs
validation.stockLedger.sequenceNumber.notNull=Sekvensnumret krävs
validation.stockLedger.transactionTimestamp.notNull=Tidsstämpeln krävs
validation.stockMovementItemDTO.description.size=Beskrivningen får inte överstiga 500 tecken
validation.stockMovementItemDTO.movementType.notNull=Rörelsetypen krävs
validation.stockMovementItemDTO.productId.notNull=Produkt-ID krävs
validation.stockMovementItemDTO.quantityDelta.digits=Kvantiteten får ha maximalt 10 heltal och 3 decimaler
validation.stockMovementItemDTO.quantityDelta.notNull=Kvantiteten krävs
validation.stockSnapshot.currentStock.notNull=Det aktuella lagret krävs
validation.stockSnapshot.integrityStatus.notBlank=Integritetsstatusen krävs
validation.stockSnapshot.lastSequenceNumber.notNull=Sekvensnumret krävs
validation.stockSnapshot.lastTransactionHash.notBlank=Senaste hash krävs
validation.stockSnapshot.lastUpdated.notNull=Uppdateringsdatumet krävs
validation.supplier.name.notBlank=Leverantörsnamnet krävs
validation.supplier.name.size=Måste vara mellan 2 och 100 tecken
validation.supplierRequestDTO.name.notBlank=Leverantörsnamnet krävs
validation.supplierRequestDTO.name.size=Måste vara mellan 2 och 100 tecken
validation.user.name.notBlank=Namnet krävs
validation.user.name.size=Måste vara mellan 2 och 100 tecken
validation.user.password.notBlank=Lösenordet krävs
validation.user.role.notNull=Rollen krävs
validation.user.user.notBlank=Användarnamnet krävs
validation.userRequestDTO.name.notBlank=Namnet krävs
validation.userRequestDTO.name.size=Måste vara mellan 2 och 100 tecken
validation.userRequestDTO.password.notBlank=Lösenordet krävs
validation.userRequestDTO.password.size=Lösenordet måste vara minst 6 tecken
validation.userRequestDTO.user.notBlank=Användarnamnet krävs
validation.userRequestDTO.user.size=Användarnamnet får inte överstiga 100 tecken
"""
}

for lang, content in FILES.items():
    path = os.path.join(VDIR, f"ValidationMessages_{lang}.properties")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content.strip() + "\n")
    lines = [l for l in content.strip().split("\n") if "=" in l]
    print(f"  {lang}: wrote {len(lines)} keys")
