#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Writes TR, RU, UK ValidationMessages files."""
import os
VDIR = "src/main/resources/i18n/validation/"
FILES = {
"tr": """validation.allergen.name.notBlank=Alerjen adı zorunludur
validation.allergen.name.size=2 ile 50 karakter arasında olmalıdır
validation.allergenRequestDTO.name.notBlank=Alerjen adı zorunludur
validation.allergenRequestDTO.name.size=2 ile 50 karakter arasında olmalıdır
validation.batchStockMovementRequestDTO.movements.notEmpty=En az bir hareket dahil edilmelidir
validation.batchStockMovementRequestDTO.reason.size=Nedeni 1000 karakteri aşamaz
validation.changePasswordRequestDTO.newPassword.notBlank=Yeni şifre zorunludur
validation.changePasswordRequestDTO.newPassword.size=Yeni şifre en az 6 karakter olmalıdır
validation.inventoryAudit.actionDescription.size=Açıklama 500 karakteri aşamaz
validation.inventoryAudit.product.notNull=Ürün zorunludur
validation.inventoryAudit.quantity.notNull=Miktar zorunludur
validation.inventoryAudit.unknown.notBlank=Hareket türü zorunludur
validation.inventoryMovementRequestDTO.movementType.notNull=Hareket türü zorunludur
validation.inventoryMovementRequestDTO.productId.notNull=Ürün ID zorunludur
validation.inventoryMovementRequestDTO.quantity.decimalMax=Miktar 9.999.999,99'u aşamaz
validation.inventoryMovementRequestDTO.quantity.notNull=Miktar zorunludur
validation.inventoryMovementRequestDTO.quantity.positive=Miktar sıfırdan büyük olmalıdır
validation.inventoryMovementRequestDTO.userId.notNull=Kullanıcı ID zorunludur
validation.jwtProperties.expiration.positive=JWT bitiş süresi pozitif bir değer olmalıdır
validation.jwtProperties.secret.notBlank=JWT sırrı zorunludur
validation.loginRequestDTO.name.notBlank=Kullanıcı adı zorunludur
validation.loginRequestDTO.password.notBlank=Şifre zorunludur
validation.order.orderDate.notNull=Sipariş tarihi zorunludur
validation.order.orderDate.pastOrPresent=Sipariş tarihi gelecekte olamaz
validation.order.status.notBlank=Durum zorunludur
validation.order.users.notNull=Kullanıcı zorunludur
validation.orderAudit.action.notBlank=Eylem zorunludur
validation.orderAudit.details.size=Ayrıntılar 1000 karakteri aşamaz
validation.orderDetail.order.notNull=Sipariş zorunludur
validation.orderDetail.product.notNull=Ürün zorunludur
validation.orderDetail.quantity.decimalMin=Miktar 0'dan büyük olmalıdır
validation.orderDetail.quantity.notNull=Talep edilen miktar zorunludur
validation.orderDetail.quantityReceived.decimalMin=Alınan miktar negatif olamaz
validation.orderDetailRequestDTO.productId.notNull=Ürün ID zorunludur
validation.orderDetailRequestDTO.quantity.decimalMin=Miktar sıfırdan büyük olmalıdır
validation.orderDetailRequestDTO.quantity.digits=Miktar en fazla 10 tam sayı ve 3 ondalık basamağa sahip olabilir
validation.orderDetailRequestDTO.quantity.notNull=Miktar zorunludur
validation.orderReceptionDetailRequestDTO.productId.notNull=Ürün ID zorunludur
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Alınan miktar zorunludur
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Alınan miktar sıfır veya sıfırdan büyük olmalıdır
validation.orderReceptionRequestDTO.items.notEmpty=En az bir alınan ürün belirtilmelidir
validation.orderReceptionRequestDTO.orderId.notNull=Sipariş ID zorunludur
validation.orderReceptionRequestDTO.status.notNull=Durum zorunludur
validation.orderRequestDTO.details.notEmpty=Siparişin en az bir detayı olmalıdır
validation.orderRequestDTO.userId.notNull=Kullanıcı ID zorunludur
validation.product.availabilityPercentage.decimalMax=Kullanılabilirlik yüzdesi 100'ü aşamaz
validation.product.availabilityPercentage.decimalMin=Kullanılabilirlik yüzdesi negatif olamaz
validation.product.availabilityPercentage.digits=Geçersiz kullanılabilirlik formatı
validation.product.currentStock.decimalMin=Stok negatif olamaz
validation.product.currentStock.digits=Geçersiz stok formatı
validation.product.currentStock.notNull=Mevcut stok zorunludur
validation.product.minimumStock.decimalMin=Minimum stok negatif olamaz
validation.product.minimumStock.digits=Geçersiz minimum stok formatı
validation.product.name.notBlank=Ürün adı zorunludur
validation.product.name.size=2 ile 100 karakter arasında olmalıdır
validation.product.productCode.notBlank=Ürün kodu zorunludur
validation.product.unit.notBlank=Ölçü birimi zorunludur
validation.product.unitPrice.decimalMin=Fiyat 0'dan büyük olmalıdır
validation.product.unitPrice.digits=Geçersiz fiyat formatı
validation.product.unitPrice.notNull=Birim fiyat zorunludur
validation.productRequestDTO.availabilityPercentage.decimalMax=Kullanılabilirlik yüzdesi 100'ü aşamaz
validation.productRequestDTO.availabilityPercentage.decimalMin=Kullanılabilirlik yüzdesi negatif olamaz
validation.productRequestDTO.availabilityPercentage.digits=Yüzde en fazla 3 tam sayı ve 2 ondalık basamağa sahip olabilir
validation.productRequestDTO.currentStock.decimalMin=Stok negatif olamaz
validation.productRequestDTO.currentStock.digits=Stok en fazla 10 tam sayı ve 3 ondalık basamağa sahip olabilir
validation.productRequestDTO.currentStock.notNull=Mevcut stok zorunludur
validation.productRequestDTO.minimumStock.decimalMin=Minimum stok negatif olamaz
validation.productRequestDTO.minimumStock.digits=Minimum stok en fazla 10 tam sayı ve 3 ondalık basamağa sahip olabilir
validation.productRequestDTO.minimumStock.notNull=Minimum stok zorunludur
validation.productRequestDTO.name.notBlank=Ürün adı zorunludur
validation.productRequestDTO.name.size=2 ile 100 karakter arasında olmalıdır
validation.productRequestDTO.productCode.notBlank=Ürün kodu zorunludur
validation.productRequestDTO.productCode.size=Kod 50 karakteri aşamaz
validation.productRequestDTO.unit.notBlank=Ölçü birimi zorunludur
validation.productRequestDTO.unit.size=Birim 20 karakteri aşamaz
validation.productRequestDTO.unitPrice.decimalMin=Fiyat sıfırdan büyük olmalıdır
validation.productRequestDTO.unitPrice.digits=Fiyat en fazla 10 tam sayı ve 2 ondalık basamağa sahip olabilir
validation.productRequestDTO.unitPrice.notNull=Birim fiyat zorunludur
validation.recipe.elaboration.size=Hazırlık 2000 karakteri aşamaz
validation.recipe.name.notBlank=Tarif adı zorunludur
validation.recipe.name.size=2 ile 150 karakter arasında olmalıdır
validation.recipe.presentation.size=Sunum 1000 karakteri aşamaz
validation.recipe.totalCost.decimalMin=Maliyet negatif olamaz
validation.recipeAudit.action.notBlank=Eylem zorunludur
validation.recipeAudit.details.size=Ayrıntılar 1000 karakteri aşamaz
validation.recipeComponent.parentRecipe.notNull=Tarif zorunludur
validation.recipeComponent.product.notNull=Ürün zorunludur
validation.recipeComponent.quantity.decimalMin=Miktar 0'dan büyük olmalıdır
validation.recipeComponent.quantity.notNull=Miktar zorunludur
validation.recipeComponentRequestDTO.productId.notNull=Ürün ID zorunludur
validation.recipeComponentRequestDTO.quantity.decimalMin=Miktar sıfırdan büyük olmalıdır
validation.recipeComponentRequestDTO.quantity.digits=Miktar en fazla 10 tam sayı ve 3 ondalık basamağa sahip olabilir
validation.recipeComponentRequestDTO.quantity.notNull=Miktar zorunludur
validation.recipeCookingAudit.details.size=Ayrıntılar 1000 karakteri aşamaz
validation.recipeCookingAudit.quantityCooked.decimalMin=Miktar 0'dan büyük olmalıdır
validation.recipeCookingAudit.quantityCooked.notNull=Pişirilen miktar zorunludur
validation.recipeCookingAudit.recipe.notNull=Tarif zorunludur
validation.recipeCookingRequestDTO.details.size=Ayrıntılar 500 karakteri aşamaz
validation.recipeCookingRequestDTO.quantity.decimalMin=Miktar 0'dan büyük olmalıdır
validation.recipeCookingRequestDTO.quantity.digits=Miktar en fazla 10 tam sayı ve 3 ondalık basamağa sahip olabilir
validation.recipeCookingRequestDTO.quantity.notNull=Pişirme miktarı zorunludur
validation.recipeCookingRequestDTO.recipeId.notNull=Tarif ID zorunludur
validation.recipeCookingRequestDTO.recipeId.positive=Tarif ID pozitif olmalıdır
validation.recipeRequestDTO.components.notEmpty=Tarif en az bir bileşen içermelidir
validation.recipeRequestDTO.elaboration.notBlank=Hazırlık zorunludur
validation.recipeRequestDTO.elaboration.size=Hazırlık 2000 karakteri aşamaz
validation.recipeRequestDTO.name.notBlank=Tarif adı zorunludur
validation.recipeRequestDTO.name.size=2 ile 150 karakter arasında olmalıdır
validation.recipeRequestDTO.presentation.notBlank=Sunum zorunludur
validation.recipeRequestDTO.presentation.size=Sunum 1000 karakteri aşamaz
validation.roleEscalationRequestDTO.durationMinutes.max=İzin verilen maksimum süre 1440 dakikadır (24 saat)
validation.roleEscalationRequestDTO.durationMinutes.min=Minimum süre 1 dakika olmalıdır
validation.roleEscalationRequestDTO.durationMinutes.notNull=Dakika cinsinden süre zorunludur
validation.stockLedger.currentHash.notBlank=Mevcut karma (hash) zorunludur
validation.stockLedger.movementType.notNull=Hareket türü zorunludur
validation.stockLedger.previousHash.notBlank=Önceki karma (hash) zorunludur
validation.stockLedger.product.notNull=Ürün zorunludur
validation.stockLedger.quantityDelta.notNull=Miktar zorunludur
validation.stockLedger.resultingStock.notNull=Sonuç stoku zorunludur
validation.stockLedger.sequenceNumber.notNull=Sıra numarası zorunludur
validation.stockLedger.transactionTimestamp.notNull=Zaman damgası zorunludur
validation.stockMovementItemDTO.description.size=Açıklama 500 karakteri aşamaz
validation.stockMovementItemDTO.movementType.notNull=Hareket türü zorunludur
validation.stockMovementItemDTO.productId.notNull=Ürün ID zorunludur
validation.stockMovementItemDTO.quantityDelta.digits=Miktar en fazla 10 tam sayı ve 3 ondalık basamağa sahip olabilir
validation.stockMovementItemDTO.quantityDelta.notNull=Miktar zorunludur
validation.stockSnapshot.currentStock.notNull=Mevcut stok zorunludur
validation.stockSnapshot.integrityStatus.notBlank=Bütünlük durumu zorunludur
validation.stockSnapshot.lastSequenceNumber.notNull=Sıra numarası zorunludur
validation.stockSnapshot.lastTransactionHash.notBlank=Son karma (hash) zorunludur
validation.stockSnapshot.lastUpdated.notNull=Güncelleme tarihi zorunludur
validation.supplier.name.notBlank=Tedarikçi adı zorunludur
validation.supplier.name.size=2 ile 100 karakter arasında olmalıdır
validation.supplierRequestDTO.name.notBlank=Tedarikçi adı zorunludur
validation.supplierRequestDTO.name.size=2 ile 100 karakter arasında olmalıdır
validation.user.name.notBlank=İzin adı zorunludur
validation.user.name.size=2 ile 100 karakter arasında olmalıdır
validation.user.password.notBlank=Şifre zorunludur
validation.user.role.notNull=Rol zorunludur
validation.user.user.notBlank=Kullanıcı adı zorunludur
validation.userRequestDTO.name.notBlank=İsim zorunludur
validation.userRequestDTO.name.size=2 ile 100 karakter arasında olmalıdır
validation.userRequestDTO.password.notBlank=Şifre zorunludur
validation.userRequestDTO.password.size=Şifre en az 6 karakter olmalıdır
validation.userRequestDTO.user.notBlank=Kullanıcı adı zorunludur
validation.userRequestDTO.user.size=Kullanıcı adı 100 karakteri aşamaz
""",

"ru": """validation.allergen.name.notBlank=Имя аллергена обязательно
validation.allergen.name.size=Должно быть от 2 до 50 символов
validation.allergenRequestDTO.name.notBlank=Имя аллергена обязательно
validation.allergenRequestDTO.name.size=Должно быть от 2 до 50 символов
validation.batchStockMovementRequestDTO.movements.notEmpty=Должно быть включено хотя бы одно движение
validation.batchStockMovementRequestDTO.reason.size=Причина не может превышать 1000 символов
validation.changePasswordRequestDTO.newPassword.notBlank=Новый пароль обязателен
validation.changePasswordRequestDTO.newPassword.size=Новый пароль должен содержать не менее 6 символов
validation.inventoryAudit.actionDescription.size=Описание не может превышать 500 символов
validation.inventoryAudit.product.notNull=Продукт обязателен
validation.inventoryAudit.quantity.notNull=Количество обязательно
validation.inventoryAudit.unknown.notBlank=Тип движения обязателен
validation.inventoryMovementRequestDTO.movementType.notNull=Тип движения обязателен
validation.inventoryMovementRequestDTO.productId.notNull=ID продукта обязателен
validation.inventoryMovementRequestDTO.quantity.decimalMax=Количество не может превышать 9 999 999,99
validation.inventoryMovementRequestDTO.quantity.notNull=Количество обязательно
validation.inventoryMovementRequestDTO.quantity.positive=Количество должно быть больше нуля
validation.inventoryMovementRequestDTO.userId.notNull=ID пользователя обязателен
validation.jwtProperties.expiration.positive=Срок действия JWT должен быть положительным значением
validation.jwtProperties.secret.notBlank=Секрет JWT обязателен
validation.loginRequestDTO.name.notBlank=Имя пользователя обязательно
validation.loginRequestDTO.password.notBlank=Пароль обязателен
validation.order.orderDate.notNull=Дата заказа обязательна
validation.order.orderDate.pastOrPresent=Дата заказа не может быть в будущем
validation.order.status.notBlank=Статус обязателен
validation.order.users.notNull=Пользователь обязателен
validation.orderAudit.action.notBlank=Действие обязательно
validation.orderAudit.details.size=Детали не могут превышать 1000 символов
validation.orderDetail.order.notNull=Заказ обязателен
validation.orderDetail.product.notNull=Продукт обязателен
validation.orderDetail.quantity.decimalMin=Количество должно быть больше 0
validation.orderDetail.quantity.notNull=Запрашиваемое количество обязательно
validation.orderDetail.quantityReceived.decimalMin=Полученное количество не может быть отрицательным
validation.orderDetailRequestDTO.productId.notNull=ID продукта обязателен
validation.orderDetailRequestDTO.quantity.decimalMin=Количество должно быть больше нуля
validation.orderDetailRequestDTO.quantity.digits=Количество может иметь максимум 10 целых чисел и 3 десятичных знака
validation.orderDetailRequestDTO.quantity.notNull=Количество обязательно
validation.orderReceptionDetailRequestDTO.productId.notNull=ID продукта обязателен
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Полученное количество обязательно
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Полученное количество должно быть ноль или больше
validation.orderReceptionRequestDTO.items.notEmpty=Должен быть указан хотя бы один полученный продукт
validation.orderReceptionRequestDTO.orderId.notNull=ID заказа обязателен
validation.orderReceptionRequestDTO.status.notNull=Статус обязателен
validation.orderRequestDTO.details.notEmpty=Заказ должен иметь как минимум одну деталь
validation.orderRequestDTO.userId.notNull=ID пользователя обязателен
validation.product.availabilityPercentage.decimalMax=Процент доступности не может превышать 100
validation.product.availabilityPercentage.decimalMin=Процент доступности не может быть отрицательным
validation.product.availabilityPercentage.digits=Недопустимый формат доступности
validation.product.currentStock.decimalMin=Запас не может быть отрицательным
validation.product.currentStock.digits=Недопустимый формат запаса
validation.product.currentStock.notNull=Текущий запас обязателен
validation.product.minimumStock.decimalMin=Минимальный запас не может быть отрицательным
validation.product.minimumStock.digits=Недопустимый формат минимального запаса
validation.product.name.notBlank=Имя продукта обязательно
validation.product.name.size=Должно быть от 2 до 100 символов
validation.product.productCode.notBlank=Код продукта обязателен
validation.product.unit.notBlank=Единица измерения обязательна
validation.product.unitPrice.decimalMin=Цена должна быть больше 0
validation.product.unitPrice.digits=Недопустимый формат цены
validation.product.unitPrice.notNull=Цена за единицу обязательна
validation.productRequestDTO.availabilityPercentage.decimalMax=Процент доступности не может превышать 100
validation.productRequestDTO.availabilityPercentage.decimalMin=Процент доступности не может быть отрицательным
validation.productRequestDTO.availabilityPercentage.digits=Процент может иметь максимум 3 целых числа и 2 десятичных знака
validation.productRequestDTO.currentStock.decimalMin=Запас не может быть отрицательным
validation.productRequestDTO.currentStock.digits=Запас может иметь максимум 10 целых чисел и 3 десятичных знака
validation.productRequestDTO.currentStock.notNull=Текущий запас обязателен
validation.productRequestDTO.minimumStock.decimalMin=Минимальный запас не может быть отрицательным
validation.productRequestDTO.minimumStock.digits=Минимальный запас может иметь максимум 10 целых чисел и 3 десятичных знака
validation.productRequestDTO.minimumStock.notNull=Минимальный запас обязателен
validation.productRequestDTO.name.notBlank=Имя продукта обязательно
validation.productRequestDTO.name.size=Должно быть от 2 до 100 символов
validation.productRequestDTO.productCode.notBlank=Код продукта обязателен
validation.productRequestDTO.productCode.size=Код не может превышать 50 символов
validation.productRequestDTO.unit.notBlank=Единица измерения обязательна
validation.productRequestDTO.unit.size=Единица не может превышать 20 символов
validation.productRequestDTO.unitPrice.decimalMin=Цена должна быть больше нуля
validation.productRequestDTO.unitPrice.digits=Цена может иметь максимум 10 целых чисел и 2 десятичных знака
validation.productRequestDTO.unitPrice.notNull=Цена за единицу обязательна
validation.recipe.elaboration.size=Приготовление не может превышать 2000 символов
validation.recipe.name.notBlank=Имя рецепта обязательно
validation.recipe.name.size=Должно быть от 2 до 150 символов
validation.recipe.presentation.size=Презентация не может превышать 1000 символов
validation.recipe.totalCost.decimalMin=Стоимость не может быть отрицательной
validation.recipeAudit.action.notBlank=Действие обязательно
validation.recipeAudit.details.size=Детали не могут превышать 1000 символов
validation.recipeComponent.parentRecipe.notNull=Рецепт обязателен
validation.recipeComponent.product.notNull=Продукт обязателен
validation.recipeComponent.quantity.decimalMin=Количество должно быть больше 0
validation.recipeComponent.quantity.notNull=Количество обязательно
validation.recipeComponentRequestDTO.productId.notNull=ID продукта обязателен
validation.recipeComponentRequestDTO.quantity.decimalMin=Количество должно быть больше нуля
validation.recipeComponentRequestDTO.quantity.digits=Количество может иметь максимум 10 целых чисел и 3 десятичных знака
validation.recipeComponentRequestDTO.quantity.notNull=Количество обязательно
validation.recipeCookingAudit.details.size=Детали не могут превышать 1000 символов
validation.recipeCookingAudit.quantityCooked.decimalMin=Количество должно быть больше 0
validation.recipeCookingAudit.quantityCooked.notNull=Приготовленное количество обязательно
validation.recipeCookingAudit.recipe.notNull=Рецепт обязателен
validation.recipeCookingRequestDTO.details.size=Детали не могут превышать 500 символов
validation.recipeCookingRequestDTO.quantity.decimalMin=Количество должно быть больше 0
validation.recipeCookingRequestDTO.quantity.digits=Количество может иметь максимум 10 целых чисел и 3 десятичных знака
validation.recipeCookingRequestDTO.quantity.notNull=Количество для приготовления обязательно
validation.recipeCookingRequestDTO.recipeId.notNull=ID рецепта обязателен
validation.recipeCookingRequestDTO.recipeId.positive=ID рецепта должен быть положительным
validation.recipeRequestDTO.components.notEmpty=Рецепт должен содержать хотя бы один компонент
validation.recipeRequestDTO.elaboration.notBlank=Приготовление обязательно
validation.recipeRequestDTO.elaboration.size=Приготовление не может превышать 2000 символов
validation.recipeRequestDTO.name.notBlank=Имя рецепта обязательно
validation.recipeRequestDTO.name.size=Должно быть от 2 до 150 символов
validation.recipeRequestDTO.presentation.notBlank=Презентация обязательна
validation.recipeRequestDTO.presentation.size=Презентация не может превышать 1000 символов
validation.roleEscalationRequestDTO.durationMinutes.max=Максимально допустимая продолжительность - 1440 минут (24 часа)
validation.roleEscalationRequestDTO.durationMinutes.min=Минимальная продолжительность должна составлять 1 минуту
validation.roleEscalationRequestDTO.durationMinutes.notNull=Продолжительность в минутах обязательна
validation.stockLedger.currentHash.notBlank=Текущий хэш обязателен
validation.stockLedger.movementType.notNull=Тип движения обязателен
validation.stockLedger.previousHash.notBlank=Предыдущий хэш обязателен
validation.stockLedger.product.notNull=Продукт обязателен
validation.stockLedger.quantityDelta.notNull=Количество обязательно
validation.stockLedger.resultingStock.notNull=Результирующий запас обязателен
validation.stockLedger.sequenceNumber.notNull=Порядковый номер обязателен
validation.stockLedger.transactionTimestamp.notNull=Временная метка обязательна
validation.stockMovementItemDTO.description.size=Описание не может превышать 500 символов
validation.stockMovementItemDTO.movementType.notNull=Тип движения обязателен
validation.stockMovementItemDTO.productId.notNull=ID продукта обязателен
validation.stockMovementItemDTO.quantityDelta.digits=Количество может иметь максимум 10 целых чисел и 3 десятичных знака
validation.stockMovementItemDTO.quantityDelta.notNull=Количество обязательно
validation.stockSnapshot.currentStock.notNull=Текущий запас обязателен
validation.stockSnapshot.integrityStatus.notBlank=Статус целостности обязателен
validation.stockSnapshot.lastSequenceNumber.notNull=Порядковый номер обязателен
validation.stockSnapshot.lastTransactionHash.notBlank=Последний хэш обязателен
validation.stockSnapshot.lastUpdated.notNull=Дата обновления обязательна
validation.supplier.name.notBlank=Имя поставщика обязательно
validation.supplier.name.size=Должно быть от 2 до 100 символов
validation.supplierRequestDTO.name.notBlank=Имя поставщика обязательно
validation.supplierRequestDTO.name.size=Должно быть от 2 до 100 символов
validation.user.name.notBlank=Имя обязательно
validation.user.name.size=Должно быть от 2 до 100 символов
validation.user.password.notBlank=Пароль обязателен
validation.user.role.notNull=Роль обязательна
validation.user.user.notBlank=Имя пользователя обязательно
validation.userRequestDTO.name.notBlank=Имя обязательно
validation.userRequestDTO.name.size=Должно быть от 2 до 100 символов
validation.userRequestDTO.password.notBlank=Пароль обязателен
validation.userRequestDTO.password.size=Пароль должен содержать не менее 6 символов
validation.userRequestDTO.user.notBlank=Имя пользователя обязательно
validation.userRequestDTO.user.size=Имя пользователя не может превышать 100 символов
""",

"uk": """validation.allergen.name.notBlank=Ім'я алергену є обов'язковим
validation.allergen.name.size=Повинно бути від 2 до 50 символів
validation.allergenRequestDTO.name.notBlank=Ім'я алергену є обов'язковим
validation.allergenRequestDTO.name.size=Повинно бути від 2 до 50 символів
validation.batchStockMovementRequestDTO.movements.notEmpty=Повинен бути включений принаймні один рух
validation.batchStockMovementRequestDTO.reason.size=Причина не може перевищувати 1000 символів
validation.changePasswordRequestDTO.newPassword.notBlank=Новий пароль є обов'язковим
validation.changePasswordRequestDTO.newPassword.size=Новий пароль повинен містити не менше 6 символів
validation.inventoryAudit.actionDescription.size=Опис не може перевищувати 500 символів
validation.inventoryAudit.product.notNull=Продукт є обов'язковим
validation.inventoryAudit.quantity.notNull=Кількість є обов'язковою
validation.inventoryAudit.unknown.notBlank=Тип руху є обов'язковим
validation.inventoryMovementRequestDTO.movementType.notNull=Тип руху є обов'язковим
validation.inventoryMovementRequestDTO.productId.notNull=ID продукту є обов'язковим
validation.inventoryMovementRequestDTO.quantity.decimalMax=Кількість не може перевищувати 9 999 999,99
validation.inventoryMovementRequestDTO.quantity.notNull=Кількість є обов'язковою
validation.inventoryMovementRequestDTO.quantity.positive=Кількість повинна бути більше нуля
validation.inventoryMovementRequestDTO.userId.notNull=ID користувача є обов'язковим
validation.jwtProperties.expiration.positive=Термін дії JWT повинен бути позитивним значенням
validation.jwtProperties.secret.notBlank=Секрет JWT є обов'язковим
validation.loginRequestDTO.name.notBlank=Ім'я користувача є обов'язковим
validation.loginRequestDTO.password.notBlank=Пароль є обов'язковим
validation.order.orderDate.notNull=Дата замовлення є обов'язковою
validation.order.orderDate.pastOrPresent=Дата замовлення не може бути в майбутньому
validation.order.status.notBlank=Статус є обов'язковим
validation.order.users.notNull=Користувач є обов'язковим
validation.orderAudit.action.notBlank=Дія є обов'язковою
validation.orderAudit.details.size=Деталі не можуть перевищувати 1000 символів
validation.orderDetail.order.notNull=Замовлення є обов'язкове
validation.orderDetail.product.notNull=Продукт є обов'язковим
validation.orderDetail.quantity.decimalMin=Кількість повинна бути більше 0
validation.orderDetail.quantity.notNull=Запитувана кількість є обов'язковою
validation.orderDetail.quantityReceived.decimalMin=Отримана кількість не може бути від'ємною
validation.orderDetailRequestDTO.productId.notNull=ID продукту є обов'язковим
validation.orderDetailRequestDTO.quantity.decimalMin=Кількість повинна бути більше нуля
validation.orderDetailRequestDTO.quantity.digits=Кількість може мати максимум 10 цілих чисел та 3 десяткових знаки
validation.orderDetailRequestDTO.quantity.notNull=Кількість є обов'язковою
validation.orderReceptionDetailRequestDTO.productId.notNull=ID продукту є обов'язковим
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Отримана кількість є обов'язковою
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Отримана кількість повинна бути нуль або більше
validation.orderReceptionRequestDTO.items.notEmpty=Повинен бути вказаний хоча б один отриманий продукт
validation.orderReceptionRequestDTO.orderId.notNull=ID замовлення є обов'язковим
validation.orderReceptionRequestDTO.status.notNull=Статус є обов'язковим
validation.orderRequestDTO.details.notEmpty=Замовлення повинно мати як мінімум одну деталь
validation.orderRequestDTO.userId.notNull=ID користувача є обов'язковим
validation.product.availabilityPercentage.decimalMax=Відсоток доступності не може перевищувати 100
validation.product.availabilityPercentage.decimalMin=Відсоток доступності не може бути від'ємним
validation.product.availabilityPercentage.digits=Недійсний формат доступности
validation.product.currentStock.decimalMin=Запас не може бути від'ємним
validation.product.currentStock.digits=Недійсний формат запасу
validation.product.currentStock.notNull=Поточний запас є обов'язковим
validation.product.minimumStock.decimalMin=Мінімальний запас не може бути від'ємним
validation.product.minimumStock.digits=Недійсний формат мінімального запасу
validation.product.name.notBlank=Ім'я продукту є обов'язковим
validation.product.name.size=Повинно бути від 2 до 100 символів
validation.product.productCode.notBlank=Код продукту є обов'язковим
validation.product.unit.notBlank=Одиниця виміру є обов'язковою
validation.product.unitPrice.decimalMin=Ціна повинна бути більше 0
validation.product.unitPrice.digits=Недійсний формат ціни
validation.product.unitPrice.notNull=Ціна за одиницю є обов'язковою
validation.productRequestDTO.availabilityPercentage.decimalMax=Відсоток доступності не може перевищувати 100
validation.productRequestDTO.availabilityPercentage.decimalMin=Відсоток доступності не може бути від'ємним
validation.productRequestDTO.availabilityPercentage.digits=Відсоток може мати максимум 3 цілих числа та 2 десяткових знаки
validation.productRequestDTO.currentStock.decimalMin=Запас не може бути від'ємним
validation.productRequestDTO.currentStock.digits=Запас може мати максимум 10 цілих чисел та 3 десяткових знаки
validation.productRequestDTO.currentStock.notNull=Поточний запас є обов'язковим
validation.productRequestDTO.minimumStock.decimalMin=Мінімальний запас не може бути від'ємним
validation.productRequestDTO.minimumStock.digits=Мінімальний запас може мати максимум 10 цілих чисел та 3 десяткових знаки
validation.productRequestDTO.minimumStock.notNull=Мінімальний запас є обов'язковим
validation.productRequestDTO.name.notBlank=Ім'я продукту є обов'язковим
validation.productRequestDTO.name.size=Повинно бути від 2 до 100 символів
validation.productRequestDTO.productCode.notBlank=Код продукту є обов'язковим
validation.productRequestDTO.productCode.size=Код не може перевищувати 50 символов
validation.productRequestDTO.unit.notBlank=Одиниця виміру є обов'язковою
validation.productRequestDTO.unit.size=Одиниця не може перевищувати 20 символів
validation.productRequestDTO.unitPrice.decimalMin=Ціна повинна бути більше нуля
validation.productRequestDTO.unitPrice.digits=Ціна може мати максимум 10 цілих чисел та 2 десяткових знаки
validation.productRequestDTO.unitPrice.notNull=Ціна за одиницю є обов'язковою
validation.recipe.elaboration.size=Приготування не може перевищувати 2000 символів
validation.recipe.name.notBlank=Ім'я рецепта є обов'язковим
validation.recipe.name.size=Повинно бути від 2 до 150 символів
validation.recipe.presentation.size=Презентація не може перевищувати 1000 символів
validation.recipe.totalCost.decimalMin=Вартість не може бути від'ємною
validation.recipeAudit.action.notBlank=Дія є обов'язковою
validation.recipeAudit.details.size=Деталі не можуть перевищувати 1000 символів
validation.recipeComponent.parentRecipe.notNull=Рецепт є обов'язковим
validation.recipeComponent.product.notNull=Продукт є обов'язковим
validation.recipeComponent.quantity.decimalMin=Кількість повинна бути більше 0
validation.recipeComponent.quantity.notNull=Кількість є обов'язковою
validation.recipeComponentRequestDTO.productId.notNull=ID продукту є обов'язковим
validation.recipeComponentRequestDTO.quantity.decimalMin=Кількість повинна бути більше нуля
validation.recipeComponentRequestDTO.quantity.digits=Кількість може мати максимум 10 цілих чисел та 3 десяткових знаки
validation.recipeComponentRequestDTO.quantity.notNull=Кількість є обов'язковою
validation.recipeCookingAudit.details.size=Деталі не можуть перевищувати 1000 символів
validation.recipeCookingAudit.quantityCooked.decimalMin=Кількість повинна бути більше 0
validation.recipeCookingAudit.quantityCooked.notNull=Приготована кількість є обов'язковою
validation.recipeCookingAudit.recipe.notNull=Рецепт є обов'язковим
validation.recipeCookingRequestDTO.details.size=Деталі не можуть перевищувати 500 символів
validation.recipeCookingRequestDTO.quantity.decimalMin=Кількість повинна бути більше 0
validation.recipeCookingRequestDTO.quantity.digits=Кількість може мати максимум 10 цілих чисел та 3 десяткових знаки
validation.recipeCookingRequestDTO.quantity.notNull=Кількість для приготування є обов'язковою
validation.recipeCookingRequestDTO.recipeId.notNull=ID рецепту є обов'язковим
validation.recipeCookingRequestDTO.recipeId.positive=ID рецепту повинен бути позитивним
validation.recipeRequestDTO.components.notEmpty=Рецепт повинен мати хоча б один компонент
validation.recipeRequestDTO.elaboration.notBlank=Приготування є обов'язковою
validation.recipeRequestDTO.elaboration.size=Приготування не може перевищувати 2000 символів
validation.recipeRequestDTO.name.notBlank=Ім'я рецепта є обов'язковим
validation.recipeRequestDTO.name.size=Повинно бути від 2 до 150 символів
validation.recipeRequestDTO.presentation.notBlank=Презентація є обов'язковою
validation.recipeRequestDTO.presentation.size=Презентація не може перевищувати 1000 символів
validation.roleEscalationRequestDTO.durationMinutes.max=Максимально допустима тривалість - 1440 хвилин (24 години)
validation.roleEscalationRequestDTO.durationMinutes.min=Мінімальна тривалість повинна складати 1 хвилину
validation.roleEscalationRequestDTO.durationMinutes.notNull=Тривалість у хвилинах є обов'язковою
validation.stockLedger.currentHash.notBlank=Поточний хеш є обов'язковим
validation.stockLedger.movementType.notNull=Тип руху є обов'язковим
validation.stockLedger.previousHash.notBlank=Попередній хеш є обов'язковим
validation.stockLedger.product.notNull=Продукт є обов'язковим
validation.stockLedger.quantityDelta.notNull=Кількість є обов'язковою
validation.stockLedger.resultingStock.notNull=Результуючий запас є обов'язковим
validation.stockLedger.sequenceNumber.notNull=Порядковий номер є обов'язковим
validation.stockLedger.transactionTimestamp.notNull=Мітка часу є обов'язковою
validation.stockMovementItemDTO.description.size=Опис не може перевищувати 500 символів
validation.stockMovementItemDTO.movementType.notNull=Тип руху є обов'язковим
validation.stockMovementItemDTO.productId.notNull=ID продукту є обов'язковим
validation.stockMovementItemDTO.quantityDelta.digits=Кількість може мати максимум 10 цілих чисел та 3 десяткових знаки
validation.stockMovementItemDTO.quantityDelta.notNull=Кількість є обов'язковою
validation.stockSnapshot.currentStock.notNull=Поточний запас є обов'язковим
validation.stockSnapshot.integrityStatus.notBlank=Статус цілісності є обов'язковим
validation.stockSnapshot.lastSequenceNumber.notNull=Порядковий номер є обов'язковим
validation.stockSnapshot.lastTransactionHash.notBlank=Останній хеш є обов'язковим
validation.stockSnapshot.lastUpdated.notNull=Дата оновлення є обов'язковою
validation.supplier.name.notBlank=Ім'я постачальника є обов'язковим
validation.supplier.name.size=Повинно бути від 2 до 100 символів
validation.supplierRequestDTO.name.notBlank=Ім'я постачальника є обов'язковим
validation.supplierRequestDTO.name.size=Повинно бути від 2 до 100 символів
validation.user.name.notBlank=Ім'я є обов'язковим
validation.user.name.size=Повинно бути від 2 до 100 символів
validation.user.password.notBlank=Пароль є обов'язковим
validation.user.role.notNull=Роль є обов'язкова
validation.user.user.notBlank=Ім'я користувача є обов'язковим
validation.userRequestDTO.name.notBlank=Ім'я є обов'язкове
validation.userRequestDTO.name.size=Повинно бути від 2 до 100 символів
validation.userRequestDTO.password.notBlank=Пароль є обов'язковим
validation.userRequestDTO.password.size=Пароль повинен містити не менше 6 символів
validation.userRequestDTO.user.notBlank=Ім'я користувача є обов'язковим
validation.userRequestDTO.user.size=Ім'я користувача не може перевищувати 100 символів
"""
}

for lang, content in FILES.items():
    path = os.path.join(VDIR, f"ValidationMessages_{lang}.properties")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content.strip() + "\n")
    lines = [l for l in content.strip().split("\n") if "=" in l]
    print(f"  {lang}: wrote {len(lines)} keys")
