#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Writes NO, DA, FI, PL ValidationMessages files."""
import os
VDIR = "src/main/resources/i18n/validation/"
FILES = {
"no": """validation.allergen.name.notBlank=Allergennavnet er påkrevd
validation.allergen.name.size=Må være mellom 2 og 50 tegn
validation.allergenRequestDTO.name.notBlank=Allergennavnet er påkrevd
validation.allergenRequestDTO.name.size=Må være mellom 2 og 50 tegn
validation.batchStockMovementRequestDTO.movements.notEmpty=Minst én bevegelse må inkluderes
validation.batchStockMovementRequestDTO.reason.size=Årsaken kan ikke overstige 1000 tegn
validation.changePasswordRequestDTO.newPassword.notBlank=Det nye passordet er påkrevd
validation.changePasswordRequestDTO.newPassword.size=Det nye passordet må være minst 6 tegn
validation.inventoryAudit.actionDescription.size=Beskrivelsen kan ikke overstige 500 tegn
validation.inventoryAudit.product.notNull=Produktet er påkrevd
validation.inventoryAudit.quantity.notNull=Mengden er påkrevd
validation.inventoryAudit.unknown.notBlank=Bevegelsestypen er påkrevd
validation.inventoryMovementRequestDTO.movementType.notNull=Bevegelsestypen er påkrevd
validation.inventoryMovementRequestDTO.productId.notNull=Produkt-ID er påkrevd
validation.inventoryMovementRequestDTO.quantity.decimalMax=Mengden kan ikke overstige 9.999.999,99
validation.inventoryMovementRequestDTO.quantity.notNull=Mengden er påkrevd
validation.inventoryMovementRequestDTO.quantity.positive=Mengden må være større enn null
validation.inventoryMovementRequestDTO.userId.notNull=Bruker-ID er påkrevd
validation.jwtProperties.expiration.positive=JWT-utløp må være en positiv verdi
validation.jwtProperties.secret.notBlank=JWT-hemmeligheten er påkrevd
validation.loginRequestDTO.name.notBlank=Brukernavnet er påkrevd
validation.loginRequestDTO.password.notBlank=Passordet er påkrevd
validation.order.orderDate.notNull=Bestillingsdatoen er påkrevd
validation.order.orderDate.pastOrPresent=Bestillingsdatoen kan ikke være i fremtiden
validation.order.status.notBlank=Status er påkrevd
validation.order.users.notNull=Brukeren er påkrevd
validation.orderAudit.action.notBlank=Handlingen er påkrevd
validation.orderAudit.details.size=Detaljene kan ikke overstige 1000 tegn
validation.orderDetail.order.notNull=Bestillingen er påkrevd
validation.orderDetail.product.notNull=Produktet er påkrevd
validation.orderDetail.quantity.decimalMin=Mengden må være større enn 0
validation.orderDetail.quantity.notNull=Den forespurte mengden er påkrevd
validation.orderDetail.quantityReceived.decimalMin=Den mottatte mengden kan ikke være negativ
validation.orderDetailRequestDTO.productId.notNull=Produkt-ID er påkrevd
validation.orderDetailRequestDTO.quantity.decimalMin=Mengden må være større enn null
validation.orderDetailRequestDTO.quantity.digits=Mengden kan ha maksimalt 10 heltall og 3 desimaler
validation.orderDetailRequestDTO.quantity.notNull=Mengden er påkrevd
validation.orderReceptionDetailRequestDTO.productId.notNull=Produkt-ID er påkrevd
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Den mottatte mengden er påkrevd
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Den mottatte mengden må være null eller større
validation.orderReceptionRequestDTO.items.notEmpty=Minst ett mottatt produkt må spesifiseres
validation.orderReceptionRequestDTO.orderId.notNull=Ordre-ID er påkrevd
validation.orderReceptionRequestDTO.status.notNull=Status er påkrevd
validation.orderRequestDTO.details.notEmpty=Bestillingen må ha minst én detalj
validation.orderRequestDTO.userId.notNull=Bruker-ID er påkrevd
validation.product.availabilityPercentage.decimalMax=Tilgjengelighetsprosenten kan ikke overstige 100
validation.product.availabilityPercentage.decimalMin=Tilgjengelighetsprosenten kan ikke være negativ
validation.product.availabilityPercentage.digits=Ugyldig tilgjengelighetsformat
validation.product.currentStock.decimalMin=Beholdningen kan ikke være negativ
validation.product.currentStock.digits=Ugyldig beholdningsformat
validation.product.currentStock.notNull=Nåværende beholdning er påkrevd
validation.product.minimumStock.decimalMin=Minimumsbeholdning kan ikke være negativ
validation.product.minimumStock.digits=Ugyldig format for minimumsbeholdning
validation.product.name.notBlank=Produktnavnet er påkrevd
validation.product.name.size=Må være mellom 2 og 100 tegn
validation.product.productCode.notBlank=Produktkoden er påkrevd
validation.product.unit.notBlank=Måleenheten er påkrevd
validation.product.unitPrice.decimalMin=Prisen må være større enn 0
validation.product.unitPrice.digits=Ugyldig prisformat
validation.product.unitPrice.notNull=Enhetsprisen er påkrevd
validation.productRequestDTO.availabilityPercentage.decimalMax=Tilgjengelighetsprosenten kan ikke overstige 100
validation.productRequestDTO.availabilityPercentage.decimalMin=Tilgjengelighetsprosenten kan ikke være negativ
validation.productRequestDTO.availabilityPercentage.digits=Prosenten kan ha maksimalt 3 heltall og 2 desimaler
validation.productRequestDTO.currentStock.decimalMin=Beholdningen kan ikke være negativ
validation.productRequestDTO.currentStock.digits=Beholdningen kan ha maksimalt 10 heltall og 3 desimaler
validation.productRequestDTO.currentStock.notNull=Nåværende beholdning er påkrevd
validation.productRequestDTO.minimumStock.decimalMin=Minimumsbeholdning kan ikke være negativ
validation.productRequestDTO.minimumStock.digits=Minimumsbeholdning kan ha maksimalt 10 heltall og 3 desimaler
validation.productRequestDTO.minimumStock.notNull=Minimumsbeholdning er påkrevd
validation.productRequestDTO.name.notBlank=Produktnavnet er påkrevd
validation.productRequestDTO.name.size=Må være mellom 2 og 100 tegn
validation.productRequestDTO.productCode.notBlank=Produktkoden er påkrevd
validation.productRequestDTO.productCode.size=Koden kan ikke overstige 50 tegn
validation.productRequestDTO.unit.notBlank=Måleenheten er påkrevd
validation.productRequestDTO.unit.size=Enheten kan ikke overstige 20 tegn
validation.productRequestDTO.unitPrice.decimalMin=Prisen må være større enn null
validation.productRequestDTO.unitPrice.digits=Prisen kan ha maksimalt 10 heltall og 2 desimaler
validation.productRequestDTO.unitPrice.notNull=Enhetsprisen er påkrevd
validation.recipe.elaboration.size=Tilberedningen kan ikke overstige 2000 tegn
validation.recipe.name.notBlank=Oppskriftsnavnet er påkrevd
validation.recipe.name.size=Må være mellom 2 og 150 tegn
validation.recipe.presentation.size=Presentasjonen kan ikke overstige 1000 tegn
validation.recipe.totalCost.decimalMin=Kostnaden kan ikke være negativ
validation.recipeAudit.action.notBlank=Handlingen er påkrevd
validation.recipeAudit.details.size=Detaljene kan ikke overstige 1000 tegn
validation.recipeComponent.parentRecipe.notNull=Oppskriften er påkrevd
validation.recipeComponent.product.notNull=Produktet er påkrevd
validation.recipeComponent.quantity.decimalMin=Mengden må være større enn 0
validation.recipeComponent.quantity.notNull=Mengden er påkrevd
validation.recipeComponentRequestDTO.productId.notNull=Produkt-ID er påkrevd
validation.recipeComponentRequestDTO.quantity.decimalMin=Mengden må være større enn null
validation.recipeComponentRequestDTO.quantity.digits=Mengden kan ha maksimalt 10 heltall og 3 desimaler
validation.recipeComponentRequestDTO.quantity.notNull=Mengden er påkrevd
validation.recipeCookingAudit.details.size=Detaljene kan ikke overstige 1000 tegn
validation.recipeCookingAudit.quantityCooked.decimalMin=Mengden må være større enn 0
validation.recipeCookingAudit.quantityCooked.notNull=Den tilberedte mengden er påkrevd
validation.recipeCookingAudit.recipe.notNull=Oppskriften er påkrevd
validation.recipeCookingRequestDTO.details.size=Detaljene kan ikke overstige 500 tegn
validation.recipeCookingRequestDTO.quantity.decimalMin=Mengden må være større enn 0
validation.recipeCookingRequestDTO.quantity.digits=Mengden kan ha maksimalt 10 heltall og 3 desimaler
validation.recipeCookingRequestDTO.quantity.notNull=Mengden som skal tilberedes er påkrevd
validation.recipeCookingRequestDTO.recipeId.notNull=Oppskrift-ID er påkrevd
validation.recipeCookingRequestDTO.recipeId.positive=Oppskrift-ID må være positiv
validation.recipeRequestDTO.components.notEmpty=Oppskriften må inneholde minst én komponent
validation.recipeRequestDTO.elaboration.notBlank=Tilberedningen er påkrevd
validation.recipeRequestDTO.elaboration.size=Tilberedningen kan ikke overstige 2000 tegn
validation.recipeRequestDTO.name.notBlank=Oppskriftsnavnet er påkrevd
validation.recipeRequestDTO.name.size=Må være mellom 2 og 150 tegn
validation.recipeRequestDTO.presentation.notBlank=Presentasjonen er påkrevd
validation.recipeRequestDTO.presentation.size=Presentasjonen kan ikke overstige 1000 tegn
validation.roleEscalationRequestDTO.durationMinutes.max=Maksimal tillatt varighet er 1440 minutter (24 timer)
validation.roleEscalationRequestDTO.durationMinutes.min=Minimumsvarighet må være 1 minutt
validation.roleEscalationRequestDTO.durationMinutes.notNull=Varigheten i minutter er påkrevd
validation.stockLedger.currentHash.notBlank=Nåværende hash er påkrevd
validation.stockLedger.movementType.notNull=Bevegelsestypen er påkrevd
validation.stockLedger.previousHash.notBlank=Tidligere hash er påkrevd
validation.stockLedger.product.notNull=Produktet er påkrevd
validation.stockLedger.quantityDelta.notNull=Mengden er påkrevd
validation.stockLedger.resultingStock.notNull=Resulterende beholdning er påkrevd
validation.stockLedger.sequenceNumber.notNull=Sekvensnummeret er påkrevd
validation.stockLedger.transactionTimestamp.notNull=Tidsstempelet er påkrevd
validation.stockMovementItemDTO.description.size=Beskrivelsen kan ikke overstige 500 tegn
validation.stockMovementItemDTO.movementType.notNull=Bevegelsestypen er påkrevd
validation.stockMovementItemDTO.productId.notNull=Produkt-ID er påkrevd
validation.stockMovementItemDTO.quantityDelta.digits=Mengden kan ha maksimalt 10 heltall og 3 desimaler
validation.stockMovementItemDTO.quantityDelta.notNull=Mengden er påkrevd
validation.stockSnapshot.currentStock.notNull=Nåværende beholdning er påkrevd
validation.stockSnapshot.integrityStatus.notBlank=Integritetsstatus er påkrevd
validation.stockSnapshot.lastSequenceNumber.notNull=Sekvensnummeret er påkrevd
validation.stockSnapshot.lastTransactionHash.notBlank=Siste hash er påkrevd
validation.stockSnapshot.lastUpdated.notNull=Oppdateringsdatoen er påkrevd
validation.supplier.name.notBlank=Leverandørnavnet er påkrevd
validation.supplier.name.size=Må være mellom 2 og 100 tegn
validation.supplierRequestDTO.name.notBlank=Leverandørnavnet er påkrevd
validation.supplierRequestDTO.name.size=Må være mellom 2 og 100 tegn
validation.user.name.notBlank=Navnet er påkrevd
validation.user.name.size=Må være mellom 2 og 100 tegn
validation.user.password.notBlank=Passordet er påkrevd
validation.user.role.notNull=Rollen er påkrevd
validation.user.user.notBlank=Brukernavnet er påkrevd
validation.userRequestDTO.name.notBlank=Navnet er påkrevd
validation.userRequestDTO.name.size=Må være mellom 2 og 100 tegn
validation.userRequestDTO.password.notBlank=Passordet er påkrevd
validation.userRequestDTO.password.size=Passordet må være minst 6 tegn
validation.userRequestDTO.user.notBlank=Brukernavnet er påkrevd
validation.userRequestDTO.user.size=Brukernavnet kan ikke overstige 100 tegn
""",

"da": """validation.allergen.name.notBlank=Allergennavnet er påkrævet
validation.allergen.name.size=Skal være mellem 2 og 50 tegn
validation.allergenRequestDTO.name.notBlank=Allergennavnet er påkrævet
validation.allergenRequestDTO.name.size=Skal være mellem 2 og 50 tegn
validation.batchStockMovementRequestDTO.movements.notEmpty=Mindst én bevægelse skal inkluderes
validation.batchStockMovementRequestDTO.reason.size=Årsagen må ikke overstige 1000 tegn
validation.changePasswordRequestDTO.newPassword.notBlank=Den nye adgangskode er påkrævet
validation.changePasswordRequestDTO.newPassword.size=Den nye adgangskode skal være mindst 6 tegn
validation.inventoryAudit.actionDescription.size=Beskrivelsen må ikke overstige 500 tegn
validation.inventoryAudit.product.notNull=Produktet er påkrævet
validation.inventoryAudit.quantity.notNull=Mængden er påkrævet
validation.inventoryAudit.unknown.notBlank=Bevægelsestypen er påkrævet
validation.inventoryMovementRequestDTO.movementType.notNull=Bevægelsestypen er påkrævet
validation.inventoryMovementRequestDTO.productId.notNull=Produkt-ID er påkrævet
validation.inventoryMovementRequestDTO.quantity.decimalMax=Mængden må ikke overstige 9.999.999,99
validation.inventoryMovementRequestDTO.quantity.notNull=Mængden er påkrævet
validation.inventoryMovementRequestDTO.quantity.positive=Mængden skal være større end nul
validation.inventoryMovementRequestDTO.userId.notNull=Bruger-ID er påkrævet
validation.jwtProperties.expiration.positive=JWT-udløb skal være en positiv værdi
validation.jwtProperties.secret.notBlank=JWT-hemmeligheden er påkrævet
validation.loginRequestDTO.name.notBlank=Brugernavnet er påkrævet
validation.loginRequestDTO.password.notBlank=Adgangskoden er påkrævet
validation.order.orderDate.notNull=Bestillingsdatoen er påkrævet
validation.order.orderDate.pastOrPresent=Bestillingsdatoen må ikke være i fremtiden
validation.order.status.notBlank=Status er påkrævet
validation.order.users.notNull=Brugeren er påkrævet
validation.orderAudit.action.notBlank=Handlingen er påkrævet
validation.orderAudit.details.size=Detaljerne må ikke overstige 1000 tegn
validation.orderDetail.order.notNull=Bestillingen er påkrævet
validation.orderDetail.product.notNull=Produktet er påkrævet
validation.orderDetail.quantity.decimalMin=Mængden skal være større end 0
validation.orderDetail.quantity.notNull=Den anmodede mængde er påkrævet
validation.orderDetail.quantityReceived.decimalMin=Den modtagne mængde må ikke være negativ
validation.orderDetailRequestDTO.productId.notNull=Produkt-ID er påkrævet
validation.orderDetailRequestDTO.quantity.decimalMin=Mængden skal være større end nul
validation.orderDetailRequestDTO.quantity.digits=Mængden må maksimalt have 10 heltal og 3 decimaler
validation.orderDetailRequestDTO.quantity.notNull=Mængden er påkrævet
validation.orderReceptionDetailRequestDTO.productId.notNull=Produkt-ID er påkrævet
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Den modtagne mængde er påkrævet
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Den modtagne mængde skal være nul eller større
validation.orderReceptionRequestDTO.items.notEmpty=Mindst ét modtaget produkt skal angives
validation.orderReceptionRequestDTO.orderId.notNull=Ordre-ID er påkrævet
validation.orderReceptionRequestDTO.status.notNull=Status er påkrævet
validation.orderRequestDTO.details.notEmpty=Bestillingen skal have mindst én detalje
validation.orderRequestDTO.userId.notNull=Bruker-ID er påkrævet
validation.product.availabilityPercentage.decimalMax=Tilgængelighedsprocenten må ikke overstige 100
validation.product.availabilityPercentage.decimalMin=Tilgængelighedsprocenten må ikke være negativ
validation.product.availabilityPercentage.digits=Ugyldigt tilgængelighedsformat
validation.product.currentStock.decimalMin=Beholdningen må ikke være negativ
validation.product.currentStock.digits=Ugyldigt beholdningsformat
validation.product.currentStock.notNull=Den aktuelle beholdning er påkrævet
validation.product.minimumStock.decimalMin=Minimumsbeholdning må ikke være negativ
validation.product.minimumStock.digits=Ugyldigt format for minimumsbeholdning
validation.product.name.notBlank=Produktnavnet er påkrævet
validation.product.name.size=Skal være mellem 2 og 100 tegn
validation.product.productCode.notBlank=Produktkoden er påkrævet
validation.product.unit.notBlank=Måleenheden er påkrævet
validation.product.unitPrice.decimalMin=Prisen skal være større end 0
validation.product.unitPrice.digits=Ugyldigt prisformat
validation.product.unitPrice.notNull=Enhedsprisen er påkrævet
validation.productRequestDTO.availabilityPercentage.decimalMax=Tilgængelighedsprocenten må ikke overstige 100
validation.productRequestDTO.availabilityPercentage.decimalMin=Tilgængelighedsprocenten må ikke være negativ
validation.productRequestDTO.availabilityPercentage.digits=Procenten må maksimalt have 3 heltal og 2 decimaler
validation.productRequestDTO.currentStock.decimalMin=Beholdningen må ikke være negativ
validation.productRequestDTO.currentStock.digits=Beholdningen må maksimalt have 10 heltal og 3 decimaler
validation.productRequestDTO.currentStock.notNull=Den aktuelle beholdning er påkrævet
validation.productRequestDTO.minimumStock.decimalMin=Minimumsbeholdning må ikke være negativ
validation.productRequestDTO.minimumStock.digits=Minimumsbeholdning må maksimalt have 10 heltal og 3 decimaler
validation.productRequestDTO.minimumStock.notNull=Minimumsbeholdning er påkrævet
validation.productRequestDTO.name.notBlank=Produktnavnet er påkrævet
validation.productRequestDTO.name.size=Skal være mellem 2 og 100 tegn
validation.productRequestDTO.productCode.notBlank=Produktkoden er påkrævet
validation.productRequestDTO.productCode.size=Koden må ikke overstige 50 tegn
validation.productRequestDTO.unit.notBlank=Måleenheden er påkrævet
validation.productRequestDTO.unit.size=Enheden må ikke overstige 20 tegn
validation.productRequestDTO.unitPrice.decimalMin=Prisen skal være større end nul
validation.productRequestDTO.unitPrice.digits=Prisen må maksimalt have 10 heltal og 2 decimaler
validation.productRequestDTO.unitPrice.notNull=Enhedsprisen er påkrævet
validation.recipe.elaboration.size=Tilberedningen må ikke overstige 2000 tegn
validation.recipe.name.notBlank=Opskriftsnavnet er påkrævet
validation.recipe.name.size=Skal være mellem 2 og 150 tegn
validation.recipe.presentation.size=Præsentationen må ikke overstige 1000 tegn
validation.recipe.totalCost.decimalMin=Omkostningerne må ikke være negative
validation.recipeAudit.action.notBlank=Handlingen er påkrævet
validation.recipeAudit.details.size=Detaljerne må ikke overstige 1000 tegn
validation.recipeComponent.parentRecipe.notNull=Opskriften er påkrævet
validation.recipeComponent.product.notNull=Produktet er påkrævet
validation.recipeComponent.quantity.decimalMin=Mængden skal være større end 0
validation.recipeComponent.quantity.notNull=Mængden er påkrævet
validation.recipeComponentRequestDTO.productId.notNull=Produkt-ID er påkrævet
validation.recipeComponentRequestDTO.quantity.decimalMin=Mængden skal være større end nul
validation.recipeComponentRequestDTO.quantity.digits=Mængden må maksimalt have 10 heltal og 3 decimaler
validation.recipeComponentRequestDTO.quantity.notNull=Mængden er påkrævet
validation.recipeCookingAudit.details.size=Detaljerne må ikke overstige 1000 tegn
validation.recipeCookingAudit.quantityCooked.decimalMin=Mængden skal være større end 0
validation.recipeCookingAudit.quantityCooked.notNull=Den tilberedte mængde er påkrævet
validation.recipeCookingAudit.recipe.notNull=Opskriften er påkrævet
validation.recipeCookingRequestDTO.details.size=Detaljerne må ikke overstige 500 tegn
validation.recipeCookingRequestDTO.quantity.decimalMin=Mængden skal være større end 0
validation.recipeCookingRequestDTO.quantity.digits=Mængden må maksimalt have 10 heltal og 3 decimaler
validation.recipeCookingRequestDTO.quantity.notNull=Mængden til tilberedning er påkrævet
validation.recipeCookingRequestDTO.recipeId.notNull=Opskrift-ID er påkrævet
validation.recipeCookingRequestDTO.recipeId.positive=Opskrift-ID skal være positivt
validation.recipeRequestDTO.components.notEmpty=Opskriften skal indeholde mindst én komponent
validation.recipeRequestDTO.elaboration.notBlank=Tilberedningen er påkrævet
validation.recipeRequestDTO.elaboration.size=Tilberedningen må ikke overstige 2000 tegn
validation.recipeRequestDTO.name.notBlank=Opskriftsnavnet er påkrævet
validation.recipeRequestDTO.name.size=Skal være mellem 2 og 150 tegn
validation.recipeRequestDTO.presentation.notBlank=Præsentationen er påkrævet
validation.recipeRequestDTO.presentation.size=Præsentationen må ikke overstige 1000 tegn
validation.roleEscalationRequestDTO.durationMinutes.max=Maksimal tilladt varighed er 1440 minutter (24 timer)
validation.roleEscalationRequestDTO.durationMinutes.min=Minimumsvarighed skal være 1 minut
validation.roleEscalationRequestDTO.durationMinutes.notNull=Varigheden i minutter er påkrævet
validation.stockLedger.currentHash.notBlank=Nuværende hash er påkrævet
validation.stockLedger.movementType.notNull=Bevægelsestypen er påkrævet
validation.stockLedger.previousHash.notBlank=Tidligere hash er påkrævet
validation.stockLedger.product.notNull=Produktet er påkrævet
validation.stockLedger.quantityDelta.notNull=Mængden er påkrævet
validation.stockLedger.resultingStock.notNull=Resulterende beholdning er påkrævet
validation.stockLedger.sequenceNumber.notNull=Sekvensnummeret er påkrævet
validation.stockLedger.transactionTimestamp.notNull=Tidsstemplet er påkrævet
validation.stockMovementItemDTO.description.size=Beskrivelsen må ikke overstige 500 tegn
validation.stockMovementItemDTO.movementType.notNull=Bevægelsestypen er påkrævet
validation.stockMovementItemDTO.productId.notNull=Produkt-ID er påkrævet
validation.stockMovementItemDTO.quantityDelta.digits=Mængden må maksimalt have 10 heltal og 3 decimaler
validation.stockMovementItemDTO.quantityDelta.notNull=Mængden er påkrævet
validation.stockSnapshot.currentStock.notNull=Den aktuelle beholdning er påkrævet
validation.stockSnapshot.integrityStatus.notBlank=Integritetsstatus er påkrævet
validation.stockSnapshot.lastSequenceNumber.notNull=Sekvensnummeret er påkrævet
validation.stockSnapshot.lastTransactionHash.notBlank=Seneste hash er påkrævet
validation.stockSnapshot.lastUpdated.notNull=Opdateringsdatoen er påkrævet
validation.supplier.name.notBlank=Leverandørnavnet er påkrævet
validation.supplier.name.size=Skal være mellem 2 og 100 tegn
validation.supplierRequestDTO.name.notBlank=Leverandørnavnet er påkrævet
validation.supplierRequestDTO.name.size=Skal være mellem 2 og 100 tegn
validation.user.name.notBlank=Navnet er påkrævet
validation.user.name.size=Skal være mellem 2 og 100 tegn
validation.user.password.notBlank=Adgangskoden er påkrævet
validation.user.role.notNull=Rollen er påkrævet
validation.user.user.notBlank=Brugernavnet er påkrævet
validation.userRequestDTO.name.notBlank=Navnet er påkrævet
validation.userRequestDTO.name.size=Skal være mellem 2 og 100 tegn
validation.userRequestDTO.password.notBlank=Adgangskoden er påkrævet
validation.userRequestDTO.password.size=Adgangskoden skal være mindst 6 tegn
validation.userRequestDTO.user.notBlank=Brugernavnet er påkrævet
validation.userRequestDTO.user.size=Brugernavnet må ikke overstige 100 tegn
""",

"fi": """validation.allergen.name.notBlank=Allergeenin nimi on pakollinen
validation.allergen.name.size=Tulee olla 2–50 merkkiä
validation.allergenRequestDTO.name.notBlank=Allergeenin nimi on pakollinen
validation.allergenRequestDTO.name.size=Tulee olla 2–50 merkkiä
validation.batchStockMovementRequestDTO.movements.notEmpty=Vähintään yksi liike on sisällytettävä
validation.batchStockMovementRequestDTO.reason.size=Syy ei saa ylittää 1000 merkkiä
validation.changePasswordRequestDTO.newPassword.notBlank=Uusi salasana on pakollinen
validation.changePasswordRequestDTO.newPassword.size=Uuden salasanan on oltava vähintään 6 merkkiä
validation.inventoryAudit.actionDescription.size=Kuvaus ei saa ylittää 500 merkkiä
validation.inventoryAudit.product.notNull=Tuote on pakollinen
validation.inventoryAudit.quantity.notNull=Määrä on pakollinen
validation.inventoryAudit.unknown.notBlank=Liiketyyppi on pakollinen
validation.inventoryMovementRequestDTO.movementType.notNull=Liiketyyppi on pakollinen
validation.inventoryMovementRequestDTO.productId.notNull=Tuotteen tunnus on pakollinen
validation.inventoryMovementRequestDTO.quantity.decimalMax=Määrä ei saa ylittää 9.999.999,99
validation.inventoryMovementRequestDTO.quantity.notNull=Määrä on pakollinen
validation.inventoryMovementRequestDTO.quantity.positive=Määrän on oltava suurempi kuin nolla
validation.inventoryMovementRequestDTO.userId.notNull=Käyttäjän tunnus on pakollinen
validation.jwtProperties.expiration.positive=JWT-vanhenemisen on oltava positiivinen arvo
validation.jwtProperties.secret.notBlank=JWT-salaisuus on pakollinen
validation.loginRequestDTO.name.notBlank=Käyttäjänimi on pakollinen
validation.loginRequestDTO.password.notBlank=Salasana on pakollinen
validation.order.orderDate.notNull=Tilauspäivä on pakollinen
validation.order.orderDate.pastOrPresent=Tilauspäivä ei saa olla tulevaisuudessa
validation.order.status.notBlank=Tila on pakollinen
validation.order.users.notNull=Käyttäjä on pakollinen
validation.orderAudit.action.notBlank=Toiminto on pakollinen
validation.orderAudit.details.size=Tiedot eivät saa ylittää 1000 merkkiä
validation.orderDetail.order.notNull=Tilaus on pakollinen
validation.orderDetail.product.notNull=Tuote on pakollinen
validation.orderDetail.quantity.decimalMin=Määrän on oltava suurempi kuin 0
validation.orderDetail.quantity.notNull=Pyydetty määrä on pakollinen
validation.orderDetail.quantityReceived.decimalMin=Vastaanotettu määrä ei saa olla negatiivinen
validation.orderDetailRequestDTO.productId.notNull=Tuotteen tunnus on pakollinen
validation.orderDetailRequestDTO.quantity.decimalMin=Määrän on oltava suurempi kuin nolla
validation.orderDetailRequestDTO.quantity.digits=Määrässä saa olla enintään 10 kokonaislukua ja 3 desimaalia
validation.orderDetailRequestDTO.quantity.notNull=Määrä on pakollinen
validation.orderReceptionDetailRequestDTO.productId.notNull=Tuotteen tunnus on pakollinen
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Vastaanotettu määrä on pakollinen
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Vastaanotetun määrän on oltava nolla tai suurempi
validation.orderReceptionRequestDTO.items.notEmpty=Vähintään yksi vastaanotettu tuote on määritettävä
validation.orderReceptionRequestDTO.orderId.notNull=Tilauksen tunnus on pakollinen
validation.orderReceptionRequestDTO.status.notNull=Tila on pakollinen
validation.orderRequestDTO.details.notEmpty=Tilauksessa on oltava vähintään yksi tieto
validation.orderRequestDTO.userId.notNull=Käyttäjän tunnus on pakollinen
validation.product.availabilityPercentage.decimalMax=Saatavuusprosentti ei saa ylittää 100
validation.product.availabilityPercentage.decimalMin=Saatavuusprosentti ei saa olla negatiivinen
validation.product.availabilityPercentage.digits=Virheellinen saatavuusmuoto
validation.product.currentStock.decimalMin=Varasto ei saa olla negatiivinen
validation.product.currentStock.digits=Virheellinen varastomuoto
validation.product.currentStock.notNull=Nykyinen varasto on pakollinen
validation.product.minimumStock.decimalMin=Minimivarasto ei saa olla negatiivinen
validation.product.minimumStock.digits=Virheellinen minimivarastomuoto
validation.product.name.notBlank=Tuotteen nimi on pakollinen
validation.product.name.size=Tulee olla 2–100 merkkiä
validation.product.productCode.notBlank=Tuotekoodi on pakollinen
validation.product.unit.notBlank=Mittayksikkö on pakollinen
validation.product.unitPrice.decimalMin=Hinnan on oltava suurempi kuin 0
validation.product.unitPrice.digits=Virheellinen hintamuoto
validation.product.unitPrice.notNull=Yksikköhinta on pakollinen
validation.productRequestDTO.availabilityPercentage.decimalMax=Saatavuusprosentti ei saa ylittää 100
validation.productRequestDTO.availabilityPercentage.decimalMin=Saatavuusprosentti ei saa olla negatiivinen
validation.productRequestDTO.availabilityPercentage.digits=Prosentissa saa olla enintään 3 kokonaislukua ja 2 desimaalia
validation.productRequestDTO.currentStock.decimalMin=Varasto ei saa olla negatiivinen
validation.productRequestDTO.currentStock.digits=Varastossa saa olla enintään 10 kokonaislukua ja 3 desimaalia
validation.productRequestDTO.currentStock.notNull=Nykyinen varasto on pakollinen
validation.productRequestDTO.minimumStock.decimalMin=Minimivarasto ei saa olla negatiivinen
validation.productRequestDTO.minimumStock.digits=Minimivarastossa saa olla enintään 10 kokonaislukua ja 3 desimaalia
validation.productRequestDTO.minimumStock.notNull=Minimivarasto on pakollinen
validation.productRequestDTO.name.notBlank=Tuotteen nimi on pakollinen
validation.productRequestDTO.name.size=Tulee olla 2–100 merkkiä
validation.productRequestDTO.productCode.notBlank=Tuotekoodi on pakollinen
validation.productRequestDTO.productCode.size=Koodi ei saa ylittää 50 merkkiä
validation.productRequestDTO.unit.notBlank=Mittayksikkö on pakollinen
validation.productRequestDTO.unit.size=Yksikkö ei saa ylittää 20 merkkiä
validation.productRequestDTO.unitPrice.decimalMin=Hinnan on oltava suurempi kuin nolla
validation.productRequestDTO.unitPrice.digits=Hinnassa saa olla enintään 10 kokonaislukua ja 2 desimaalia
validation.productRequestDTO.unitPrice.notNull=Yksikköhinta on pakollinen
validation.recipe.elaboration.size=Valmistus ei saa ylittää 2000 merkkiä
validation.recipe.name.notBlank=Reseptin nimi on pakollinen
validation.recipe.name.size=Tulee olla 2–150 merkkiä
validation.recipe.presentation.size=Esitys ei saa ylittää 1000 merkkiä
validation.recipe.totalCost.decimalMin=Kustannus ei saa olla negatiivinen
validation.recipeAudit.action.notBlank=Toiminto on pakollinen
validation.recipeAudit.details.size=Tiedot eivät saa ylittää 1000 merkkiä
validation.recipeComponent.parentRecipe.notNull=Resepti on pakollinen
validation.recipeComponent.product.notNull=Tuote on pakollinen
validation.recipeComponent.quantity.decimalMin=Määrän on oltava suurempi kuin 0
validation.recipeComponent.quantity.notNull=Määrä on pakollinen
validation.recipeComponentRequestDTO.productId.notNull=Tuotteen tunnus on pakollinen
validation.recipeComponentRequestDTO.quantity.decimalMin=Määrän on oltava suurempi kuin nolla
validation.recipeComponentRequestDTO.quantity.digits=Määrässä saa olla enintään 10 kokonaislukua ja 3 desimaalia
validation.recipeComponentRequestDTO.quantity.notNull=Määrä on pakollinen
validation.recipeCookingAudit.details.size=Tiedot eivät saa ylittää 1000 merkkiä
validation.recipeCookingAudit.quantityCooked.decimalMin=Määrän on oltava suurempi kuin 0
validation.recipeCookingAudit.quantityCooked.notNull=Valmistettu määrä on pakollinen
validation.recipeCookingAudit.recipe.notNull=Resepti on pakollinen
validation.recipeCookingRequestDTO.details.size=Tiedot eivät saa ylittää 500 merkkiä
validation.recipeCookingRequestDTO.quantity.decimalMin=Määrän on oltava suurempi kuin 0
validation.recipeCookingRequestDTO.quantity.digits=Määrässä saa olla enintään 10 kokonaislukua ja 3 desimaalia
validation.recipeCookingRequestDTO.quantity.notNull=Valmistettava määrä on pakollinen
validation.recipeCookingRequestDTO.recipeId.notNull=Reseptin tunnus on pakollinen
validation.recipeCookingRequestDTO.recipeId.positive=Reseptin tunnuksen on oltava positiivinen
validation.recipeRequestDTO.components.notEmpty=Reseptin on sisällettävä vähintään yksi komponentti
validation.recipeRequestDTO.elaboration.notBlank=Valmistus on pakollinen
validation.recipeRequestDTO.elaboration.size=Valmistus ei saa ylittää 2000 merkkiä
validation.recipeRequestDTO.name.notBlank=Reseptin nimi on pakollinen
validation.recipeRequestDTO.name.size=Tulee olla 2–150 merkkiä
validation.recipeRequestDTO.presentation.notBlank=Esitys on pakollinen
validation.recipeRequestDTO.presentation.size=Esitys ei saa ylittää 1000 merkkiä
validation.roleEscalationRequestDTO.durationMinutes.max=Suurin sallittu kesto on 1440 minuuttia (24 tuntia)
validation.roleEscalationRequestDTO.durationMinutes.min=Vähimmäiskeston on oltava 1 minuutti
validation.roleEscalationRequestDTO.durationMinutes.notNull=Kesto minuutteina on pakollinen
validation.stockLedger.currentHash.notBlank=Nykyinen tiiviste on pakollinen
validation.stockLedger.movementType.notNull=Liiketyyppi on pakollinen
validation.stockLedger.previousHash.notBlank=Edellinen tiiviste on pakollinen
validation.stockLedger.product.notNull=Tuote on pakollinen
validation.stockLedger.quantityDelta.notNull=Määrä on pakollinen
validation.stockLedger.resultingStock.notNull=Tuloksena oleva varasto on pakollinen
validation.stockLedger.sequenceNumber.notNull=Järjestysnumero on pakollinen
validation.stockLedger.transactionTimestamp.notNull=Aikaleima on pakollinen
validation.stockMovementItemDTO.description.size=Kuvaus ei saa ylittää 500 merkkiä
validation.stockMovementItemDTO.movementType.notNull=Liiketyyppi on pakollinen
validation.stockMovementItemDTO.productId.notNull=Tuotteen tunnus on pakollinen
validation.stockMovementItemDTO.quantityDelta.digits=Määrässä saa olla enintään 10 kokonaislukua ja 3 desimaalia
validation.stockMovementItemDTO.quantityDelta.notNull=Määrä on pakollinen
validation.stockSnapshot.currentStock.notNull=Nykyinen varasto on pakollinen
validation.stockSnapshot.integrityStatus.notBlank=Eheystila on pakollinen
validation.stockSnapshot.lastSequenceNumber.notNull=Järjestysnumero on pakollinen
validation.stockSnapshot.lastTransactionHash.notBlank=Viimeisin tiiviste on pakollinen
validation.stockSnapshot.lastUpdated.notNull=Päivityspäivämäärä on pakollinen
validation.supplier.name.notBlank=Toimittajan nimi on pakollinen
validation.supplier.name.size=Tulee olla 2–100 merkkiä
validation.supplierRequestDTO.name.notBlank=Toimittajan nimi on pakollinen
validation.supplierRequestDTO.name.size=Tulee olla 2–100 merkkiä
validation.user.name.notBlank=Nimi on pakollinen
validation.user.name.size=Tulee olla 2–100 merkkiä
validation.user.password.notBlank=Salasana on pakollinen
validation.user.role.notNull=Rooli on pakollinen
validation.user.user.notBlank=Käyttäjänimi on pakollinen
validation.userRequestDTO.name.notBlank=Nimi on pakollinen
validation.userRequestDTO.name.size=Tulee olla 2–100 merkkiä
validation.userRequestDTO.password.notBlank=Salasana on pakollinen
validation.userRequestDTO.password.size=Salasanan on oltava vähintään 6 merkkiä
validation.userRequestDTO.user.notBlank=Käyttäjänimi on pakollinen
validation.userRequestDTO.user.size=Käyttäjänimi ei saa ylittää 100 merkkiä
""",

"pl": """validation.allergen.name.notBlank=Nazwa alergenu jest wymagana
validation.allergen.name.size=Musi mieć od 2 do 50 znaków
validation.allergenRequestDTO.name.notBlank=Nazwa alergenu jest wymagana
validation.allergenRequestDTO.name.size=Musi mieć od 2 do 50 znaków
validation.batchStockMovementRequestDTO.movements.notEmpty=Należy uwzględnić co najmniej jeden ruch
validation.batchStockMovementRequestDTO.reason.size=Powód nie może przekraczać 1000 znaków
validation.changePasswordRequestDTO.newPassword.notBlank=Nowe hasło jest wymagane
validation.changePasswordRequestDTO.newPassword.size=Nowe hasło musi mieć co najmniej 6 znaków
validation.inventoryAudit.actionDescription.size=Opis nie może przekraczać 500 znaków
validation.inventoryAudit.product.notNull=Produkt jest wymagany
validation.inventoryAudit.quantity.notNull=Ilość jest wymagana
validation.inventoryAudit.unknown.notBlank=Typ ruchu jest wymagany
validation.inventoryMovementRequestDTO.movementType.notNull=Typ ruchu jest wymagany
validation.inventoryMovementRequestDTO.productId.notNull=ID produktu jest wymagane
validation.inventoryMovementRequestDTO.quantity.decimalMax=Ilość nie może przekraczać 9.999.999,99
validation.inventoryMovementRequestDTO.quantity.notNull=Ilość jest wymagana
validation.inventoryMovementRequestDTO.quantity.positive=Ilość musi być większa niż zero
validation.inventoryMovementRequestDTO.userId.notNull=ID użytkownika jest wymagane
validation.jwtProperties.expiration.positive=Czas wygaśnięcia JWT musi być wartością dodatnią
validation.jwtProperties.secret.notBlank=Sekret JWT jest wymagany
validation.loginRequestDTO.name.notBlank=Nazwa użytkownika jest wymagana
validation.loginRequestDTO.password.notBlank=Hasło jest wymagane
validation.order.orderDate.notNull=Data zamówienia jest wymagana
validation.order.orderDate.pastOrPresent=Data zamówienia nie może być z przyszłości
validation.order.status.notBlank=Status jest wymagany
validation.order.users.notNull=Użytkownik jest wymagany
validation.orderAudit.action.notBlank=Akcja jest wymagana
validation.orderAudit.details.size=Szczegóły nie mogą przekraczać 1000 znaków
validation.orderDetail.order.notNull=Zamówienie jest wymagane
validation.orderDetail.product.notNull=Produkt jest wymagany
validation.orderDetail.quantity.decimalMin=Ilość musi być większa niż 0
validation.orderDetail.quantity.notNull=Ządana ilość jest wymagana
validation.orderDetail.quantityReceived.decimalMin=Otrzymana ilość nie może być ujemna
validation.orderDetailRequestDTO.productId.notNull=ID produktu jest wymagane
validation.orderDetailRequestDTO.quantity.decimalMin=Ilość musi być większa niż zero
validation.orderDetailRequestDTO.quantity.digits=Ilość może mieć maksymalnie 10 cyfr całkowitych i 3 dziesiętne
validation.orderDetailRequestDTO.quantity.notNull=Ilość jest wymagana
validation.orderReceptionDetailRequestDTO.productId.notNull=ID produktu jest wymagane
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Otrzymana ilość jest wymagana
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Otrzymana ilość musi być równa lub większa od zera
validation.orderReceptionRequestDTO.items.notEmpty=Należy określić co najmniej jeden odebrany produkt
validation.orderReceptionRequestDTO.orderId.notNull=ID zamówienia jest wymagane
validation.orderReceptionRequestDTO.status.notNull=Status jest wymagany
validation.orderRequestDTO.details.notEmpty=Zamówienie musi mieć co najmniej jeden szczegół
validation.orderRequestDTO.userId.notNull=ID użytkownika jest wymagane
validation.product.availabilityPercentage.decimalMax=Procent dostępności nie może przekraczać 100
validation.product.availabilityPercentage.decimalMin=Procent dostępności nie może być ujemny
validation.product.availabilityPercentage.digits=Nieprawidłowy format dostępności
validation.product.currentStock.decimalMin=Stan magazynowy nie może być ujemny
validation.product.currentStock.digits=Nieprawidłowy format stanu magazynowego
validation.product.currentStock.notNull=Obecny stan magazynowy jest wymagany
validation.product.minimumStock.decimalMin=Minimalny stan magazynowy nie może być ujemny
validation.product.minimumStock.digits=Nieprawidłowy format minimalnego stanu
validation.product.name.notBlank=Nazwa produktu jest wymagana
validation.product.name.size=Musi mieć od 2 do 100 znaków
validation.product.productCode.notBlank=Kod produktu jest wymagany
validation.product.unit.notBlank=Jednostka miary jest wymagana
validation.product.unitPrice.decimalMin=Cena musi być większa niż 0
validation.product.unitPrice.digits=Nieprawidłowy format ceny
validation.product.unitPrice.notNull=Cena jednostkowa jest wymagana
validation.productRequestDTO.availabilityPercentage.decimalMax=Procent dostępności nie może przekraczać 100
validation.productRequestDTO.availabilityPercentage.decimalMin=Procent dostępności nie może być ujemny
validation.productRequestDTO.availabilityPercentage.digits=Procent może mieć maksymalnie 3 cyfry całkowite i 2 dziesiętne
validation.productRequestDTO.currentStock.decimalMin=Stan magazynowy nie może być ujemny
validation.productRequestDTO.currentStock.digits=Stan magazynowy może mieć maksymalnie 10 cyfr całkowitych i 3 dziesiętne
validation.productRequestDTO.currentStock.notNull=Obecny stan magazynowy jest wymagany
validation.productRequestDTO.minimumStock.decimalMin=Minimalny stan magazynowy nie może być ujemny
validation.productRequestDTO.minimumStock.digits=Minimalny stan magazynowy może mieć maksymalnie 10 cyfr całkowitych i 3 dziesiętne
validation.productRequestDTO.minimumStock.notNull=Minimalny stan magazynowy jest wymagany
validation.productRequestDTO.name.notBlank=Nazwa produktu jest wymagana
validation.productRequestDTO.name.size=Musi mieć od 2 do 100 znaków
validation.productRequestDTO.productCode.notBlank=Kod produktu jest wymagany
validation.productRequestDTO.productCode.size=Kod nie może przekraczać 50 znaków
validation.productRequestDTO.unit.notBlank=Jednostka miary jest wymagana
validation.productRequestDTO.unit.size=Jednostka nie może przekraczać 20 znaków
validation.productRequestDTO.unitPrice.decimalMin=Cena musi być większa niż zero
validation.productRequestDTO.unitPrice.digits=Cena może mieć maksymalnie 10 cyfr całkowitych i 2 dziesiętne
validation.productRequestDTO.unitPrice.notNull=Cena jednostkowa jest wymagana
validation.recipe.elaboration.size=Przygotowanie nie może przekraczać 2000 znaków
validation.recipe.name.notBlank=Nazwa przepisu jest wymagana
validation.recipe.name.size=Musi mieć od 2 do 150 znaków
validation.recipe.presentation.size=Prezentacja nie może przekraczać 1000 znaków
validation.recipe.totalCost.decimalMin=Koszt nie może być ujemny
validation.recipeAudit.action.notBlank=Akcja jest wymagana
validation.recipeAudit.details.size=Szczegóły nie mogą przekraczać 1000 znaków
validation.recipeComponent.parentRecipe.notNull=Przepis jest wymagany
validation.recipeComponent.product.notNull=Produkt jest wymagany
validation.recipeComponent.quantity.decimalMin=Ilość musi być większa niż 0
validation.recipeComponent.quantity.notNull=Ilość jest wymagana
validation.recipeComponentRequestDTO.productId.notNull=ID produktu jest wymagane
validation.recipeComponentRequestDTO.quantity.decimalMin=Ilość musi być większa niż zero
validation.recipeComponentRequestDTO.quantity.digits=Ilość może mieć maksymalnie 10 cyfr całkowitych i 3 dziesiętne
validation.recipeComponentRequestDTO.quantity.notNull=Ilość jest wymagana
validation.recipeCookingAudit.details.size=Szczegóły nie mogą przekraczać 1000 znaków
validation.recipeCookingAudit.quantityCooked.decimalMin=Ilość musi być większa niż 0
validation.recipeCookingAudit.quantityCooked.notNull=Ugotowana ilość jest wymagana
validation.recipeCookingAudit.recipe.notNull=Przepis jest wymagany
validation.recipeCookingRequestDTO.details.size=Szczegóły nie mogą przekraczać 500 znaków
validation.recipeCookingRequestDTO.quantity.decimalMin=Ilość musi być większa niż 0
validation.recipeCookingRequestDTO.quantity.digits=Ilość może mieć maksymalnie 10 cyfr całkowitych i 3 dziesiętne
validation.recipeCookingRequestDTO.quantity.notNull=Ilość do ugotowania jest wymagana
validation.recipeCookingRequestDTO.recipeId.notNull=ID przepisu jest wymagane
validation.recipeCookingRequestDTO.recipeId.positive=ID przepisu musi być dodatnie
validation.recipeRequestDTO.components.notEmpty=Przepis musi zawierać co najmniej jeden składnik
validation.recipeRequestDTO.elaboration.notBlank=Przygotowanie jest wymagane
validation.recipeRequestDTO.elaboration.size=Przygotowanie nie może przekraczać 2000 znaków
validation.recipeRequestDTO.name.notBlank=Nazwa przepisu jest wymagana
validation.recipeRequestDTO.name.size=Musi mieć od 2 do 150 znaków
validation.recipeRequestDTO.presentation.notBlank=Prezentacja jest wymagana
validation.recipeRequestDTO.presentation.size=Prezentacja nie może przekraczać 1000 znaków
validation.roleEscalationRequestDTO.durationMinutes.max=Maksymalny dozwolony czas trwania to 1440 minut (24 godziny)
validation.roleEscalationRequestDTO.durationMinutes.min=Minimalny czas trwania musi wynosić 1 minutę
validation.roleEscalationRequestDTO.durationMinutes.notNull=Czas trwania w minutach jest wymagany
validation.stockLedger.currentHash.notBlank=Obecny hash jest wymagany
validation.stockLedger.movementType.notNull=Typ ruchu jest wymagany
validation.stockLedger.previousHash.notBlank=Poprzedni hash jest wymagany
validation.stockLedger.product.notNull=Produkt jest wymagany
validation.stockLedger.quantityDelta.notNull=Ilość jest wymagana
validation.stockLedger.resultingStock.notNull=Wynikowy stan magazynowy jest wymagany
validation.stockLedger.sequenceNumber.notNull=Numer sekwencyjny jest wymagany
validation.stockLedger.transactionTimestamp.notNull=Sygnatura czasowa jest wymagana
validation.stockMovementItemDTO.description.size=Opis nie może przekraczać 500 znaków
validation.stockMovementItemDTO.movementType.notNull=Typ ruchu jest wymagany
validation.stockMovementItemDTO.productId.notNull=ID produktu jest wymagane
validation.stockMovementItemDTO.quantityDelta.digits=Ilość może mieć maksymalnie 10 cyfr całkowitych i 3 dziesiętne
validation.stockMovementItemDTO.quantityDelta.notNull=Ilość jest wymagana
validation.stockSnapshot.currentStock.notNull=Obecny stan magazynowy jest wymagany
validation.stockSnapshot.integrityStatus.notBlank=Status integralności jest wymagany
validation.stockSnapshot.lastSequenceNumber.notNull=Numer sekwencyjny jest wymagany
validation.stockSnapshot.lastTransactionHash.notBlank=Ostatni hash jest wymagany
validation.stockSnapshot.lastUpdated.notNull=Data aktualizacji jest wymagana
validation.supplier.name.notBlank=Nazwa dostawcy jest wymagana
validation.supplier.name.size=Musi mieć od 2 do 100 znaków
validation.supplierRequestDTO.name.notBlank=Nazwa dostawcy jest wymagana
validation.supplierRequestDTO.name.size=Musi mieć od 2 do 100 znaków
validation.user.name.notBlank=Imię jest wymagane
validation.user.name.size=Musi mieć od 2 do 100 znaków
validation.user.password.notBlank=Hasło jest wymagane
validation.user.role.notNull=Rola jest wymagana
validation.user.user.notBlank=Nazwa użytkownika jest wymagana
validation.userRequestDTO.name.notBlank=Imię jest wymagane
validation.userRequestDTO.name.size=Musi mieć od 2 do 100 znaków
validation.userRequestDTO.password.notBlank=Hasło jest wymagane
validation.userRequestDTO.password.size=Hasło musi mieć co najmniej 6 znaków
validation.userRequestDTO.user.notBlank=Nazwa użytkownika jest wymagana
validation.userRequestDTO.user.size=Nazwa użytkownika nie może przekraczać 100 znaków
"""
}

for lang, content in FILES.items():
    path = os.path.join(VDIR, f"ValidationMessages_{lang}.properties")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content.strip() + "\n")
    lines = [l for l in content.strip().split("\n") if "=" in l]
    print(f"  {lang}: wrote {len(lines)} keys")
