#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Writes CS, SK, HU, RO ValidationMessages files."""
import os
VDIR = "src/main/resources/i18n/validation/"
FILES = {
"cs": """validation.allergen.name.notBlank=Název alergenu je povinný
validation.allergen.name.size=Musí mít mezi 2 a 50 znaky
validation.allergenRequestDTO.name.notBlank=Název alergenu je povinný
validation.allergenRequestDTO.name.size=Musí mít mezi 2 a 50 znaky
validation.batchStockMovementRequestDTO.movements.notEmpty=Musí být zahrnut alespoň jeden pohyb
validation.batchStockMovementRequestDTO.reason.size=Důvod nesmí přesáhnout 1000 znaků
validation.changePasswordRequestDTO.newPassword.notBlank=Nové heslo je povinné
validation.changePasswordRequestDTO.newPassword.size=Nové heslo musí mít alespoň 6 znaků
validation.inventoryAudit.actionDescription.size=Popis nesmí přesáhnout 500 znaků
validation.inventoryAudit.product.notNull=Produkt je povinný
validation.inventoryAudit.quantity.notNull=Množství je povinné
validation.inventoryAudit.unknown.notBlank=Typ pohybu je povinný
validation.inventoryMovementRequestDTO.movementType.notNull=Typ pohybu je povinný
validation.inventoryMovementRequestDTO.productId.notNull=ID produktu je povinné
validation.inventoryMovementRequestDTO.quantity.decimalMax=Množství nesmí přesáhnout 9 999 999,99
validation.inventoryMovementRequestDTO.quantity.notNull=Množství je povinné
validation.inventoryMovementRequestDTO.quantity.positive=Množství musí být větší než nula
validation.inventoryMovementRequestDTO.userId.notNull=ID uživatele je povinné
validation.jwtProperties.expiration.positive=Platnost JWT musí být kladná hodnota
validation.jwtProperties.secret.notBlank=Tajemství JWT je povinné
validation.loginRequestDTO.name.notBlank=Uživatelské jméno je povinné
validation.loginRequestDTO.password.notBlank=Heslo je povinné
validation.order.orderDate.notNull=Datum objednávky je povinné
validation.order.orderDate.pastOrPresent=Datum objednávky nesmí být v budoucnosti
validation.order.status.notBlank=Stav je povinný
validation.order.users.notNull=Uživatel je povinný
validation.orderAudit.action.notBlank=Akce je povinná
validation.orderAudit.details.size=Podrobnosti nesmí přesáhnout 1000 znaků
validation.orderDetail.order.notNull=Objednávka je povinná
validation.orderDetail.product.notNull=Produkt je povinný
validation.orderDetail.quantity.decimalMin=Množství musí být větší než 0
validation.orderDetail.quantity.notNull=Požadované množství je povinné
validation.orderDetail.quantityReceived.decimalMin=Přijaté množství nesmí být záporné
validation.orderDetailRequestDTO.productId.notNull=ID produktu je povinné
validation.orderDetailRequestDTO.quantity.decimalMin=Množství musí být větší než nula
validation.orderDetailRequestDTO.quantity.digits=Množství může mít maximálně 10 celých čísel a 3 desetinná místa
validation.orderDetailRequestDTO.quantity.notNull=Množství je povinné
validation.orderReceptionDetailRequestDTO.productId.notNull=ID produktu je povinné
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Přijaté množství je povinné
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Přijaté množství musí být nula nebo větší
validation.orderReceptionRequestDTO.items.notEmpty=Musí být uveden alespoň jeden přijatý produkt
validation.orderReceptionRequestDTO.orderId.notNull=ID objednávky je povinné
validation.orderReceptionRequestDTO.status.notNull=Stav je povinný
validation.orderRequestDTO.details.notEmpty=Objednávka musí mít alespoň jeden detail
validation.orderRequestDTO.userId.notNull=ID uživatele je povinné
validation.product.availabilityPercentage.decimalMax=Procento dostupnosti nesmí přesáhnout 100
validation.product.availabilityPercentage.decimalMin=Procento dostupnosti nesmí být záporné
validation.product.availabilityPercentage.digits=Neplatný formát dostupnosti
validation.product.currentStock.decimalMin=Zásoba nesmí být záporná
validation.product.currentStock.digits=Neplatný formát zásoby
validation.product.currentStock.notNull=Aktuální zásoba je povinná
validation.product.minimumStock.decimalMin=Minimální zásoba nesmí být záporná
validation.product.minimumStock.digits=Neplatný formát minimální zásoby
validation.product.name.notBlank=Název produktu je povinný
validation.product.name.size=Musí mít mezi 2 a 100 znaky
validation.product.productCode.notBlank=Kód produktu je povinný
validation.product.unit.notBlank=Měrná jednotka je povinná
validation.product.unitPrice.decimalMin=Cena musí být větší než 0
validation.product.unitPrice.digits=Neplatný formát ceny
validation.product.unitPrice.notNull=Jednotková cena je povinná
validation.productRequestDTO.availabilityPercentage.decimalMax=Procento dostupnosti nesmí přesáhnout 100
validation.productRequestDTO.availabilityPercentage.decimalMin=Procento dostupnosti nesmí být záporné
validation.productRequestDTO.availabilityPercentage.digits=Procento může mít maximálně 3 celá čísla a 2 desetinná místa
validation.productRequestDTO.currentStock.decimalMin=Zásoba nesmí být záporná
validation.productRequestDTO.currentStock.digits=Zásoba může mít maximálně 10 celých čísel a 3 desetinná místa
validation.productRequestDTO.currentStock.notNull=Aktuální zásoba je povinná
validation.productRequestDTO.minimumStock.decimalMin=Minimální zásoba nesmí být záporná
validation.productRequestDTO.minimumStock.digits=Minimální zásoba může mít maximálně 10 celých čísel a 3 desetinná místa
validation.productRequestDTO.minimumStock.notNull=Minimální zásoba je povinná
validation.productRequestDTO.name.notBlank=Název produktu je povinný
validation.productRequestDTO.name.size=Musí mít mezi 2 a 100 znaky
validation.productRequestDTO.productCode.notBlank=Kód produktu je povinný
validation.productRequestDTO.productCode.size=Kód nesmí přesáhnout 50 znaků
validation.productRequestDTO.unit.notBlank=Měrná jednotka je povinná
validation.productRequestDTO.unit.size=Jednotka nesmí přesáhnout 20 znaků
validation.productRequestDTO.unitPrice.decimalMin=Cena musí být větší než nula
validation.productRequestDTO.unitPrice.digits=Cena může mít maximálně 10 celých čísel a 2 desetinná místa
validation.productRequestDTO.unitPrice.notNull=Jednotková cena je povinná
validation.recipe.elaboration.size=Příprava nesmí přesáhnout 2000 znaků
validation.recipe.name.notBlank=Název receptu je povinný
validation.recipe.name.size=Musí mít mezi 2 a 150 znaky
validation.recipe.presentation.size=Prezentace nesmí přesáhnout 1000 znaků
validation.recipe.totalCost.decimalMin=Cena nesmí být záporná
validation.recipeAudit.action.notBlank=Akce je povinná
validation.recipeAudit.details.size=Podrobnosti nesmí přesáhnout 1000 znaků
validation.recipeComponent.parentRecipe.notNull=Recept je povinný
validation.recipeComponent.product.notNull=Produkt je povinný
validation.recipeComponent.quantity.decimalMin=Množství musí být větší než 0
validation.recipeComponent.quantity.notNull=Množství je povinné
validation.recipeComponentRequestDTO.productId.notNull=ID produktu je povinné
validation.recipeComponentRequestDTO.quantity.decimalMin=Množství musí být větší než nula
validation.recipeComponentRequestDTO.quantity.digits=Množství může mít maximálně 10 celých čísel a 3 desetinná místa
validation.recipeComponentRequestDTO.quantity.notNull=Množství je povinné
validation.recipeCookingAudit.details.size=Podrobnosti nesmí přesáhnout 1000 znaků
validation.recipeCookingAudit.quantityCooked.decimalMin=Množství musí být větší než 0
validation.recipeCookingAudit.quantityCooked.notNull=Uvařené množství je povinné
validation.recipeCookingAudit.recipe.notNull=Recept je povinný
validation.recipeCookingRequestDTO.details.size=Podrobnosti nesmí přesáhnout 500 znaků
validation.recipeCookingRequestDTO.quantity.decimalMin=Množství musí být větší než 0
validation.recipeCookingRequestDTO.quantity.digits=Množství může mít maximálně 10 celých čísel a 3 desetinná místa
validation.recipeCookingRequestDTO.quantity.notNull=Množství k uvaření je povinné
validation.recipeCookingRequestDTO.recipeId.notNull=ID receptu je povinné
validation.recipeCookingRequestDTO.recipeId.positive=ID receptu musí být kladné
validation.recipeRequestDTO.components.notEmpty=Recept musí obsahovat alespoň jednu složku
validation.recipeRequestDTO.elaboration.notBlank=Příprava je povinná
validation.recipeRequestDTO.elaboration.size=Příprava nesmí přesáhnout 2000 znaků
validation.recipeRequestDTO.name.notBlank=Název receptu je povinný
validation.recipeRequestDTO.name.size=Musí mít mezi 2 a 150 znaky
validation.recipeRequestDTO.presentation.notBlank=Prezentace je povinná
validation.recipeRequestDTO.presentation.size=Prezentace nesmí přesáhnout 1000 znaků
validation.roleEscalationRequestDTO.durationMinutes.max=Maximální povolená doba je 1440 minut (24 hodin)
validation.roleEscalationRequestDTO.durationMinutes.min=Minimální doba musí být 1 minuta
validation.roleEscalationRequestDTO.durationMinutes.notNull=Doba v minutách je povinná
validation.stockLedger.currentHash.notBlank=Aktuální hash je povinný
validation.stockLedger.movementType.notNull=Typ pohybu je povinný
validation.stockLedger.previousHash.notBlank=Předchozí hash je povinný
validation.stockLedger.product.notNull=Produkt je povinný
validation.stockLedger.quantityDelta.notNull=Množství je povinné
validation.stockLedger.resultingStock.notNull=Výsledná zásoba je povinná
validation.stockLedger.sequenceNumber.notNull=Sekvenční číslo je povinné
validation.stockLedger.transactionTimestamp.notNull=Časové razítko je povinné
validation.stockMovementItemDTO.description.size=Popis nesmí přesáhnout 500 znaků
validation.stockMovementItemDTO.movementType.notNull=Typ pohybu je povinný
validation.stockMovementItemDTO.productId.notNull=ID produktu je povinné
validation.stockMovementItemDTO.quantityDelta.digits=Množství může mít maximálně 10 celých čísel a 3 desetinná místa
validation.stockMovementItemDTO.quantityDelta.notNull=Množství je povinné
validation.stockSnapshot.currentStock.notNull=Aktuální zásoba je povinná
validation.stockSnapshot.integrityStatus.notBlank=Stav integrity je povinný
validation.stockSnapshot.lastSequenceNumber.notNull=Sekvenční číslo je povinné
validation.stockSnapshot.lastTransactionHash.notBlank=Poslední hash je povinný
validation.stockSnapshot.lastUpdated.notNull=Datum aktualizace je povinné
validation.supplier.name.notBlank=Název dodavatele je povinný
validation.supplier.name.size=Musí mít mezi 2 a 100 znaky
validation.supplierRequestDTO.name.notBlank=Název dodavatele je povinný
validation.supplierRequestDTO.name.size=Musí mít mezi 2 a 100 znaky
validation.user.name.notBlank=Jméno je povinné
validation.user.name.size=Musí mít mezi 2 a 100 znaky
validation.user.password.notBlank=Heslo je povinné
validation.user.role.notNull=Role je povinná
validation.user.user.notBlank=Uživatelské jméno je povinné
validation.userRequestDTO.name.notBlank=Jméno je povinné
validation.userRequestDTO.name.size=Musí mít mezi 2 a 100 znaky
validation.userRequestDTO.password.notBlank=Heslo je povinné
validation.userRequestDTO.password.size=Heslo musí mít alespoň 6 znaků
validation.userRequestDTO.user.notBlank=Uživatelské jméno je povinné
validation.userRequestDTO.user.size=Uživatelské jméno nesmí přesáhnout 100 znaků
""",

"sk": """validation.allergen.name.notBlank=Názov alergénu je povinný
validation.allergen.name.size=Musí mať od 2 do 50 znakov
validation.allergenRequestDTO.name.notBlank=Názov alergénu je povinný
validation.allergenRequestDTO.name.size=Musí mať od 2 do 50 znakov
validation.batchStockMovementRequestDTO.movements.notEmpty=Musí byť zahrnutý aspoň jeden pohyb
validation.batchStockMovementRequestDTO.reason.size=Dôvod nesmie presiahnuť 1000 znakov
validation.changePasswordRequestDTO.newPassword.notBlank=Nové heslo je povinné
validation.changePasswordRequestDTO.newPassword.size=Nové heslo musí mať aspoň 6 znakov
validation.inventoryAudit.actionDescription.size=Popis nesmie presiahnuť 500 znakov
validation.inventoryAudit.product.notNull=Produkt je povinný
validation.inventoryAudit.quantity.notNull=Množstvo je povinné
validation.inventoryAudit.unknown.notBlank=Typ pohybu je povinný
validation.inventoryMovementRequestDTO.movementType.notNull=Typ pohybu je povinný
validation.inventoryMovementRequestDTO.productId.notNull=ID produktu je povinné
validation.inventoryMovementRequestDTO.quantity.decimalMax=Množstvo nesmie presiahnuť 9 999 999,99
validation.inventoryMovementRequestDTO.quantity.notNull=Množstvo je povinné
validation.inventoryMovementRequestDTO.quantity.positive=Množstvo musí byť väčšie ako nula
validation.inventoryMovementRequestDTO.userId.notNull=ID používateľa je povinné
validation.jwtProperties.expiration.positive=Exspirácia JWT musí byť kladná hodnota
validation.jwtProperties.secret.notBlank=Tajomstvo JWT je povinné
validation.loginRequestDTO.name.notBlank=Používateľské meno je povinné
validation.loginRequestDTO.password.notBlank=Heslo je povinné
validation.order.orderDate.notNull=Dátum objednávky je povinný
validation.order.orderDate.pastOrPresent=Dátum objednávky nesmie byť v budúcnosti
validation.order.status.notBlank=Stav je povinný
validation.order.users.notNull=Používateľ je povinný
validation.orderAudit.action.notBlank=Akcia je povinná
validation.orderAudit.details.size=Podrobnosti nesmú presiahnuť 1000 znakov
validation.orderDetail.order.notNull=Objednávka je povinná
validation.orderDetail.product.notNull=Produkt je povinný
validation.orderDetail.quantity.decimalMin=Množstvo musí byť väčšie ako 0
validation.orderDetail.quantity.notNull=Požadované množstvo je povinné
validation.orderDetail.quantityReceived.decimalMin=Prijaté množstvo nesmie byť záporné
validation.orderDetailRequestDTO.productId.notNull=ID produktu je povinné
validation.orderDetailRequestDTO.quantity.decimalMin=Množstvo musí byť väčšie ako nula
validation.orderDetailRequestDTO.quantity.digits=Množstvo môže mať maximálne 10 celých čísel a 3 desatinné miesta
validation.orderDetailRequestDTO.quantity.notNull=Množstvo je povinné
validation.orderReceptionDetailRequestDTO.productId.notNull=ID produktu je povinné
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Prijaté množstvo je povinné
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Prijaté množstvo musí byť nula alebo väčšie
validation.orderReceptionRequestDTO.items.notEmpty=Musí byť uvedený aspoň jeden prijatý produkt
validation.orderReceptionRequestDTO.orderId.notNull=ID objednávky je povinné
validation.orderReceptionRequestDTO.status.notNull=Stav je povinný
validation.orderRequestDTO.details.notEmpty=Objednávka musí mať aspoň jeden detail
validation.orderRequestDTO.userId.notNull=ID používateľa je povinné
validation.product.availabilityPercentage.decimalMax=Percento dostupnosti nesmie presiahnuť 100
validation.product.availabilityPercentage.decimalMin=Percento dostupnosti nesmie byť záporné
validation.product.availabilityPercentage.digits=Neplatný formát dostupnosti
validation.product.currentStock.decimalMin=Zásoba nesmie byť záporná
validation.product.currentStock.digits=Neplatný formát zásoby
validation.product.currentStock.notNull=Aktuálna zásoba je povinná
validation.product.minimumStock.decimalMin=Minimálna zásoba nesmie byť záporná
validation.product.minimumStock.digits=Neplatný formát minimálnej zásoby
validation.product.name.notBlank=Názov produktu je povinný
validation.product.name.size=Musí mať od 2 do 100 znakov
validation.product.productCode.notBlank=Kód produktu je povinný
validation.product.unit.notBlank=Merná jednotka je povinná
validation.product.unitPrice.decimalMin=Cena musí byť väčšia ako 0
validation.product.unitPrice.digits=Neplatný formát ceny
validation.product.unitPrice.notNull=Jednotková cena je povinná
validation.productRequestDTO.availabilityPercentage.decimalMax=Percento dostupnosti nesmie presiahnuť 100
validation.productRequestDTO.availabilityPercentage.decimalMin=Percento dostupnosti nesmie byť záporné
validation.productRequestDTO.availabilityPercentage.digits=Percento môže mať maximálne 3 celé čísla a 2 desatinné miesta
validation.productRequestDTO.currentStock.decimalMin=Zásoba nesmie byť záporná
validation.productRequestDTO.currentStock.digits=Zásoba môže mať maximálne 10 celých čísel a 3 desatinné miesta
validation.productRequestDTO.currentStock.notNull=Aktuálna zásoba je povinná
validation.productRequestDTO.minimumStock.decimalMin=Minimálna zásoba nesmie byť záporná
validation.productRequestDTO.minimumStock.digits=Minimálna zásoba môže mať maximálne 10 celých čísel a 3 desatinné miesta
validation.productRequestDTO.minimumStock.notNull=Minimálna zásoba je povinná
validation.productRequestDTO.name.notBlank=Názov produktu je povinný
validation.productRequestDTO.name.size=Musí mať od 2 do 100 znakov
validation.productRequestDTO.productCode.notBlank=Kód produktu je povinný
validation.productRequestDTO.productCode.size=Kód nesmie presiahnuť 50 znakov
validation.productRequestDTO.unit.notBlank=Merná jednotka je povinná
validation.productRequestDTO.unit.size=Jednotka nesmie presiahnuť 20 znakov
validation.productRequestDTO.unitPrice.decimalMin=Cena musí byť väčšia ako nula
validation.productRequestDTO.unitPrice.digits=Cena môže mať maximálne 10 celých čísel a 2 desatinné miesta
validation.productRequestDTO.unitPrice.notNull=Jednotková cena je povinná
validation.recipe.elaboration.size=Príprava nesmie presiahnuť 2000 znakov
validation.recipe.name.notBlank=Názov receptu je povinný
validation.recipe.name.size=Musí mať od 2 do 150 znakov
validation.recipe.presentation.size=Prezentácia nesmie presiahnuť 1000 znakov
validation.recipe.totalCost.decimalMin=Náklady nesmú byť záporné
validation.recipeAudit.action.notBlank=Akcia je povinná
validation.recipeAudit.details.size=Podrobnosti nesmú presiahnuť 1000 znakov
validation.recipeComponent.parentRecipe.notNull=Recept je povinný
validation.recipeComponent.product.notNull=Produkt je povinný
validation.recipeComponent.quantity.decimalMin=Množstvo musí byť väčšie ako 0
validation.recipeComponent.quantity.notNull=Množstvo je povinné
validation.recipeComponentRequestDTO.productId.notNull=ID produktu je povinné
validation.recipeComponentRequestDTO.quantity.decimalMin=Množstvo musí byť väčšie ako nula
validation.recipeComponentRequestDTO.quantity.digits=Množstvo môže mať maximálne 10 celých čísel a 3 desatinné miesta
validation.recipeComponentRequestDTO.quantity.notNull=Množstvo je povinné
validation.recipeCookingAudit.details.size=Podrobnosti nesmú presiahnuť 1000 znakov
validation.recipeCookingAudit.quantityCooked.decimalMin=Množstvo musí byť väčšie ako 0
validation.recipeCookingAudit.quantityCooked.notNull=Uvarené množstvo je povinné
validation.recipeCookingAudit.recipe.notNull=Recept je povinný
validation.recipeCookingRequestDTO.details.size=Podrobnosti nesmú presiahnuť 500 znakov
validation.recipeCookingRequestDTO.quantity.decimalMin=Množstvo musí byť väčšie ako 0
validation.recipeCookingRequestDTO.quantity.digits=Množstvo môže mať maximálne 10 celých čísel a 3 desatinné miesta
validation.recipeCookingRequestDTO.quantity.notNull=Množstvo na uvarenie je povinné
validation.recipeCookingRequestDTO.recipeId.notNull=ID receptu je povinné
validation.recipeCookingRequestDTO.recipeId.positive=ID receptu musí byť kladné
validation.recipeRequestDTO.components.notEmpty=Recept musí obsahovať aspoň jednu zložku
validation.recipeRequestDTO.elaboration.notBlank=Príprava je povinná
validation.recipeRequestDTO.elaboration.size=Príprava nesmie presiahnuť 2000 znakov
validation.recipeRequestDTO.name.notBlank=Názov receptu je povinný
validation.recipeRequestDTO.name.size=Musí mať od 2 do 150 znakov
validation.recipeRequestDTO.presentation.notBlank=Prezentácia je povinná
validation.recipeRequestDTO.presentation.size=Prezentácia nesmie presiahnuť 1000 znakov
validation.roleEscalationRequestDTO.durationMinutes.max=Maximálne povolené trvanie je 1440 minút (24 hodín)
validation.roleEscalationRequestDTO.durationMinutes.min=Minimálne trvanie musí byť 1 minúta
validation.roleEscalationRequestDTO.durationMinutes.notNull=Trvanie v minútach je povinné
validation.stockLedger.currentHash.notBlank=Aktuálny hash je povinný
validation.stockLedger.movementType.notNull=Typ pohybu je povinný
validation.stockLedger.previousHash.notBlank=Predchádzajúci hash je povinný
validation.stockLedger.product.notNull=Produkt je povinný
validation.stockLedger.quantityDelta.notNull=Množstvo je povinné
validation.stockLedger.resultingStock.notNull=Výsledná zásoba je povinná
validation.stockLedger.sequenceNumber.notNull=Sekvenčné číslo je povinné
validation.stockLedger.transactionTimestamp.notNull=Časová pečiatka je povinná
validation.stockMovementItemDTO.description.size=Popis nesmie presiahnuť 500 znakov
validation.stockMovementItemDTO.movementType.notNull=Typ pohybu je povinný
validation.stockMovementItemDTO.productId.notNull=ID produktu je povinné
validation.stockMovementItemDTO.quantityDelta.digits=Množstvo môže mať maximálne 10 celých čísel a 3 desatinné miesta
validation.stockMovementItemDTO.quantityDelta.notNull=Množstvo je povinné
validation.stockSnapshot.currentStock.notNull=Aktuálna zásoba je povinná
validation.stockSnapshot.integrityStatus.notBlank=Stav integrity je povinný
validation.stockSnapshot.lastSequenceNumber.notNull=Sekvenčné číslo je povinné
validation.stockSnapshot.lastTransactionHash.notBlank=Posledný hash je povinný
validation.stockSnapshot.lastUpdated.notNull=Dátum aktualizácie je povinný
validation.supplier.name.notBlank=Názov dodávateľa je povinný
validation.supplier.name.size=Musí mať od 2 do 100 znakov
validation.supplierRequestDTO.name.notBlank=Názov dodávateľa je povinný
validation.supplierRequestDTO.name.size=Musí mať od 2 do 100 znakov
validation.user.name.notBlank=Meno je povinné
validation.user.name.size=Musí mať od 2 do 100 znakov
validation.user.password.notBlank=Heslo je povinné
validation.user.role.notNull=Rola je povinná
validation.user.user.notBlank=Používateľské meno je povinné
validation.userRequestDTO.name.notBlank=Meno je povinné
validation.userRequestDTO.name.size=Musí mať od 2 do 100 znakov
validation.userRequestDTO.password.notBlank=Heslo je povinné
validation.userRequestDTO.password.size=Heslo musí mať aspoň 6 znakov
validation.userRequestDTO.user.notBlank=Používateľské meno je povinné
validation.userRequestDTO.user.size=Používateľské meno nesmie presiahnuť 100 znakov
""",

"hu": """validation.allergen.name.notBlank=Az allergén neve kötelező
validation.allergen.name.size=2 és 50 karakter között kell lennie
validation.allergenRequestDTO.name.notBlank=Az allergén neve kötelező
validation.allergenRequestDTO.name.size=2 és 50 karakter között kell lennie
validation.batchStockMovementRequestDTO.movements.notEmpty=Legalább egy mozgást meg kell adni
validation.batchStockMovementRequestDTO.reason.size=Az ok nem haladhatja meg az 1000 karaktert
validation.changePasswordRequestDTO.newPassword.notBlank=Az új jelszó kötelező
validation.changePasswordRequestDTO.newPassword.size=Az új jelszónak legalább 6 karakterből kell állnia
validation.inventoryAudit.actionDescription.size=A leírás nem haladhatja meg az 500 karaktert
validation.inventoryAudit.product.notNull=A termék kötelező
validation.inventoryAudit.quantity.notNull=A mennyiség kötelező
validation.inventoryAudit.unknown.notBlank=A mozgás típusa kötelező
validation.inventoryMovementRequestDTO.movementType.notNull=A mozgás típusa kötelező
validation.inventoryMovementRequestDTO.productId.notNull=A termék azonosítója kötelező
validation.inventoryMovementRequestDTO.quantity.decimalMax=A mennyiség nem haladhatja meg a 9 999 999,99-et
validation.inventoryMovementRequestDTO.quantity.notNull=A mennyiség kötelező
validation.inventoryMovementRequestDTO.quantity.positive=A mennyiségnek nullánál nagyobbnak kell lennie
validation.inventoryMovementRequestDTO.userId.notNull=A felhasználó azonosítója kötelező
validation.jwtProperties.expiration.positive=A JWT lejárata pozitív érték kell legyen
validation.jwtProperties.secret.notBlank=A JWT titok kötelező
validation.loginRequestDTO.name.notBlank=A felhasználónév kötelező
validation.loginRequestDTO.password.notBlank=A jelszó kötelező
validation.order.orderDate.notNull=A rendelés dátuma kötelező
validation.order.orderDate.pastOrPresent=A rendelés dátuma nem lehet a jövőben
validation.order.status.notBlank=Az állapot kötelező
validation.order.users.notNull=A felhasználó kötelező
validation.orderAudit.action.notBlank=A művelet kötelező
validation.orderAudit.details.size=A részletek nem haladhatják meg az 1000 karaktert
validation.orderDetail.order.notNull=A rendelés kötelező
validation.orderDetail.product.notNull=A termék kötelező
validation.orderDetail.quantity.decimalMin=A mennyiségnek nagyobbnak kell lennie, mint 0
validation.orderDetail.quantity.notNull=A kért mennyiség kötelező
validation.orderDetail.quantityReceived.decimalMin=A kapott mennyiség nem lehet negatív
validation.orderDetailRequestDTO.productId.notNull=A termék azonosítója kötelező
validation.orderDetailRequestDTO.quantity.decimalMin=A mennyiségnek nullánál nagyobbnak kell lennie
validation.orderDetailRequestDTO.quantity.digits=A mennyiség legfeljebb 10 egész és 3 tizedes jegyet tartalmazhat
validation.orderDetailRequestDTO.quantity.notNull=A mennyiség kötelező
validation.orderReceptionDetailRequestDTO.productId.notNull=A termék azonosítója kötelező
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=A kapott mennyiség kötelező
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=A kapott mennyiségnek nullának vagy annál nagyobbnak kell lennie
validation.orderReceptionRequestDTO.items.notEmpty=Legalább egy kapott terméket meg kell adni
validation.orderReceptionRequestDTO.orderId.notNull=A rendelés azonosítója kötelező
validation.orderReceptionRequestDTO.status.notNull=Az állapot kötelező
validation.orderRequestDTO.details.notEmpty=A rendelésnek legalább egy részletet kell tartalmaznia
validation.orderRequestDTO.userId.notNull=A felhasználó azonosítója kötelező
validation.product.availabilityPercentage.decimalMax=Az elérhetőségi százalék nem haladhatja meg a 100-at
validation.product.availabilityPercentage.decimalMin=Az elérhetőségi százalék nem lehet negatív
validation.product.availabilityPercentage.digits=Érvénytelen elérhetőségi formátum
validation.product.currentStock.decimalMin=A készlet nem lehet negatív
validation.product.currentStock.digits=Érvénytelen készletformátum
validation.product.currentStock.notNull=A jelenlegi készlet kötelező
validation.product.minimumStock.decimalMin=A minimális készlet nem lehet negatív
validation.product.minimumStock.digits=Érvénytelen minimális készletformátum
validation.product.name.notBlank=A termék neve kötelező
validation.product.name.size=2 és 100 karakter között kell lennie
validation.product.productCode.notBlank=A termékkód kötelező
validation.product.unit.notBlank=A mértékegység kötelező
validation.product.unitPrice.decimalMin=Az árnak nagyobbnak kell lennie, mint 0
validation.product.unitPrice.digits=Érvénytelen árformátum
validation.product.unitPrice.notNull=Az egységár kötelező
validation.productRequestDTO.availabilityPercentage.decimalMax=Az elérhetőségi százalék nem haladhatja meg a 100-at
validation.productRequestDTO.availabilityPercentage.decimalMin=Az elérhetőségi százalék nem lehet negatív
validation.productRequestDTO.availabilityPercentage.digits=A százalék legfeljebb 3 egész és 2 tizedes jegyet tartalmazhat
validation.productRequestDTO.currentStock.decimalMin=A készlet nem lehet negatív
validation.productRequestDTO.currentStock.digits=A készlet legfeljebb 10 egész és 3 tizedes jegyet tartalmazhat
validation.productRequestDTO.currentStock.notNull=A jelenlegi készlet kötelező
validation.productRequestDTO.minimumStock.decimalMin=A minimális készlet nem lehet negatív
validation.productRequestDTO.minimumStock.digits=A minimális készlet legfeljebb 10 egész és 3 tizedes jegyet tartalmazhat
validation.productRequestDTO.minimumStock.notNull=A minimális készlet kötelező
validation.productRequestDTO.name.notBlank=A termék neve kötelező
validation.productRequestDTO.name.size=2 és 100 karakter között kell lennie
validation.productRequestDTO.productCode.notBlank=A termékkód kötelező
validation.productRequestDTO.productCode.size=A kód nem haladhatja meg az 50 karaktert
validation.productRequestDTO.unit.notBlank=A mértékegység kötelező
validation.productRequestDTO.unit.size=Az egység nem haladhatja meg a 20 karaktert
validation.productRequestDTO.unitPrice.decimalMin=Az árnak nullánál nagyobbnak kell lennie
validation.productRequestDTO.unitPrice.digits=Az ár legfeljebb 10 egész és 2 tizedes jegyet tartalmazhat
validation.productRequestDTO.unitPrice.notNull=Az egységár kötelező
validation.recipe.elaboration.size=Az elkészítés nem haladhatja meg a 2000 karaktert
validation.recipe.name.notBlank=A recept neve kötelező
validation.recipe.name.size=2 és 150 karakter között kell lennie
validation.recipe.presentation.size=A tálalás nem haladhatja meg az 1000 karaktert
validation.recipe.totalCost.decimalMin=A költség nem lehet negatív
validation.recipeAudit.action.notBlank=A művelet kötelező
validation.recipeAudit.details.size=A részletek nem haladhatják meg az 1000 karaktert
validation.recipeComponent.parentRecipe.notNull=A recept kötelező
validation.recipeComponent.product.notNull=A termék kötelező
validation.recipeComponent.quantity.decimalMin=A mennyiségnek nagyobbnak kell lennie, mint 0
validation.recipeComponent.quantity.notNull=A mennyiség kötelező
validation.recipeComponentRequestDTO.productId.notNull=A termék azonosítója kötelező
validation.recipeComponentRequestDTO.quantity.decimalMin=A mennyiségnek nullánál nagyobbnak kell lennie
validation.recipeComponentRequestDTO.quantity.digits=A mennyiség legfeljebb 10 egész és 3 tizedes jegyet tartalmazhat
validation.recipeComponentRequestDTO.quantity.notNull=A mennyiség kötelező
validation.recipeCookingAudit.details.size=A részletek nem haladhatják meg az 1000 karaktert
validation.recipeCookingAudit.quantityCooked.decimalMin=A mennyiségnek nagyobbnak kell lennie, mint 0
validation.recipeCookingAudit.quantityCooked.notNull=A megfőzött mennyiség kötelező
validation.recipeCookingAudit.recipe.notNull=A recept kötelező
validation.recipeCookingRequestDTO.details.size=A részletek nem haladhatják meg az 500 karaktert
validation.recipeCookingRequestDTO.quantity.decimalMin=A mennyiségnek nagyobbnak kell lennie, mint 0
validation.recipeCookingRequestDTO.quantity.digits=A mennyiség legfeljebb 10 egész és 3 tizedes jegyet tartalmazhat
validation.recipeCookingRequestDTO.quantity.notNull=A főzési mennyiség kötelező
validation.recipeCookingRequestDTO.recipeId.notNull=A recept azonosítója kötelező
validation.recipeCookingRequestDTO.recipeId.positive=A recept azonosítójának pozitívnak kell lennie
validation.recipeRequestDTO.components.notEmpty=A receptnek legalább egy összetevőt tartalmaznia kell
validation.recipeRequestDTO.elaboration.notBlank=Az elkészítés kötelező
validation.recipeRequestDTO.elaboration.size=Az elkészítés nem haladhatja meg a 2000 karaktert
validation.recipeRequestDTO.name.notBlank=A recept neve kötelező
validation.recipeRequestDTO.name.size=2 és 150 karakter között kell lennie
validation.recipeRequestDTO.presentation.notBlank=A tálalás kötelező
validation.recipeRequestDTO.presentation.size=A tálalás nem haladhatja meg az 1000 karaktert
validation.roleEscalationRequestDTO.durationMinutes.max=A maximálisan megengedett időtartam 1440 perc (24 óra)
validation.roleEscalationRequestDTO.durationMinutes.min=A minimális időtartamnak 1 percnek kell lennie
validation.roleEscalationRequestDTO.durationMinutes.notNull=Az időtartam percben kötelező
validation.stockLedger.currentHash.notBlank=A jelenlegi hash kötelező
validation.stockLedger.movementType.notNull=A mozgás típusa kötelező
validation.stockLedger.previousHash.notBlank=Az előző hash kötelező
validation.stockLedger.product.notNull=A termék kötelező
validation.stockLedger.quantityDelta.notNull=A mennyiség kötelező
validation.stockLedger.resultingStock.notNull=Az eredménykészlet kötelező
validation.stockLedger.sequenceNumber.notNull=A sorszám kötelező
validation.stockLedger.transactionTimestamp.notNull=Az időbélyeg kötelező
validation.stockMovementItemDTO.description.size=A leírás nem haladhatja meg az 500 karaktert
validation.stockMovementItemDTO.movementType.notNull=A mozgás típusa kötelező
validation.stockMovementItemDTO.productId.notNull=A termék azonosítója kötelező
validation.stockMovementItemDTO.quantityDelta.digits=A mennyiség legfeljebb 10 egész és 3 tizedes jegyet tartalmazhat
validation.stockMovementItemDTO.quantityDelta.notNull=A mennyiség kötelező
validation.stockSnapshot.currentStock.notNull=A jelenlegi készlet kötelező
validation.stockSnapshot.integrityStatus.notBlank=Az integritás állapota kötelező
validation.stockSnapshot.lastSequenceNumber.notNull=A sorszám kötelező
validation.stockSnapshot.lastTransactionHash.notBlank=Az utolsó hash kötelező
validation.stockSnapshot.lastUpdated.notNull=A frissítés dátuma kötelező
validation.supplier.name.notBlank=A beszállító neve kötelező
validation.supplier.name.size=2 és 100 karakter között kell lennie
validation.supplierRequestDTO.name.notBlank=A beszállító neve kötelező
validation.supplierRequestDTO.name.size=2 és 100 karakter között kell lennie
validation.user.name.notBlank=A név kötelező
validation.user.name.size=2 és 100 karakter között kell lennie
validation.user.password.notBlank=A jelszó kötelező
validation.user.role.notNull=A szerepkör kötelező
validation.user.user.notBlank=A felhasználónév kötelező
validation.userRequestDTO.name.notBlank=A név kötelező
validation.userRequestDTO.name.size=2 és 100 karakter között kell lennie
validation.userRequestDTO.password.notBlank=A jelszó kötelező
validation.userRequestDTO.password.size=A jelszónak legalább 6 karakterből kell állnia
validation.userRequestDTO.user.notBlank=A felhasználónév kötelező
validation.userRequestDTO.user.size=A felhasználónév nem haladhatja meg a 100 karaktert
""",

"ro": """validation.allergen.name.notBlank=Numele alergenului este obligatoriu
validation.allergen.name.size=Trebuie să aibă între 2 și 50 de caractere
validation.allergenRequestDTO.name.notBlank=Numele alergenului este obligatoriu
validation.allergenRequestDTO.name.size=Trebuie să aibă între 2 și 50 de caractere
validation.batchStockMovementRequestDTO.movements.notEmpty=Trebuie inclusă cel puțin o mișcare
validation.batchStockMovementRequestDTO.reason.size=Motivul nu poate depăși 1000 de caractere
validation.changePasswordRequestDTO.newPassword.notBlank=Noua parolă este obligatorie
validation.changePasswordRequestDTO.newPassword.size=Parola nouă trebuie să aibă cel puțin 6 caractere
validation.inventoryAudit.actionDescription.size=Descrierea nu poate depăși 500 de caractere
validation.inventoryAudit.product.notNull=Produsul este obligatoriu
validation.inventoryAudit.quantity.notNull=Cantitatea este obligatorie
validation.inventoryAudit.unknown.notBlank=Tipul mișcării este obligatoriu
validation.inventoryMovementRequestDTO.movementType.notNull=Tipul mișcării este obligatoriu
validation.inventoryMovementRequestDTO.productId.notNull=ID-ul produsului este obligatoriu
validation.inventoryMovementRequestDTO.quantity.decimalMax=Cantitatea nu poate depăși 9.999.999,99
validation.inventoryMovementRequestDTO.quantity.notNull=Cantitatea este obligatorie
validation.inventoryMovementRequestDTO.quantity.positive=Cantitatea trebuie să fie mai mare ca zero
validation.inventoryMovementRequestDTO.userId.notNull=ID-ul utilizatorului este obligatoriu
validation.jwtProperties.expiration.positive=Expirarea JWT trebuie să fie o valoare pozitivă
validation.jwtProperties.secret.notBlank=Secretul JWT este obligatoriu
validation.loginRequestDTO.name.notBlank=Numele de utilizator este obligatoriu
validation.loginRequestDTO.password.notBlank=Parola este obligatorie
validation.order.orderDate.notNull=Data comenzii este obligatorie
validation.order.orderDate.pastOrPresent=Data comenzii nu poate fi în viitor
validation.order.status.notBlank=Statusul este obligatoriu
validation.order.users.notNull=Utilizatorul este obligatoriu
validation.orderAudit.action.notBlank=Acțiunea este obligatorie
validation.orderAudit.details.size=Detaliile nu pot depăși 1000 de caractere
validation.orderDetail.order.notNull=Comanda este obligatorie
validation.orderDetail.product.notNull=Produsul este obligatoriu
validation.orderDetail.quantity.decimalMin=Cantitatea trebuie să fie mai mare ca 0
validation.orderDetail.quantity.notNull=Cantitatea cerută este obligatorie
validation.orderDetail.quantityReceived.decimalMin=Cantitatea primită nu poate fi negativă
validation.orderDetailRequestDTO.productId.notNull=ID-ul produsului este obligatoriu
validation.orderDetailRequestDTO.quantity.decimalMin=Cantitatea trebuie să fie mai mare ca zero
validation.orderDetailRequestDTO.quantity.digits=Cantitatea poate avea cel mult 10 numere întregi și 3 zecimale
validation.orderDetailRequestDTO.quantity.notNull=Cantitatea este obligatorie
validation.orderReceptionDetailRequestDTO.productId.notNull=ID-ul produsului este obligatoriu
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Cantitatea primită este obligatorie
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Cantitatea primită trebuie să fie zero sau mai mare
validation.orderReceptionRequestDTO.items.notEmpty=Trebuie specificat cel puțin un produs primit
validation.orderReceptionRequestDTO.orderId.notNull=ID-ul comenzii este obligatoriu
validation.orderReceptionRequestDTO.status.notNull=Statusul este obligatoriu
validation.orderRequestDTO.details.notEmpty=Comanda trebuie să aibă cel puțin un detaliu
validation.orderRequestDTO.userId.notNull=ID-ul utilizatorului este obligatoriu
validation.product.availabilityPercentage.decimalMax=Procentul de disponibilitate nu poate depăși 100
validation.product.availabilityPercentage.decimalMin=Procentul de disponibilitate nu poate fi negativ
validation.product.availabilityPercentage.digits=Format de disponibilitate invalid
validation.product.currentStock.decimalMin=Stocul nu poate fi negativ
validation.product.currentStock.digits=Format de stoc invalid
validation.product.currentStock.notNull=Stocul actual este obligatoriu
validation.product.minimumStock.decimalMin=Stocul minim nu poate fi negativ
validation.product.minimumStock.digits=Format de stoc minim invalid
validation.product.name.notBlank=Numele produsului este obligatoriu
validation.product.name.size=Trebuie să aibă între 2 și 100 de caractere
validation.product.productCode.notBlank=Codul produsului este obligatoriu
validation.product.unit.notBlank=Unitatea de măsură este obligatorie
validation.product.unitPrice.decimalMin=Prețul trebuie să fie mai mare ca 0
validation.product.unitPrice.digits=Format de preț invalid
validation.product.unitPrice.notNull=Prețul unitar este obligatoriu
validation.productRequestDTO.availabilityPercentage.decimalMax=Procentul de disponibilitate nu poate depăși 100
validation.productRequestDTO.availabilityPercentage.decimalMin=Procentul de disponibilitate nu poate fi negativ
validation.productRequestDTO.availabilityPercentage.digits=Procentul poate avea cel mult 3 numere întregi și 2 zecimale
validation.productRequestDTO.currentStock.decimalMin=Stocul nu poate fi negativ
validation.productRequestDTO.currentStock.digits=Stocul poate avea cel mult 10 numere întregi și 3 zecimale
validation.productRequestDTO.currentStock.notNull=Stocul actual este obligatoriu
validation.productRequestDTO.minimumStock.decimalMin=Stocul minim nu poate fi negativ
validation.productRequestDTO.minimumStock.digits=Stocul minim poate avea cel mult 10 numere întregi și 3 zecimale
validation.productRequestDTO.minimumStock.notNull=Stocul minim este obligatoriu
validation.productRequestDTO.name.notBlank=Numele produsului este obligatoriu
validation.productRequestDTO.name.size=Trebuie să aibă între 2 și 100 de caractere
validation.productRequestDTO.productCode.notBlank=Codul produsului este obligatoriu
validation.productRequestDTO.productCode.size=Codul nu poate depăși 50 de caractere
validation.productRequestDTO.unit.notBlank=Unitatea de măsură este obligatorie
validation.productRequestDTO.unit.size=Unitatea nu poate depăși 20 de caractere
validation.productRequestDTO.unitPrice.decimalMin=Prețul trebuie să fie mai mare ca zero
validation.productRequestDTO.unitPrice.digits=Prețul poate avea cel mult 10 numere întregi și 2 zecimale
validation.productRequestDTO.unitPrice.notNull=Prețul unitar este obligatoriu
validation.recipe.elaboration.size=Prepararea nu poate depăși 2000 de caractere
validation.recipe.name.notBlank=Numele rețetei este obligatoriu
validation.recipe.name.size=Trebuie să aibă între 2 și 150 de caractere
validation.recipe.presentation.size=Prezentarea nu poate depăși 1000 de caractere
validation.recipe.totalCost.decimalMin=Costul nu poate fi negativ
validation.recipeAudit.action.notBlank=Acțiunea este obligatorie
validation.recipeAudit.details.size=Detaliile nu pot depăși 1000 de caractere
validation.recipeComponent.parentRecipe.notNull=Rețeta este obligatorie
validation.recipeComponent.product.notNull=Produsul este obligatoriu
validation.recipeComponent.quantity.decimalMin=Cantitatea trebuie să fie mai mare ca 0
validation.recipeComponent.quantity.notNull=Cantitatea este obligatorie
validation.recipeComponentRequestDTO.productId.notNull=ID-ul produsului este obligatoriu
validation.recipeComponentRequestDTO.quantity.decimalMin=Cantitatea trebuie să fie mai mare ca zero
validation.recipeComponentRequestDTO.quantity.digits=Cantitatea poate avea cel mult 10 numere întregi și 3 zecimale
validation.recipeComponentRequestDTO.quantity.notNull=Cantitatea este obligatorie
validation.recipeCookingAudit.details.size=Detaliile nu pot depăși 1000 de caractere
validation.recipeCookingAudit.quantityCooked.decimalMin=Cantitatea trebuie să fie mai mare ca 0
validation.recipeCookingAudit.quantityCooked.notNull=Cantitatea gătită este obligatorie
validation.recipeCookingAudit.recipe.notNull=Rețeta este obligatorie
validation.recipeCookingRequestDTO.details.size=Detaliile nu pot depăși 500 de caractere
validation.recipeCookingRequestDTO.quantity.decimalMin=Cantitatea trebuie să fie mai mare ca 0
validation.recipeCookingRequestDTO.quantity.digits=Cantitatea poate avea cel mult 10 numere întregi și 3 zecimale
validation.recipeCookingRequestDTO.quantity.notNull=Cantitatea de gătit este obligatorie
validation.recipeCookingRequestDTO.recipeId.notNull=ID-ul rețetei este obligatoriu
validation.recipeCookingRequestDTO.recipeId.positive=ID-ul rețetei trebuie să fie pozitiv
validation.recipeRequestDTO.components.notEmpty=Rețeta trebuie să includă cel puțin o componentă
validation.recipeRequestDTO.elaboration.notBlank=Prepararea este obligatorie
validation.recipeRequestDTO.elaboration.size=Prepararea nu poate depăși 2000 de caractere
validation.recipeRequestDTO.name.notBlank=Numele rețetei este obligatoriu
validation.recipeRequestDTO.name.size=Trebuie să aibă între 2 și 150 de caractere
validation.recipeRequestDTO.presentation.notBlank=Prezentarea este obligatorie
validation.recipeRequestDTO.presentation.size=Prezentarea nu poate depăși 1000 de caractere
validation.roleEscalationRequestDTO.durationMinutes.max=Durata maximă permisă este de 1440 de minute (24 de ore)
validation.roleEscalationRequestDTO.durationMinutes.min=Durata minimă trebuie să fie de 1 minut
validation.roleEscalationRequestDTO.durationMinutes.notNull=Durata în minute este obligatorie
validation.stockLedger.currentHash.notBlank=Hash-ul actual este obligatoriu
validation.stockLedger.movementType.notNull=Tipul mișcării este obligatoriu
validation.stockLedger.previousHash.notBlank=Hash-ul anterior este obligatoriu
validation.stockLedger.product.notNull=Produsul este obligatoriu
validation.stockLedger.quantityDelta.notNull=Cantitatea este obligatorie
validation.stockLedger.resultingStock.notNull=Stocul rezultat este obligatoriu
validation.stockLedger.sequenceNumber.notNull=Numărul de secvență este obligatoriu
validation.stockLedger.transactionTimestamp.notNull=Marcajul de timp este obligatoriu
validation.stockMovementItemDTO.description.size=Descrierea nu poate depăși 500 de caractere
validation.stockMovementItemDTO.movementType.notNull=Tipul mișcării este obligatoriu
validation.stockMovementItemDTO.productId.notNull=ID-ul produsului este obligatoriu
validation.stockMovementItemDTO.quantityDelta.digits=Cantitatea poate avea cel mult 10 numere întregi și 3 zecimale
validation.stockMovementItemDTO.quantityDelta.notNull=Cantitatea este obligatorie
validation.stockSnapshot.currentStock.notNull=Stocul actual este obligatoriu
validation.stockSnapshot.integrityStatus.notBlank=Statusul integrității este obligatoriu
validation.stockSnapshot.lastSequenceNumber.notNull=Numărul de secvență este obligatoriu
validation.stockSnapshot.lastTransactionHash.notBlank=Ultimul hash este obligatoriu
validation.stockSnapshot.lastUpdated.notNull=Data actualizării este obligatorie
validation.supplier.name.notBlank=Numele furnizorului este obligatoriu
validation.supplier.name.size=Trebuie să aibă între 2 și 100 de caractere
validation.supplierRequestDTO.name.notBlank=Numele furnizorului este obligatoriu
validation.supplierRequestDTO.name.size=Trebuie să aibă între 2 și 100 de caractere
validation.user.name.notBlank=Numele este obligatoriu
validation.user.name.size=Trebuie să aibă între 2 și 100 de caractere
validation.user.password.notBlank=Parola este obligatorie
validation.user.role.notNull=Rolul este obligatoriu
validation.user.user.notBlank=Numele de utilizator este obligatoriu
validation.userRequestDTO.name.notBlank=Numele este obligatoriu
validation.userRequestDTO.name.size=Trebuie să aibă între 2 și 100 de caractere
validation.userRequestDTO.password.notBlank=Parola este obligatorie
validation.userRequestDTO.password.size=Parola trebuie să aibă cel puțin 6 caractere
validation.userRequestDTO.user.notBlank=Numele de utilizator este obligatoriu
validation.userRequestDTO.user.size=Numele de utilizator nu poate depăși 100 de caractere
"""
}

for lang, content in FILES.items():
    path = os.path.join(VDIR, f"ValidationMessages_{lang}.properties")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content.strip() + "\n")
    lines = [l for l in content.strip().split("\n") if "=" in l]
    print(f"  {lang}: wrote {len(lines)} keys")
