#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Writes ET, LV, LT, EL ValidationMessages files."""
import os
VDIR = "src/main/resources/i18n/validation/"
FILES = {
"et": """validation.allergen.name.notBlank=Allergeeni nimi on kohustuslik
validation.allergen.name.size=Peab olema 2 kuni 50 tähemärki
validation.allergenRequestDTO.name.notBlank=Allergeeni nimi on kohustuslik
validation.allergenRequestDTO.name.size=Peab olema 2 kuni 50 tähemärki
validation.batchStockMovementRequestDTO.movements.notEmpty=Peab sisaldama vähemalt ühte liikumist
validation.batchStockMovementRequestDTO.reason.size=Põhjus ei tohi ületada 1000 tähemärki
validation.changePasswordRequestDTO.newPassword.notBlank=Uus parool on kohustuslik
validation.changePasswordRequestDTO.newPassword.size=Uus parool peab olema vähemalt 6 tähemärki
validation.inventoryAudit.actionDescription.size=Kirjeldus ei tohi ületada 500 tähemärki
validation.inventoryAudit.product.notNull=Toode on kohustuslik
validation.inventoryAudit.quantity.notNull=Kogus on kohustuslik
validation.inventoryAudit.unknown.notBlank=Liikumise tüüp on kohustuslik
validation.inventoryMovementRequestDTO.movementType.notNull=Liikumise tüüp on kohustuslik
validation.inventoryMovementRequestDTO.productId.notNull=Toote ID on kohustuslik
validation.inventoryMovementRequestDTO.quantity.decimalMax=Kogus ei tohi ületada 9 999 999,99
validation.inventoryMovementRequestDTO.quantity.notNull=Kogus on kohustuslik
validation.inventoryMovementRequestDTO.quantity.positive=Kogus peab olema suurem kui null
validation.inventoryMovementRequestDTO.userId.notNull=Kasutaja ID on kohustuslik
validation.jwtProperties.expiration.positive=JWT aegumine peab olema positiivne väärtus
validation.jwtProperties.secret.notBlank=JWT saladus on kohustuslik
validation.loginRequestDTO.name.notBlank=Kasutajanimi on kohustuslik
validation.loginRequestDTO.password.notBlank=Parool on kohustuslik
validation.order.orderDate.notNull=Tellimuse kuupäev on kohustuslik
validation.order.orderDate.pastOrPresent=Tellimuse kuupäev ei tohi olla tulevikus
validation.order.status.notBlank=Olek on kohustuslik
validation.order.users.notNull=Kasutaja on kohustuslik
validation.orderAudit.action.notBlank=Tegevus on kohustuslik
validation.orderAudit.details.size=Üksikasjad ei tohi ületada 1000 tähemärki
validation.orderDetail.order.notNull=Tellimus on kohustuslik
validation.orderDetail.product.notNull=Toode on kohustuslik
validation.orderDetail.quantity.decimalMin=Kogus peab olema suurem kui 0
validation.orderDetail.quantity.notNull=Nõutav kogus on kohustuslik
validation.orderDetail.quantityReceived.decimalMin=Saadud kogus ei tohi olla negatiivne
validation.orderDetailRequestDTO.productId.notNull=Toote ID on kohustuslik
validation.orderDetailRequestDTO.quantity.decimalMin=Kogus peab olema suurem kui null
validation.orderDetailRequestDTO.quantity.digits=Kogusel võib olla maksimaalselt 10 täisarvu ja 3 komakohta
validation.orderDetailRequestDTO.quantity.notNull=Kogus on kohustuslik
validation.orderReceptionDetailRequestDTO.productId.notNull=Toote ID on kohustuslik
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Saadud kogus on kohustuslik
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Saadud kogus peab olema null või suurem
validation.orderReceptionRequestDTO.items.notEmpty=Tuleb määrata vähemalt üks saadud toode
validation.orderReceptionRequestDTO.orderId.notNull=Tellimuse ID on kohustuslik
validation.orderReceptionRequestDTO.status.notNull=Olek on kohustuslik
validation.orderRequestDTO.details.notEmpty=Tellimusel peab olema vähemalt üks detail
validation.orderRequestDTO.userId.notNull=Kasutaja ID on kohustuslik
validation.product.availabilityPercentage.decimalMax=Saadavusprotsent ei tohi ületada 100
validation.product.availabilityPercentage.decimalMin=Saadavusprotsent ei tohi olla negatiivne
validation.product.availabilityPercentage.digits=Vigane saadavuse vorming
validation.product.currentStock.decimalMin=Varu ei tohi olla negatiivne
validation.product.currentStock.digits=Vigane varu vorming
validation.product.currentStock.notNull=Praegune varu on kohustuslik
validation.product.minimumStock.decimalMin=Miinimumvaru ei tohi olla negatiivne
validation.product.minimumStock.digits=Vigane miinimumvaru vorming
validation.product.name.notBlank=Toote nimi on kohustuslik
validation.product.name.size=Peab olema 2 kuni 100 tähemärki
validation.product.productCode.notBlank=Tootekood on kohustuslik
validation.product.unit.notBlank=Mõõtühik on kohustuslik
validation.product.unitPrice.decimalMin=Hind peab olema suurem kui 0
validation.product.unitPrice.digits=Vigane hinna vorming
validation.product.unitPrice.notNull=Ühikuhind on kohustuslik
validation.productRequestDTO.availabilityPercentage.decimalMax=Saadavusprotsent ei tohi ületada 100
validation.productRequestDTO.availabilityPercentage.decimalMin=Saadavusprotsent ei tohi olla negatiivine
validation.productRequestDTO.availabilityPercentage.digits=Protsendil võib olla maksimaalselt 3 täisarvu ja 2 komakohta
validation.productRequestDTO.currentStock.decimalMin=Varu ei tohi olla negatiivne
validation.productRequestDTO.currentStock.digits=Varul võib olla maksimaalselt 10 täisarvu ja 3 komakohta
validation.productRequestDTO.currentStock.notNull=Praegune varu on kohustuslik
validation.productRequestDTO.minimumStock.decimalMin=Miinimumvaru ei tohi olla negatiivne
validation.productRequestDTO.minimumStock.digits=Miinimumvarul võib olla maksimaalselt 10 täisarvu ja 3 komakohta
validation.productRequestDTO.minimumStock.notNull=Miinimumvaru on kohustuslik
validation.productRequestDTO.name.notBlank=Toote nimi on kohustuslik
validation.productRequestDTO.name.size=Peab olema 2 kuni 100 tähemärki
validation.productRequestDTO.productCode.notBlank=Tootekood on kohustuslik
validation.productRequestDTO.productCode.size=Kood ei tohi ületada 50 tähemärki
validation.productRequestDTO.unit.notBlank=Mõõtühik on kohustuslik
validation.productRequestDTO.unit.size=Ühik ei tohi ületada 20 tähemärki
validation.productRequestDTO.unitPrice.decimalMin=Hind peab olema suurem kui null
validation.productRequestDTO.unitPrice.digits=Hinnal võib olla maksimaalselt 10 täisarvu ja 2 komakohta
validation.productRequestDTO.unitPrice.notNull=Ühikuhind on kohustuslik
validation.recipe.elaboration.size=Ettevalmistus ei tohi ületada 2000 tähemärki
validation.recipe.name.notBlank=Retsepti nimi on kohustuslik
validation.recipe.name.size=Peab olema 2 kuni 150 tähemärki
validation.recipe.presentation.size=Esitlus ei tohi ületada 1000 tähemärki
validation.recipe.totalCost.decimalMin=Kulu ei tohi olla negatiivne
validation.recipeAudit.action.notBlank=Tegevus on kohustuslik
validation.recipeAudit.details.size=Üksikasjad ei tohi ületada 1000 tähemärki
validation.recipeComponent.parentRecipe.notNull=Retsept on kohustuslik
validation.recipeComponent.product.notNull=Toode on kohustuslik
validation.recipeComponent.quantity.decimalMin=Kogus peab olema suurem kui 0
validation.recipeComponent.quantity.notNull=Kogus on kohustuslik
validation.recipeComponentRequestDTO.productId.notNull=Toote ID on kohustuslik
validation.recipeComponentRequestDTO.quantity.decimalMin=Kogus peab olema suurem kui null
validation.recipeComponentRequestDTO.quantity.digits=Kogusel võib olla maksimaalselt 10 täisarvu ja 3 komakohta
validation.recipeComponentRequestDTO.quantity.notNull=Kogus on kohustuslik
validation.recipeCookingAudit.details.size=Üksikasjad ei tohi ületada 1000 tähemärki
validation.recipeCookingAudit.quantityCooked.decimalMin=Kogus peab olema suurem kui 0
validation.recipeCookingAudit.quantityCooked.notNull=Valmistatud kogus on kohustuslik
validation.recipeCookingAudit.recipe.notNull=Retsept on kohustuslik
validation.recipeCookingRequestDTO.details.size=Üksikasjad ei tohi ületada 500 tähemärki
validation.recipeCookingRequestDTO.quantity.decimalMin=Kogus peab olema suurem kui 0
validation.recipeCookingRequestDTO.quantity.digits=Kogusel võib olla maksimaalselt 10 täisarvu ja 3 komakohta
validation.recipeCookingRequestDTO.quantity.notNull=Valmistatav kogus on kohustuslik
validation.recipeCookingRequestDTO.recipeId.notNull=Retsepti ID on kohustuslik
validation.recipeCookingRequestDTO.recipeId.positive=Retsepti ID peab olema positiivne
validation.recipeRequestDTO.components.notEmpty=Retsept peab sisaldama vähemalt ühte komponenti
validation.recipeRequestDTO.elaboration.notBlank=Ettevalmistus on kohustuslik
validation.recipeRequestDTO.elaboration.size=Ettevalmistus ei tohi ületada 2000 tähemärki
validation.recipeRequestDTO.name.notBlank=Retsepti nimi on kohustuslik
validation.recipeRequestDTO.name.size=Peab olema 2 kuni 150 tähemärki
validation.recipeRequestDTO.presentation.notBlank=Esitlus on kohustuslik
validation.recipeRequestDTO.presentation.size=Esitlus ei tohi ületada 1000 tähemärki
validation.roleEscalationRequestDTO.durationMinutes.max=Maksimaalne lubatud kestus on 1440 minutit (24 tundi)
validation.roleEscalationRequestDTO.durationMinutes.min=Minimaalne kestus peab olema 1 minut
validation.roleEscalationRequestDTO.durationMinutes.notNull=Kestus minutites on kohustuslik
validation.stockLedger.currentHash.notBlank=Praegune räsi on kohustuslik
validation.stockLedger.movementType.notNull=Liikumise tüüp on kohustuslik
validation.stockLedger.previousHash.notBlank=Eelmine räsi on kohustuslik
validation.stockLedger.product.notNull=Toode on kohustuslik
validation.stockLedger.quantityDelta.notNull=Kogus on kohustuslik
validation.stockLedger.resultingStock.notNull=Tekkiv varu on kohustuslik
validation.stockLedger.sequenceNumber.notNull=Järjenumber on kohustuslik
validation.stockLedger.transactionTimestamp.notNull=Ajatempel on kohustuslik
validation.stockMovementItemDTO.description.size=Kirjeldus ei tohi ületada 500 tähemärki
validation.stockMovementItemDTO.movementType.notNull=Liikumise tüüp on kohustuslik
validation.stockMovementItemDTO.productId.notNull=Toote ID on kohustuslik
validation.stockMovementItemDTO.quantityDelta.digits=Kogusel võib olla maksimaalselt 10 täisarvu ja 3 komakohta
validation.stockMovementItemDTO.quantityDelta.notNull=Kogus on kohustuslik
validation.stockSnapshot.currentStock.notNull=Praegune varu on kohustuslik
validation.stockSnapshot.integrityStatus.notBlank=Tervikluse olek on kohustuslik
validation.stockSnapshot.lastSequenceNumber.notNull=Järjenumber on kohustuslik
validation.stockSnapshot.lastTransactionHash.notBlank=Viimane räsi on kohustuslik
validation.stockSnapshot.lastUpdated.notNull=Värskendamise kuupäev on kohustuslik
validation.supplier.name.notBlank=Tarnija nimi on kohustuslik
validation.supplier.name.size=Peab olema 2 kuni 100 tähemärki
validation.supplierRequestDTO.name.notBlank=Tarnija nimi on kohustuslik
validation.supplierRequestDTO.name.size=Peab olema 2 kuni 100 tähemärki
validation.user.name.notBlank=Nimi on kohustuslik
validation.user.name.size=Peab olema 2 kuni 100 tähemärki
validation.user.password.notBlank=Parool on kohustuslik
validation.user.role.notNull=Roll on kohustuslik
validation.user.user.notBlank=Kasutajanimi on kohustuslik
validation.userRequestDTO.name.notBlank=Nimi on kohustuslik
validation.userRequestDTO.name.size=Peab olema 2 kuni 100 tähemärki
validation.userRequestDTO.password.notBlank=Parool on kohustuslik
validation.userRequestDTO.password.size=Parool peab olema vähemalt 6 tähemärki
validation.userRequestDTO.user.notBlank=Kasutajanimi on kohustuslik
validation.userRequestDTO.user.size=Kasutajanimi ei tohi ületada 100 tähemärki
""",

"lv": """validation.allergen.name.notBlank=Alergēna nosaukums ir obligāts
validation.allergen.name.size=Jābūt no 2 līdz 50 rakstzīmēm
validation.allergenRequestDTO.name.notBlank=Alergēna nosaukums ir obligāts
validation.allergenRequestDTO.name.size=Jābūt no 2 līdz 50 rakstzīmēm
validation.batchStockMovementRequestDTO.movements.notEmpty=Jāiekļauj vismaz viena kustība
validation.batchStockMovementRequestDTO.reason.size=Iemesls nedrīkst pārsniegt 1000 rakstzīmes
validation.changePasswordRequestDTO.newPassword.notBlank=Jaunā parole ir obligāta
validation.changePasswordRequestDTO.newPassword.size=Jaunajai parolei jābūt vismaz 6 rakstzīmēm
validation.inventoryAudit.actionDescription.size=Apraksts nedrīkst pārsniegt 500 rakstzīmes
validation.inventoryAudit.product.notNull=Produkts ir obligāts
validation.inventoryAudit.quantity.notNull=Daudzums ir obligāts
validation.inventoryAudit.unknown.notBlank=Kustības veids ir obligāts
validation.inventoryMovementRequestDTO.movementType.notNull=Kustības veids ir obligāts
validation.inventoryMovementRequestDTO.productId.notNull=Produkta ID ir obligāts
validation.inventoryMovementRequestDTO.quantity.decimalMax=Daudzums nedrīkst pārsniegt 9 999 999,99
validation.inventoryMovementRequestDTO.quantity.notNull=Daudzums ir obligāts
validation.inventoryMovementRequestDTO.quantity.positive=Daudzumam jābūt lielākam par nulli
validation.inventoryMovementRequestDTO.userId.notNull=Lietotāja ID ir obligāts
validation.jwtProperties.expiration.positive=JWT derīguma termiņam jābūt pozitīvai vērtībai
validation.jwtProperties.secret.notBlank=JWT noslēpums ir obligāts
validation.loginRequestDTO.name.notBlank=Lietotājvārds ir obligāts
validation.loginRequestDTO.password.notBlank=Parole ir obligāta
validation.order.orderDate.notNull=Pasūtījuma datums ir obligāts
validation.order.orderDate.pastOrPresent=Pasūtījuma datums nedrīkst būt nākotnē
validation.order.status.notBlank=Statuss ir obligāts
validation.order.users.notNull=Lietotājs ir obligāts
validation.orderAudit.action.notBlank=Darbība ir obligāta
validation.orderAudit.details.size=Sīkāka informācija nedrīkst pārsniegt 1000 rakstzīmes
validation.orderDetail.order.notNull=Pasūtījums ir obligāts
validation.orderDetail.product.notNull=Produkts ir obligāts
validation.orderDetail.quantity.decimalMin=Daudzumam jābūt lielākam par 0
validation.orderDetail.quantity.notNull=Pieprasītais daudzums ir obligāts
validation.orderDetail.quantityReceived.decimalMin=Saņemtais daudzums nedrīkst būt negatīvs
validation.orderDetailRequestDTO.productId.notNull=Produkta ID ir obligāts
validation.orderDetailRequestDTO.quantity.decimalMin=Daudzumam jābūt lielākam par nulli
validation.orderDetailRequestDTO.quantity.digits=Daudzumam var būt ne vairāk kā 10 veseli skaitļi un 3 zīmes aiz komata
validation.orderDetailRequestDTO.quantity.notNull=Daudzums ir obligāts
validation.orderReceptionDetailRequestDTO.productId.notNull=Produkta ID ir obligāts
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Saņemtais daudzums ir obligāts
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Saņemtajam daudzumam jābūt vienādam ar nulli vai lielākam
validation.orderReceptionRequestDTO.items.notEmpty=Jānorāda vismaz viens saņemtais produkts
validation.orderReceptionRequestDTO.orderId.notNull=Pasūtījuma ID ir obligāts
validation.orderReceptionRequestDTO.status.notNull=Statuss ir obligāts
validation.orderRequestDTO.details.notEmpty=Pasūtījumā jābūt vismaz vienai iedaļai
validation.orderRequestDTO.userId.notNull=Lietotāja ID ir obligāts
validation.product.availabilityPercentage.decimalMax=Pieejamības procents nedrīkst pārsniegt 100
validation.product.availabilityPercentage.decimalMin=Pieejamības procents nedrīkst būt negatīvs
validation.product.availabilityPercentage.digits=Nederīgs pieejamības formāts
validation.product.currentStock.decimalMin=Krājumi nedrīkst būt negatīvi
validation.product.currentStock.digits=Nederīgs krājumu formāts
validation.product.currentStock.notNull=Pašreizējie krājumi ir obligāti
validation.product.minimumStock.decimalMin=Minimālie krājumi nedrīkst būt negatīvi
validation.product.minimumStock.digits=Nederīgs minimālā krājuma formāts
validation.product.name.notBlank=Produkta nosaukums ir obligāts
validation.product.name.size=Jābūt no 2 līdz 100 rakstzīmēm
validation.product.productCode.notBlank=Produkta kods ir obligāts
validation.product.unit.notBlank=Mērvienība ir obligāta
validation.product.unitPrice.decimalMin=Cenai jābūt lielākai par 0
validation.product.unitPrice.digits=Nederīgs cenas formāts
validation.product.unitPrice.notNull=Vienības cena ir obligāta
validation.productRequestDTO.availabilityPercentage.decimalMax=Pieejamības procents nedrīkst pārsniegt 100
validation.productRequestDTO.availabilityPercentage.decimalMin=Pieejamības procents nedrīkst būt negatīvs
validation.productRequestDTO.availabilityPercentage.digits=Procentam var būt ne vairāk kā 3 veseli skaitļi un 2 zīmes aiz komata
validation.productRequestDTO.currentStock.decimalMin=Krājumi nedrīkst būt negatīvi
validation.productRequestDTO.currentStock.digits=Krājumiem var būt ne vairāk kā 10 veseli skaitļi un 3 zīmes aiz komata
validation.productRequestDTO.currentStock.notNull=Pašreizējie krājumi ir obligāti
validation.productRequestDTO.minimumStock.decimalMin=Minimālie krājumi nedrīkst būt negatīvi
validation.productRequestDTO.minimumStock.digits=Minimālajiem krājumiem var būt ne vairāk kā 10 veseli skaitļi un 3 zīmes aiz komata
validation.productRequestDTO.minimumStock.notNull=Minimālie krājumi ir obligāti
validation.productRequestDTO.name.notBlank=Produkta nosaukums ir obligāts
validation.productRequestDTO.name.size=Jābūt no 2 līdz 100 rakstzīmēm
validation.productRequestDTO.productCode.notBlank=Produkta kods ir obligāts
validation.productRequestDTO.productCode.size=Kods nedrīkst pārsniegt 50 rakstzīmes
validation.productRequestDTO.unit.notBlank=Mērvienība ir obligāta
validation.productRequestDTO.unit.size=Vienība nedrīkst pārsniegt 20 rakstzīmes
validation.productRequestDTO.unitPrice.decimalMin=Cenai jābūt lielākai par nulli
validation.productRequestDTO.unitPrice.digits=Cenai var būt ne vairāk kā 10 veseli skaitļi un 2 zīmes aiz komata
validation.productRequestDTO.unitPrice.notNull=Vienības cena ir obligāta
validation.recipe.elaboration.size=Pagatavošana nedrīkst pārsniegt 2000 rakstzīmes
validation.recipe.name.notBlank=Receptes nosaukums ir obligāts
validation.recipe.name.size=Jābūt no 2 līdz 150 rakstzīmēm
validation.recipe.presentation.size=Noformējums nedrīkst pārsniegt 1000 rakstzīmes
validation.recipe.totalCost.decimalMin=Izmaksas nedrīkst būt negatīvas
validation.recipeAudit.action.notBlank=Darbība ir obligāta
validation.recipeAudit.details.size=Sīkāka informācija nedrīkst pārsniegt 1000 rakstzīmes
validation.recipeComponent.parentRecipe.notNull=Recepte ir obligāta
validation.recipeComponent.product.notNull=Produkts ir obligāts
validation.recipeComponent.quantity.decimalMin=Daudzumam jābūt lielākam par 0
validation.recipeComponent.quantity.notNull=Daudzums ir obligāts
validation.recipeComponentRequestDTO.productId.notNull=Produkta ID ir obligāts
validation.recipeComponentRequestDTO.quantity.decimalMin=Daudzumam jābūt lielākam par nulli
validation.recipeComponentRequestDTO.quantity.digits=Daudzumam var būt ne vairāk kā 10 veseli skaitļi un 3 zīmes aiz komata
validation.recipeComponentRequestDTO.quantity.notNull=Daudzums ir obligāts
validation.recipeCookingAudit.details.size=Sīkāka informācija nedrīkst pārsniegt 1000 rakstzīmes
validation.recipeCookingAudit.quantityCooked.decimalMin=Daudzumam jābūt lielākam par 0
validation.recipeCookingAudit.quantityCooked.notNull=Pagatavotais daudzums ir obligāts
validation.recipeCookingAudit.recipe.notNull=Recepte ir obligāta
validation.recipeCookingRequestDTO.details.size=Sīkāka informācija nedrīkst pārsniegt 500 rakstzīmes
validation.recipeCookingRequestDTO.quantity.decimalMin=Daudzumam jābūt lielākam par 0
validation.recipeCookingRequestDTO.quantity.digits=Daudzumam var būt ne vairāk kā 10 veseli skaitļi un 3 zīmes aiz komata
validation.recipeCookingRequestDTO.quantity.notNull=Paredzamais gatavošanas daudzums ir obligāts
validation.recipeCookingRequestDTO.recipeId.notNull=Receptes ID ir obligāts
validation.recipeCookingRequestDTO.recipeId.positive=Receptes ID jābūt pozitīvam
validation.recipeRequestDTO.components.notEmpty=Receptei jāietver vismaz viens komponents
validation.recipeRequestDTO.elaboration.notBlank=Pagatavošana ir obligāta
validation.recipeRequestDTO.elaboration.size=Pagatavošana nedrīkst pārsniegt 2000 rakstzīmes
validation.recipeRequestDTO.name.notBlank=Receptes nosaukums ir obligāts
validation.recipeRequestDTO.name.size=Jābūt no 2 līdz 150 rakstzīmēm
validation.recipeRequestDTO.presentation.notBlank=Noformējums ir obligāts
validation.recipeRequestDTO.presentation.size=Noformējums nedrīkst pārsniegt 1000 rakstzīmes
validation.roleEscalationRequestDTO.durationMinutes.max=Maksimālais atļautais ilgums ir 1440 minūtes (24 stundas)
validation.roleEscalationRequestDTO.durationMinutes.min=Minimālajam ilgumam jābūt 1 minūtei
validation.roleEscalationRequestDTO.durationMinutes.notNull=Ilgums minūtēs ir obligāts
validation.stockLedger.currentHash.notBlank=Pašreizējais jaucējkods (hash) ir obligāts
validation.stockLedger.movementType.notNull=Kustības veids ir obligāts
validation.stockLedger.previousHash.notBlank=Iepriekšējais jaucējkods (hash) ir obligāts
validation.stockLedger.product.notNull=Produkts ir obligāts
validation.stockLedger.quantityDelta.notNull=Daudzums ir obligāts
validation.stockLedger.resultingStock.notNull=Rezultējošie krājumi ir obligāti
validation.stockLedger.sequenceNumber.notNull=Kārtas numurs ir obligāts
validation.stockLedger.transactionTimestamp.notNull=Laika zīmogs ir obligāts
validation.stockMovementItemDTO.description.size=Apraksts nedrīkst pārsniegt 500 rakstzīmes
validation.stockMovementItemDTO.movementType.notNull=Kustības veids ir obligāts
validation.stockMovementItemDTO.productId.notNull=Produkta ID ir obligāts
validation.stockMovementItemDTO.quantityDelta.digits=Daudzumam var būt ne vairāk kā 10 veseli skaitļi un 3 zīmes aiz komata
validation.stockMovementItemDTO.quantityDelta.notNull=Daudzums ir obligāts
validation.stockSnapshot.currentStock.notNull=Pašreizējie krājumi ir obligāti
validation.stockSnapshot.integrityStatus.notBlank=Integritātes statuss ir obligāts
validation.stockSnapshot.lastSequenceNumber.notNull=Kārtas numurs ir obligāts
validation.stockSnapshot.lastTransactionHash.notBlank=Pēdējais jaucējkods (hash) ir obligāts
validation.stockSnapshot.lastUpdated.notNull=Atjaunināšanas datums ir obligāts
validation.supplier.name.notBlank=Piegādātāja nosaukums ir obligāts
validation.supplier.name.size=Jābūt no 2 līdz 100 rakstzīmēm
validation.supplierRequestDTO.name.notBlank=Piegādātāja nosaukums ir obligāts
validation.supplierRequestDTO.name.size=Jābūt no 2 līdz 100 rakstzīmēm
validation.user.name.notBlank=Vārds ir obligāts
validation.user.name.size=Jābūt no 2 līdz 100 rakstzīmēm
validation.user.password.notBlank=Parole ir obligāta
validation.user.role.notNull=Loma ir obligāta
validation.user.user.notBlank=Lietotājvārds ir obligāts
validation.userRequestDTO.name.notBlank=Vārds ir obligāts
validation.userRequestDTO.name.size=Jābūt no 2 līdz 100 rakstzīmēm
validation.userRequestDTO.password.notBlank=Parole ir obligāta
validation.userRequestDTO.password.size=Parolei jābūt vismaz 6 rakstzīmēm
validation.userRequestDTO.user.notBlank=Lietotājvārds ir obligāts
validation.userRequestDTO.user.size=Lietotājvārds nedrīkst pārsniegt 100 rakstzīmes
""",

"lt": """validation.allergen.name.notBlank=Alergeno pavadinimas yra privalomas
validation.allergen.name.size=Turi būti nuo 2 iki 50 simbolių
validation.allergenRequestDTO.name.notBlank=Alergeno pavadinimas yra privalomas
validation.allergenRequestDTO.name.size=Turi būti nuo 2 iki 50 simbolių
validation.batchStockMovementRequestDTO.movements.notEmpty=Turi būti įtrauktas bent vienas judėjimas
validation.batchStockMovementRequestDTO.reason.size=Priežastis negali viršyti 1000 simbolių
validation.changePasswordRequestDTO.newPassword.notBlank=Naujas slaptažodis yra privalomas
validation.changePasswordRequestDTO.newPassword.size=Naujas slaptažodis turi būti bent 6 simbolių ilgio
validation.inventoryAudit.actionDescription.size=Aprašymas negali viršyti 500 simbolių
validation.inventoryAudit.product.notNull=Produktas yra privalomas
validation.inventoryAudit.quantity.notNull=Kiekis yra privalomas
validation.inventoryAudit.unknown.notBlank=Judėjimo tipas yra privalomas
validation.inventoryMovementRequestDTO.movementType.notNull=Judėjimo tipas yra privalomas
validation.inventoryMovementRequestDTO.productId.notNull=Produkto ID yra privalomas
validation.inventoryMovementRequestDTO.quantity.decimalMax=Kiekis negali viršyti 9 999 999,99
validation.inventoryMovementRequestDTO.quantity.notNull=Kiekis yra privalomas
validation.inventoryMovementRequestDTO.quantity.positive=Kiekis turi būti didesnis nei nulis
validation.inventoryMovementRequestDTO.userId.notNull=Vartotojo ID yra privalomas
validation.jwtProperties.expiration.positive=JWT galiojimo laikas turi būti teigiama reikšmė
validation.jwtProperties.secret.notBlank=JWT paslaptis yra privaloma
validation.loginRequestDTO.name.notBlank=Vartotojo vardas yra privalomas
validation.loginRequestDTO.password.notBlank=Slaptažodis yra privalomas
validation.order.orderDate.notNull=Užsakymo data yra privaloma
validation.order.orderDate.pastOrPresent=Užsakymo data negali būti ateityje
validation.order.status.notBlank=Būsena yra privaloma
validation.order.users.notNull=Vartotojas yra privalomas
validation.orderAudit.action.notBlank=Veiksmas yra privalomas
validation.orderAudit.details.size=Išsami informacija negali viršyti 1000 simbolių
validation.orderDetail.order.notNull=Užsakymas yra privalomas
validation.orderDetail.product.notNull=Produktas yra privalomas
validation.orderDetail.quantity.decimalMin=Kiekis turi būti didesnis nei 0
validation.orderDetail.quantity.notNull=Prašomas kiekis yra privalomas
validation.orderDetail.quantityReceived.decimalMin=Gautas kiekis negali būti neigiamas
validation.orderDetailRequestDTO.productId.notNull=Produkto ID yra privalomas
validation.orderDetailRequestDTO.quantity.decimalMin=Kiekis turi būti didesnis nei nulis
validation.orderDetailRequestDTO.quantity.digits=Kiekis gali turėti daugiausia 10 sveikųjų skaičių ir 3 dešimtaines dalis
validation.orderDetailRequestDTO.quantity.notNull=Kiekis yra privalomas
validation.orderReceptionDetailRequestDTO.productId.notNull=Produkto ID yra privalomas
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Gautas kiekis yra privalomas
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Gautas kiekis turi būti nulis arba didesnis
validation.orderReceptionRequestDTO.items.notEmpty=Turi būti nurodytas bent vienas gautas produktas
validation.orderReceptionRequestDTO.orderId.notNull=Užsakymo ID yra privalomas
validation.orderReceptionRequestDTO.status.notNull=Būsena yra privaloma
validation.orderRequestDTO.details.notEmpty=Užsakymas turi turėti bent vieną detalę
validation.orderRequestDTO.userId.notNull=Vartotojo ID yra privalomas
validation.product.availabilityPercentage.decimalMax=Prieinamumo procentas negali viršyti 100
validation.product.availabilityPercentage.decimalMin=Prieinamumo procentas negali būti neigiamas
validation.product.availabilityPercentage.digits=Neteisingas prieinamumo formatas
validation.product.currentStock.decimalMin=Atsargos negali būti neigiamos
validation.product.currentStock.digits=Neteisingas atsargų formatas
validation.product.currentStock.notNull=Dabartinės atsargos yra privalomos
validation.product.minimumStock.decimalMin=Minimalios atsargos negali būti neigiamos
validation.product.minimumStock.digits=Neteisingas minimalių atsargų formatas
validation.product.name.notBlank=Produkto pavadinimas yra privalomas
validation.product.name.size=Turi būti nuo 2 iki 100 simbolių
validation.product.productCode.notBlank=Produkto kodas yra privalomas
validation.product.unit.notBlank=Matavimo vienetas yra privalomas
validation.product.unitPrice.decimalMin=Kaina turi būti didesnė nei 0
validation.product.unitPrice.digits=Neteisingas kainos formatas
validation.product.unitPrice.notNull=Vieneto kaina yra privaloma
validation.productRequestDTO.availabilityPercentage.decimalMax=Prieinamumo procentas negali viršyti 100
validation.productRequestDTO.availabilityPercentage.decimalMin=Prieinamumo procentas negali būti neigiamas
validation.productRequestDTO.availabilityPercentage.digits=Procentas gali turėti daugiausia 3 sveikuosius skaičius ir 2 dešimtaines dalis
validation.productRequestDTO.currentStock.decimalMin=Atsargos negali būti neigiamos
validation.productRequestDTO.currentStock.digits=Atsargos gali turėti daugiausia 10 sveikųjų skaičių ir 3 dešimtaines dalis
validation.productRequestDTO.currentStock.notNull=Dabartinės atsargos yra privalomos
validation.productRequestDTO.minimumStock.decimalMin=Minimalios atsargos negali būti neigiamos
validation.productRequestDTO.minimumStock.digits=Minimalios atsargos gali turėti daugiausia 10 sveikųjų skaičių ir 3 dešimtaines dalis
validation.productRequestDTO.minimumStock.notNull=Minimalios atsargos yra privalomos
validation.productRequestDTO.name.notBlank=Produkto pavadinimas yra privalomas
validation.productRequestDTO.name.size=Turi būti nuo 2 iki 100 simbolių
validation.productRequestDTO.productCode.notBlank=Produkto kodas yra privalomas
validation.productRequestDTO.productCode.size=Kodas negali viršyti 50 simbolių
validation.productRequestDTO.unit.notBlank=Matavimo vienetas yra privalomas
validation.productRequestDTO.unit.size=Vienetas negali viršyti 20 simbolių
validation.productRequestDTO.unitPrice.decimalMin=Kaina turi būti didesnė nei nulis
validation.productRequestDTO.unitPrice.digits=Kaina gali turėti daugiausia 10 sveikųjų skaičių ir 2 dešimtaines dalis
validation.productRequestDTO.unitPrice.notNull=Vieneto kaina yra privaloma
validation.recipe.elaboration.size=Paruošimas negali viršyti 2000 simbolių
validation.recipe.name.notBlank=Recepto pavadinimas yra privalomas
validation.recipe.name.size=Turi būti nuo 2 iki 150 simbolių
validation.recipe.presentation.size=Pateikimas negali viršyti 1000 simbolių
validation.recipe.totalCost.decimalMin=Išlaidos negali būti neigiamos
validation.recipeAudit.action.notBlank=Veiksmas yra privalomas
validation.recipeAudit.details.size=Išsami informacija negali viršyti 1000 simbolių
validation.recipeComponent.parentRecipe.notNull=Receptas yra privalomas
validation.recipeComponent.product.notNull=Produktas yra privalomas
validation.recipeComponent.quantity.decimalMin=Kiekis turi būti didesnis nei 0
validation.recipeComponent.quantity.notNull=Kiekis yra privalomas
validation.recipeComponentRequestDTO.productId.notNull=Produkto ID yra privalomas
validation.recipeComponentRequestDTO.quantity.decimalMin=Kiekis turi būti didesnis nei nulis
validation.recipeComponentRequestDTO.quantity.digits=Kiekis gali turėti daugiausia 10 sveikųjų skaičių ir 3 dešimtaines dalis
validation.recipeComponentRequestDTO.quantity.notNull=Kiekis yra privalomas
validation.recipeCookingAudit.details.size=Išsami informacija negali viršyti 1000 simbolių
validation.recipeCookingAudit.quantityCooked.decimalMin=Kiekis turi būti didesnis nei 0
validation.recipeCookingAudit.quantityCooked.notNull=Pagamintas kiekis yra privalomas
validation.recipeCookingAudit.recipe.notNull=Receptas yra privalomas
validation.recipeCookingRequestDTO.details.size=Išsami informacija negali viršyti 500 simbolių
validation.recipeCookingRequestDTO.quantity.decimalMin=Kiekis turi būti didesnis nei 0
validation.recipeCookingRequestDTO.quantity.digits=Kiekis gali turėti daugiausia 10 sveikųjų skaičių ir 3 dešimtaines dalis
validation.recipeCookingRequestDTO.quantity.notNull=Kiekis gaminimui yra privalomas
validation.recipeCookingRequestDTO.recipeId.notNull=Recepto ID yra privalomas
validation.recipeCookingRequestDTO.recipeId.positive=Recepto ID turi būti teigiamas
validation.recipeRequestDTO.components.notEmpty=Recepte turi būti bent vienas komponentas
validation.recipeRequestDTO.elaboration.notBlank=Paruošimas yra privalomas
validation.recipeRequestDTO.elaboration.size=Paruošimas negali viršyti 2000 simbolių
validation.recipeRequestDTO.name.notBlank=Recepto pavadinimas yra privalomas
validation.recipeRequestDTO.name.size=Turi būti nuo 2 iki 150 simbolių
validation.recipeRequestDTO.presentation.notBlank=Pateikimas yra privalomas
validation.recipeRequestDTO.presentation.size=Pateikimas negali viršyti 1000 simbolių
validation.roleEscalationRequestDTO.durationMinutes.max=Maksimali leistina trukmė yra 1440 minučių (24 valandos)
validation.roleEscalationRequestDTO.durationMinutes.min=Minimali trukmė turi būti 1 minutė
validation.roleEscalationRequestDTO.durationMinutes.notNull=Trukmė minutėmis yra privaloma
validation.stockLedger.currentHash.notBlank=Dabartinė maiša (hash) yra privaloma
validation.stockLedger.movementType.notNull=Judėjimo tipas yra privalomas
validation.stockLedger.previousHash.notBlank=Ankstesnė maiša (hash) yra privaloma
validation.stockLedger.product.notNull=Produktas yra privalomas
validation.stockLedger.quantityDelta.notNull=Kiekis yra privalomas
validation.stockLedger.resultingStock.notNull=Gaunamos atsargos yra privalomos
validation.stockLedger.sequenceNumber.notNull=Sekos numeris yra privalomas
validation.stockLedger.transactionTimestamp.notNull=Laiko žyma yra privaloma
validation.stockMovementItemDTO.description.size=Aprašymas negali viršyti 500 simbolių
validation.stockMovementItemDTO.movementType.notNull=Judėjimo tipas yra privalomas
validation.stockMovementItemDTO.productId.notNull=Produkto ID yra privalomas
validation.stockMovementItemDTO.quantityDelta.digits=Kiekis gali turėti daugiausia 10 sveikųjų skaičių ir 3 dešimtaines dalis
validation.stockMovementItemDTO.quantityDelta.notNull=Kiekis yra privalomas
validation.stockSnapshot.currentStock.notNull=Dabartinės atsargos yra privalomos
validation.stockSnapshot.integrityStatus.notBlank=Vientisumo būsena yra privaloma
validation.stockSnapshot.lastSequenceNumber.notNull=Sekos numeris yra privalomas
validation.stockSnapshot.lastTransactionHash.notBlank=Paskutinė maiša (hash) yra privaloma
validation.stockSnapshot.lastUpdated.notNull=Atnaujinimo data yra privaloma
validation.supplier.name.notBlank=Tiekėjo pavadinimas yra privalomas
validation.supplier.name.size=Turi būti nuo 2 iki 100 simbolių
validation.supplierRequestDTO.name.notBlank=Tiekėjo pavadinimas yra privalomas
validation.supplierRequestDTO.name.size=Turi būti nuo 2 iki 100 simbolių
validation.user.name.notBlank=Vardas yra privalomas
validation.user.name.size=Turi būti nuo 2 iki 100 simbolių
validation.user.password.notBlank=Slaptažodis yra privalomas
validation.user.role.notNull=Vaidmuo yra privalomas
validation.user.user.notBlank=Vartotojo vardas yra privalomas
validation.userRequestDTO.name.notBlank=Vardas yra privalomas
validation.userRequestDTO.name.size=Turi būti nuo 2 iki 100 simbolių
validation.userRequestDTO.password.notBlank=Slaptažodis yra privalomas
validation.userRequestDTO.password.size=Slaptažodis turi būti bent 6 simbolių ilgio
validation.userRequestDTO.user.notBlank=Vartotojo vardas yra privalomas
validation.userRequestDTO.user.size=Vartotojo vardas negali viršyti 100 simbolių
""",

"el": """validation.allergen.name.notBlank=Το όνομα αλλεργιογόνου είναι υποχρεωτικό
validation.allergen.name.size=Πρέπει να είναι μεταξύ 2 και 50 χαρακτήρων
validation.allergenRequestDTO.name.notBlank=Το όνομα αλλεργιογόνου είναι υποχρεωτικό
validation.allergenRequestDTO.name.size=Πρέπει να είναι μεταξύ 2 και 50 χαρακτήρων
validation.batchStockMovementRequestDTO.movements.notEmpty=Πρέπει να συμπεριληφθεί τουλάχιστον μία κίνηση
validation.batchStockMovementRequestDTO.reason.size=Η αιτιολογία δεν μπορεί να υπερβαίνει τους 1000 χαρακτήρες
validation.changePasswordRequestDTO.newPassword.notBlank=Ο νέος κωδικός πρόσβασης είναι υποχρεωτικός
validation.changePasswordRequestDTO.newPassword.size=Ο νέος κωδικός πρόσβασης πρέπει να έχει τουλάχιστον 6 χαρακτήρες
validation.inventoryAudit.actionDescription.size=Η περιγραφή δεν μπορεί να υπερβαίνει τους 500 χαρακτήρες
validation.inventoryAudit.product.notNull=Το προϊόν είναι υποχρεωτικό
validation.inventoryAudit.quantity.notNull=Η ποσότητα είναι υποχρεωτική
validation.inventoryAudit.unknown.notBlank=Ο τύπος κίνησης είναι υποχρεωτικός
validation.inventoryMovementRequestDTO.movementType.notNull=Ο τύπος κίνησης είναι υποχρεωτικός
validation.inventoryMovementRequestDTO.productId.notNull=Το ID του προϊόντος είναι υποχρεωτικό
validation.inventoryMovementRequestDTO.quantity.decimalMax=Η ποσότητα δεν μπορεί να υπερβαίνει τα 9.999.999,99
validation.inventoryMovementRequestDTO.quantity.notNull=Η ποσότητα είναι υποχρεωτική
validation.inventoryMovementRequestDTO.quantity.positive=Η ποσότητα πρέπει να είναι μεγαλύτερη από μηδέν
validation.inventoryMovementRequestDTO.userId.notNull=Το ID χρήστη είναι υποχρεωτικό
validation.jwtProperties.expiration.positive=Η λήξη JWT πρέπει να είναι θετική τιμή
validation.jwtProperties.secret.notBlank=Το μυστικό JWT είναι υποχρεωτικό
validation.loginRequestDTO.name.notBlank=Το όνομα χρήστη είναι υποχρεωτικό
validation.loginRequestDTO.password.notBlank=Ο κωδικός πρόσβασης είναι υποχρεωτικός
validation.order.orderDate.notNull=Η ημερομηνία παραγγελίας είναι υποχρεωτική
validation.order.orderDate.pastOrPresent=Η ημερομηνία παραγγελίας δεν μπορεί να είναι στο μέλλον
validation.order.status.notBlank=Η κατάσταση είναι υποχρεωτική
validation.order.users.notNull=Ο χρήστης είναι υποχρεωτικός
validation.orderAudit.action.notBlank=Η ενέργεια είναι υποχρεωτική
validation.orderAudit.details.size=Οι λεπτομέρειες δεν μπορούν να υπερβαίνουν τους 1000 χαρακτήρες
validation.orderDetail.order.notNull=Η παραγγελία είναι υποχρεωτική
validation.orderDetail.product.notNull=Το προϊόν είναι υποχρεωτικό
validation.orderDetail.quantity.decimalMin=Η ποσότητα πρέπει να είναι μεγαλύτερη από 0
validation.orderDetail.quantity.notNull=Η ζητούμενη ποσότητα είναι υποχρεωτική
validation.orderDetail.quantityReceived.decimalMin=Η παραληφθείσα ποσότητα δεν μπορεί να είναι αρνητική
validation.orderDetailRequestDTO.productId.notNull=Το ID του προϊόντος είναι υποχρεωτικό
validation.orderDetailRequestDTO.quantity.decimalMin=Η ποσότητα πρέπει να είναι μεγαλύτερη από μηδέν
validation.orderDetailRequestDTO.quantity.digits=Η ποσότητα μπορεί να έχει το πολύ 10 ακέραιους και 3 δεκαδικά ψηφία
validation.orderDetailRequestDTO.quantity.notNull=Η ποσότητα είναι υποχρεωτική
validation.orderReceptionDetailRequestDTO.productId.notNull=Το ID του προϊόντος είναι υποχρεωτικό
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Η παραληφθείσα ποσότητα είναι υποχρεωτική
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Η παραληφθείσα ποσότητα πρέπει να είναι μηδέν ή μεγαλύτερη
validation.orderReceptionRequestDTO.items.notEmpty=Πρέπει να καθοριστεί τουλάχιστον ένα παραληφθέν προϊόν
validation.orderReceptionRequestDTO.orderId.notNull=Το ID της παραγγελίας είναι υποχρεωτικό
validation.orderReceptionRequestDTO.status.notNull=Η κατάσταση είναι υποχρεωτική
validation.orderRequestDTO.details.notEmpty=Η παραγγελία πρέπει να έχει τουλάχιστον μία λεπτομέρεια
validation.orderRequestDTO.userId.notNull=Το ID χρήστη είναι υποχρεωτικό
validation.product.availabilityPercentage.decimalMax=Το ποσοστό διαθεσιμότητας δεν μπορεί να υπερβαίνει το 100
validation.product.availabilityPercentage.decimalMin=Το ποσοστό διαθεσιμότητας δεν μπορεί να είναι αρνητικό
validation.product.availabilityPercentage.digits=Μη έγκυρη μορφή διαθεσιμότητας
validation.product.currentStock.decimalMin=Το απόθεμα δεν μπορεί να είναι αρνητικό
validation.product.currentStock.digits=Μη έγκυρη μορφή αποθέματος
validation.product.currentStock.notNull=Το τρέχον απόθεμα είναι υποχρεωτικό
validation.product.minimumStock.decimalMin=Το ελάχιστο απόθεμα δεν μπορεί να είναι αρνητικό
validation.product.minimumStock.digits=Μη έγκυρη μορφή ελάχιστου αποθέματος
validation.product.name.notBlank=Το όνομα του προϊόντος είναι υποχρεωτικό
validation.product.name.size=Πρέπει να είναι μεταξύ 2 και 100 χαρακτήρων
validation.product.productCode.notBlank=Ο κωδικός προϊόντος είναι υποχρεωτικός
validation.product.unit.notBlank=Η μονάδα μέτρησης είναι υποχρεωτική
validation.product.unitPrice.decimalMin=Η τιμή πρέπει να είναι μεγαλύτερη από 0
validation.product.unitPrice.digits=Μη έγκυρη μορφή τιμής
validation.product.unitPrice.notNull=Η τιμή μονάδας είναι υποχρεωτική
validation.productRequestDTO.availabilityPercentage.decimalMax=Το ποσοστό διαθεσιμότητας δεν μπορεί να υπερβαίνει το 100
validation.productRequestDTO.availabilityPercentage.decimalMin=Το ποσοστό διαθεσιμότητας δεν μπορεί να είναι αρνητικό
validation.productRequestDTO.availabilityPercentage.digits=Το ποσοστό μπορεί να έχει το πολύ 3 ακέραιους και 2 δεκαδικά ψηφία
validation.productRequestDTO.currentStock.decimalMin=Το απόθεμα δεν μπορεί να είναι αρνητικό
validation.productRequestDTO.currentStock.digits=Το απόθεμα μπορεί να έχει το πολύ 10 ακέραιους και 3 δεκαδικά ψηφία
validation.productRequestDTO.currentStock.notNull=Το τρέχον απόθεμα είναι υποχρεωτικό
validation.productRequestDTO.minimumStock.decimalMin=Το ελάχιστο απόθεμα δεν μπορεί να είναι αρνητικό
validation.productRequestDTO.minimumStock.digits=Το ελάχιστο απόθεμα μπορεί να έχει το πολύ 10 ακέραιους και 3 δεκαδικά ψηφία
validation.productRequestDTO.minimumStock.notNull=Το ελάχιστο απόθεμα είναι υποχρεωτικό
validation.productRequestDTO.name.notBlank=Το όνομα του προϊόντος είναι υποχρεωτικό
validation.productRequestDTO.name.size=Πρέπει να είναι μεταξύ 2 και 100 χαρακτήρων
validation.productRequestDTO.productCode.notBlank=Ο κωδικός προϊόντος είναι υποχρεωτικός
validation.productRequestDTO.productCode.size=Ο κωδικός δεν μπορεί να υπερβαίνει τους 50 χαρακτήρες
validation.productRequestDTO.unit.notBlank=Η μονάδα μέτρησης είναι υποχρεωτική
validation.productRequestDTO.unit.size=Η μονάδα δεν μπορεί να υπερβαίνει τους 20 χαρακτήρες
validation.productRequestDTO.unitPrice.decimalMin=Η τιμή πρέπει να είναι μεγαλύτερη από μηδέν
validation.productRequestDTO.unitPrice.digits=Η τιμή μπορεί να έχει το πολύ 10 ακέραιους και 2 δεκαδικά ψηφία
validation.productRequestDTO.unitPrice.notNull=Η τιμή μονάδας είναι υποχρεωτική
validation.recipe.elaboration.size=Η παρασκευή δεν μπορεί να υπερβαίνει τους 2000 χαρακτήρες
validation.recipe.name.notBlank=Το όνομα της συνταγής είναι υποχρεωτικό
validation.recipe.name.size=Πρέπει να είναι μεταξύ 2 και 150 χαρακτήρων
validation.recipe.presentation.size=Η παρουσίαση δεν μπορεί να υπερβαίνει τους 1000 χαρακτήρες
validation.recipe.totalCost.decimalMin=Το κόστος δεν μπορεί να είναι αρνητικό
validation.recipeAudit.action.notBlank=Η ενέργεια είναι υποχρεωτική
validation.recipeAudit.details.size=Οι λεπτομέρειες δεν μπορούν να υπερβαίνουν τους 1000 χαρακτήρες
validation.recipeComponent.parentRecipe.notNull=Η συνταγή είναι υποχρεωτική
validation.recipeComponent.product.notNull=Το προϊόν είναι υποχρεωτικό
validation.recipeComponent.quantity.decimalMin=Η ποσότητα πρέπει να είναι μεγαλύτερη από 0
validation.recipeComponent.quantity.notNull=Η ποσότητα είναι υποχρεωτική
validation.recipeComponentRequestDTO.productId.notNull=Το ID του προϊόντος είναι υποχρεωτικό
validation.recipeComponentRequestDTO.quantity.decimalMin=Η ποσότητα πρέπει να είναι μεγαλύτερη από μηδέν
validation.recipeComponentRequestDTO.quantity.digits=Η ποσότητα μπορεί να έχει το πολύ 10 ακέραιους και 3 δεκαδικά ψηφία
validation.recipeComponentRequestDTO.quantity.notNull=Η ποσότητα είναι υποχρεωτική
validation.recipeCookingAudit.details.size=Οι λεπτομέρειες δεν μπορούν να υπερβαίνουν τους 1000 χαρακτήρες
validation.recipeCookingAudit.quantityCooked.decimalMin=Η ποσότητα πρέπει να είναι μεγαλύτερη από 0
validation.recipeCookingAudit.quantityCooked.notNull=Η μαγειρεμένη ποσότητα είναι υποχρεωτική
validation.recipeCookingAudit.recipe.notNull=Η συνταγή είναι υποχρεωτική
validation.recipeCookingRequestDTO.details.size=Οι λεπτομέρειες δεν μπορούν να υπερβαίνουν τους 500 χαρακτήρες
validation.recipeCookingRequestDTO.quantity.decimalMin=Η ποσότητα πρέπει να είναι μεγαλύτερη από 0
validation.recipeCookingRequestDTO.quantity.digits=Η ποσότητα μπορεί να έχει το πολύ 10 ακέραιους και 3 δεκαδικά ψηφία
validation.recipeCookingRequestDTO.quantity.notNull=Η ποσότητα για μαγείρεμα είναι υποχρεωτική
validation.recipeCookingRequestDTO.recipeId.notNull=Το ID της συνταγής είναι υποχρεωτικό
validation.recipeCookingRequestDTO.recipeId.positive=Το ID της συνταγής πρέπει να είναι θετικό
validation.recipeRequestDTO.components.notEmpty=Η συνταγή πρέπει να περιλαμβάνει τουλάχιστον ένα συστατικό
validation.recipeRequestDTO.elaboration.notBlank=Η παρασκευή είναι υποχρεωτική
validation.recipeRequestDTO.elaboration.size=Η παρασκευή δεν μπορεί να υπερβαίνει τους 2000 χαρακτήρες
validation.recipeRequestDTO.name.notBlank=Το όνομα της συνταγής είναι υποχρεωτικό
validation.recipeRequestDTO.name.size=Πρέπει να είναι μεταξύ 2 και 150 χαρακτήρων
validation.recipeRequestDTO.presentation.notBlank=Η παρουσίαση είναι υποχρεωτική
validation.recipeRequestDTO.presentation.size=Η παρουσίαση δεν μπορεί να υπερβαίνει τους 1000 χαρακτήρες
validation.roleEscalationRequestDTO.durationMinutes.max=Η μέγιστη επιτρεπόμενη διάρκεια είναι 1440 λεπτά (24 ώρες)
validation.roleEscalationRequestDTO.durationMinutes.min=Η ελάχιστη διάρκεια πρέπει να είναι 1 λεπτό
validation.roleEscalationRequestDTO.durationMinutes.notNull=Η διάρκεια σε λεπτά είναι υποχρεωτική
validation.stockLedger.currentHash.notBlank=Το τρέχον hash είναι υποχρεωτικό
validation.stockLedger.movementType.notNull=Ο τύπος κίνησης είναι υποχρεωτικός
validation.stockLedger.previousHash.notBlank=Το προηγούμενο hash είναι υποχρεωτικό
validation.stockLedger.product.notNull=Το προϊόν είναι υποχρεωτικό
validation.stockLedger.quantityDelta.notNull=Η ποσότητα είναι υποχρεωτική
validation.stockLedger.resultingStock.notNull=Το προκύπτον απόθεμα είναι υποχρεωτικό
validation.stockLedger.sequenceNumber.notNull=Ο αριθμός ακολουθίας είναι υποχρεωτικός
validation.stockLedger.transactionTimestamp.notNull=Η χρονική σήμανση είναι υποχρεωτική
validation.stockMovementItemDTO.description.size=Η περιγραφή δεν μπορεί να υπερβαίνει τους 500 χαρακτήρες
validation.stockMovementItemDTO.movementType.notNull=Ο τύπος κίνησης είναι υποχρεωτικός
validation.stockMovementItemDTO.productId.notNull=Το ID του προϊόντος είναι υποχρεωτικό
validation.stockMovementItemDTO.quantityDelta.digits=Η ποσότητα μπορεί να έχει το πολύ 10 ακέραιους και 3 δεκαδικά ψηφία
validation.stockMovementItemDTO.quantityDelta.notNull=Η ποσότητα είναι υποχρεωτική
validation.stockSnapshot.currentStock.notNull=Το τρέχον απόθεμα είναι υποχρεωτικό
validation.stockSnapshot.integrityStatus.notBlank=Η κατάσταση ακεραιότητας είναι υποχρεωτική
validation.stockSnapshot.lastSequenceNumber.notNull=Ο αριθμός ακολουθίας είναι υποχρεωτικός
validation.stockSnapshot.lastTransactionHash.notBlank=Το τελευταίο hash είναι υποχρεωτικό
validation.stockSnapshot.lastUpdated.notNull=Η ημερομηνία ενημέρωσης είναι υποχρεωτική
validation.supplier.name.notBlank=Το όνομα του προμηθευτή είναι υποχρεωτικό
validation.supplier.name.size=Πρέπει να είναι μεταξύ 2 και 100 χαρακτήρων
validation.supplierRequestDTO.name.notBlank=Το όνομα του προμηθευτή είναι υποχρεωτικό
validation.supplierRequestDTO.name.size=Πρέπει να είναι μεταξύ 2 και 100 χαρακτήρων
validation.user.name.notBlank=Το όνομα είναι υποχρεωτικό
validation.user.name.size=Πρέπει να είναι μεταξύ 2 και 100 χαρακτήρων
validation.user.password.notBlank=Ο κωδικός πρόσβασης είναι υποχρεωτικός
validation.user.role.notNull=Ο ρόλος είναι υποχρεωτικός
validation.user.user.notBlank=Το όνομα χρήστη είναι υποχρεωτικό
validation.userRequestDTO.name.notBlank=Το όνομα είναι υποχρεωτικό
validation.userRequestDTO.name.size=Πρέπει να είναι μεταξύ 2 και 100 χαρακτήρων
validation.userRequestDTO.password.notBlank=Ο κωδικός πρόσβασης είναι υποχρεωτικός
validation.userRequestDTO.password.size=Ο κωδικός πρόσβασης πρέπει να έχει τουλάχιστον 6 χαρακτήρες
validation.userRequestDTO.user.notBlank=Το όνομα χρήστη είναι υποχρεωτικό
validation.userRequestDTO.user.size=Το όνομα χρήστη δεν μπορεί να υπερβαίνει τους 100 χαρακτήρες
"""
}

for lang, content in FILES.items():
    path = os.path.join(VDIR, f"ValidationMessages_{lang}.properties")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content.strip() + "\n")
    lines = [l for l in content.strip().split("\n") if "=" in l]
    print(f"  {lang}: wrote {len(lines)} keys")
