#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Writes PT, CA, EU, GL ValidationMessages files."""
import os
VDIR = "src/main/resources/i18n/validation/"
FILES = {
"pt": """validation.allergen.name.notBlank=O nome do alergénio é obrigatório
validation.allergen.name.size=Deve ter entre 2 e 50 caracteres
validation.allergenRequestDTO.name.notBlank=O nome do alergénio é obrigatório
validation.allergenRequestDTO.name.size=Deve ter entre 2 e 50 caracteres
validation.batchStockMovementRequestDTO.movements.notEmpty=Deve incluir pelo menos um movimento
validation.batchStockMovementRequestDTO.reason.size=O motivo não pode exceder 1000 caracteres
validation.changePasswordRequestDTO.newPassword.notBlank=A nova palavra-passe é obrigatória
validation.changePasswordRequestDTO.newPassword.size=A nova palavra-passe deve ter pelo menos 6 caracteres
validation.inventoryAudit.actionDescription.size=A descrição não pode exceder 500 caracteres
validation.inventoryAudit.product.notNull=O produto é obrigatório
validation.inventoryAudit.quantity.notNull=A quantidade é obrigatória
validation.inventoryAudit.unknown.notBlank=O tipo de movimento é obrigatório
validation.inventoryMovementRequestDTO.movementType.notNull=O tipo de movimento é obrigatório
validation.inventoryMovementRequestDTO.productId.notNull=O ID do produto é obrigatório
validation.inventoryMovementRequestDTO.quantity.decimalMax=A quantidade não pode exceder 9.999.999,99
validation.inventoryMovementRequestDTO.quantity.notNull=A quantidade é obrigatória
validation.inventoryMovementRequestDTO.quantity.positive=A quantidade deve ser superior a zero
validation.inventoryMovementRequestDTO.userId.notNull=O ID do utilizador é obrigatório
validation.jwtProperties.expiration.positive=A expiração JWT deve ser um valor positivo
validation.jwtProperties.secret.notBlank=O segredo JWT é obrigatório
validation.loginRequestDTO.name.notBlank=O nome de utilizador é obrigatório
validation.loginRequestDTO.password.notBlank=A palavra-passe é obrigatória
validation.order.orderDate.notNull=A data da encomenda é obrigatória
validation.order.orderDate.pastOrPresent=A data da encomenda não pode ser futura
validation.order.status.notBlank=O estado é obrigatório
validation.order.users.notNull=O utilizador é obrigatório
validation.orderAudit.action.notBlank=A ação é obrigatória
validation.orderAudit.details.size=Os detalhes não podem exceder 1000 caracteres
validation.orderDetail.order.notNull=A encomenda é obrigatória
validation.orderDetail.product.notNull=O produto é obrigatório
validation.orderDetail.quantity.decimalMin=A quantidade deve ser superior a 0
validation.orderDetail.quantity.notNull=A quantidade solicitada é obrigatória
validation.orderDetail.quantityReceived.decimalMin=A quantidade recebida não pode ser negativa
validation.orderDetailRequestDTO.productId.notNull=O ID do produto é obrigatório
validation.orderDetailRequestDTO.quantity.decimalMin=A quantidade deve ser superior a zero
validation.orderDetailRequestDTO.quantity.digits=A quantidade deve ter no máximo 10 dígitos inteiros e 3 decimais
validation.orderDetailRequestDTO.quantity.notNull=A quantidade é obrigatória
validation.orderReceptionDetailRequestDTO.productId.notNull=O ID do produto é obrigatório
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=A quantidade recebida é obrigatória
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=A quantidade recebida deve ser superior ou igual a zero
validation.orderReceptionRequestDTO.items.notEmpty=Deve especificar pelo menos um produto recebido
validation.orderReceptionRequestDTO.orderId.notNull=O ID da encomenda é obrigatório
validation.orderReceptionRequestDTO.status.notNull=O estado é obrigatório
validation.orderRequestDTO.details.notEmpty=A encomenda deve ter pelo menos um detalhe
validation.orderRequestDTO.userId.notNull=O ID do utilizador é obrigatório
validation.product.availabilityPercentage.decimalMax=A percentagem de disponibilidade não pode exceder 100
validation.product.availabilityPercentage.decimalMin=A percentagem de disponibilidade não pode ser negativa
validation.product.availabilityPercentage.digits=Formato de disponibilidade inválido
validation.product.currentStock.decimalMin=O stock não pode ser negativo
validation.product.currentStock.digits=Formato de stock inválido
validation.product.currentStock.notNull=O stock atual é obrigatório
validation.product.minimumStock.decimalMin=O stock mínimo não pode ser negativo
validation.product.minimumStock.digits=Formato de stock mínimo inválido
validation.product.name.notBlank=O nome do produto é obrigatório
validation.product.name.size=Deve ter entre 2 e 100 caracteres
validation.product.productCode.notBlank=O código do produto é obrigatório
validation.product.unit.notBlank=A unidade de medida é obrigatória
validation.product.unitPrice.decimalMin=O preço deve ser superior a 0
validation.product.unitPrice.digits=Formato de preço inválido
validation.product.unitPrice.notNull=O preço unitário é obrigatório
validation.productRequestDTO.availabilityPercentage.decimalMax=A percentagem de disponibilidade não pode exceder 100
validation.productRequestDTO.availabilityPercentage.decimalMin=A percentagem de disponibilidade não pode ser negativa
validation.productRequestDTO.availabilityPercentage.digits=A percentagem deve ter no máximo 3 dígitos inteiros e 2 decimais
validation.productRequestDTO.currentStock.decimalMin=O stock não pode ser negativo
validation.productRequestDTO.currentStock.digits=O stock deve ter no máximo 10 dígitos inteiros e 3 decimais
validation.productRequestDTO.currentStock.notNull=O stock atual é obrigatório
validation.productRequestDTO.minimumStock.decimalMin=O stock mínimo não pode ser negativo
validation.productRequestDTO.minimumStock.digits=O stock mínimo deve ter no máximo 10 dígitos inteiros e 3 decimais
validation.productRequestDTO.minimumStock.notNull=O stock mínimo é obrigatório
validation.productRequestDTO.name.notBlank=O nome do produto é obrigatório
validation.productRequestDTO.name.size=Deve ter entre 2 e 100 caracteres
validation.productRequestDTO.productCode.notBlank=O código do produto é obrigatório
validation.productRequestDTO.productCode.size=O código não pode exceder 50 caracteres
validation.productRequestDTO.unit.notBlank=A unidade de medida é obrigatória
validation.productRequestDTO.unit.size=A unidade não pode exceder 20 caracteres
validation.productRequestDTO.unitPrice.decimalMin=O preço deve ser superior a zero
validation.productRequestDTO.unitPrice.digits=O preço deve ter no máximo 10 dígitos inteiros e 2 decimais
validation.productRequestDTO.unitPrice.notNull=O preço unitário é obrigatório
validation.recipe.elaboration.size=A elaboração não pode exceder 2000 caracteres
validation.recipe.name.notBlank=O nome da receita é obrigatório
validation.recipe.name.size=Deve ter entre 2 e 150 caracteres
validation.recipe.presentation.size=A apresentação não pode exceder 1000 caracteres
validation.recipe.totalCost.decimalMin=O custo não pode ser negativo
validation.recipeAudit.action.notBlank=A ação é obrigatória
validation.recipeAudit.details.size=Os detalhes não podem exceder 1000 caracteres
validation.recipeComponent.parentRecipe.notNull=A receita é obrigatória
validation.recipeComponent.product.notNull=O produto é obrigatório
validation.recipeComponent.quantity.decimalMin=A quantidade deve ser superior a 0
validation.recipeComponent.quantity.notNull=A quantidade é obrigatória
validation.recipeComponentRequestDTO.productId.notNull=O ID do produto é obrigatório
validation.recipeComponentRequestDTO.quantity.decimalMin=A quantidade deve ser superior a zero
validation.recipeComponentRequestDTO.quantity.digits=A quantidade deve ter no máximo 10 dígitos inteiros e 3 decimais
validation.recipeComponentRequestDTO.quantity.notNull=A quantidade é obrigatória
validation.recipeCookingAudit.details.size=Os detalhes não podem exceder 1000 caracteres
validation.recipeCookingAudit.quantityCooked.decimalMin=A quantidade deve ser superior a 0
validation.recipeCookingAudit.quantityCooked.notNull=A quantidade cozinhada é obrigatória
validation.recipeCookingAudit.recipe.notNull=A receita é obrigatória
validation.recipeCookingRequestDTO.details.size=Os detalhes não podem exceder 500 caracteres
validation.recipeCookingRequestDTO.quantity.decimalMin=A quantidade deve ser superior a 0
validation.recipeCookingRequestDTO.quantity.digits=A quantidade deve ter no máximo 10 dígitos inteiros e 3 decimais
validation.recipeCookingRequestDTO.quantity.notNull=A quantidade a cozinhar é obrigatória
validation.recipeCookingRequestDTO.recipeId.notNull=O ID da receita é obrigatório
validation.recipeCookingRequestDTO.recipeId.positive=O ID da receita deve ser positivo
validation.recipeRequestDTO.components.notEmpty=A receita deve incluir pelo menos um componente
validation.recipeRequestDTO.elaboration.notBlank=A elaboração é obrigatória
validation.recipeRequestDTO.elaboration.size=A elaboração não pode exceder 2000 caracteres
validation.recipeRequestDTO.name.notBlank=O nome da receita é obrigatório
validation.recipeRequestDTO.name.size=Deve ter entre 2 e 150 caracteres
validation.recipeRequestDTO.presentation.notBlank=A apresentação é obrigatória
validation.recipeRequestDTO.presentation.size=A apresentação não pode exceder 1000 caracteres
validation.roleEscalationRequestDTO.durationMinutes.max=A duração máxima permitida é de 1440 minutos (24 horas)
validation.roleEscalationRequestDTO.durationMinutes.min=A duração mínima deve ser de 1 minuto
validation.roleEscalationRequestDTO.durationMinutes.notNull=A duração em minutos é obrigatória
validation.stockLedger.currentHash.notBlank=O hash atual é obrigatório
validation.stockLedger.movementType.notNull=O tipo de movimento é obrigatório
validation.stockLedger.previousHash.notBlank=O hash anterior é obrigatório
validation.stockLedger.product.notNull=O produto é obrigatório
validation.stockLedger.quantityDelta.notNull=A quantidade é obrigatória
validation.stockLedger.resultingStock.notNull=O stock resultante é obrigatório
validation.stockLedger.sequenceNumber.notNull=O número de sequência é obrigatório
validation.stockLedger.transactionTimestamp.notNull=O timestamp é obrigatório
validation.stockMovementItemDTO.description.size=A descrição não pode exceder 500 caracteres
validation.stockMovementItemDTO.movementType.notNull=O tipo de movimento é obrigatório
validation.stockMovementItemDTO.productId.notNull=O ID do produto é obrigatório
validation.stockMovementItemDTO.quantityDelta.digits=A quantidade deve ter no máximo 10 dígitos inteiros e 3 decimais
validation.stockMovementItemDTO.quantityDelta.notNull=A quantidade é obrigatória
validation.stockSnapshot.currentStock.notNull=O stock atual é obrigatório
validation.stockSnapshot.integrityStatus.notBlank=O estado de integridade é obrigatório
validation.stockSnapshot.lastSequenceNumber.notNull=O número de sequência é obrigatório
validation.stockSnapshot.lastTransactionHash.notBlank=O último hash é obrigatório
validation.stockSnapshot.lastUpdated.notNull=A data de atualização é obrigatória
validation.supplier.name.notBlank=O nome do fornecedor é obrigatório
validation.supplier.name.size=Deve ter entre 2 e 100 caracteres
validation.supplierRequestDTO.name.notBlank=O nome do fornecedor é obrigatório
validation.supplierRequestDTO.name.size=Deve ter entre 2 e 100 caracteres
validation.user.name.notBlank=O nome é obrigatório
validation.user.name.size=Deve ter entre 2 e 100 caracteres
validation.user.password.notBlank=A palavra-passe é obrigatória
validation.user.role.notNull=O papel é obrigatório
validation.user.user.notBlank=O utilizador é obrigatório
validation.userRequestDTO.name.notBlank=O nome é obrigatório
validation.userRequestDTO.name.size=Deve ter entre 2 e 100 caracteres
validation.userRequestDTO.password.notBlank=A palavra-passe é obrigatória
validation.userRequestDTO.password.size=A palavra-passe deve ter pelo menos 6 caracteres
validation.userRequestDTO.user.notBlank=O utilizador é obrigatório
validation.userRequestDTO.user.size=O utilizador não pode exceder 100 caracteres
""",

"ca": """validation.allergen.name.notBlank=El nom de l'al·lergen és obligatori
validation.allergen.name.size=Ha de tenir entre 2 i 50 caràcters
validation.allergenRequestDTO.name.notBlank=El nom de l'al·lergen és obligatori
validation.allergenRequestDTO.name.size=Ha de tenir entre 2 i 50 caràcters
validation.batchStockMovementRequestDTO.movements.notEmpty=Cal incloure almenys un moviment
validation.batchStockMovementRequestDTO.reason.size=El motiu no pot excedir 1000 caràcters
validation.changePasswordRequestDTO.newPassword.notBlank=La nova contrasenya és obligatòria
validation.changePasswordRequestDTO.newPassword.size=La nova contrasenya ha de tenir almenys 6 caràcters
validation.inventoryAudit.actionDescription.size=La descripció no pot excedir 500 caràcters
validation.inventoryAudit.product.notNull=El producte és obligatori
validation.inventoryAudit.quantity.notNull=La quantitat és obligatòria
validation.inventoryAudit.unknown.notBlank=El tipus de moviment és obligatori
validation.inventoryMovementRequestDTO.movementType.notNull=El tipus de moviment és obligatori
validation.inventoryMovementRequestDTO.productId.notNull=L'ID del producte és obligatori
validation.inventoryMovementRequestDTO.quantity.decimalMax=La quantitat no pot superar 9.999.999,99
validation.inventoryMovementRequestDTO.quantity.notNull=La quantitat és obligatòria
validation.inventoryMovementRequestDTO.quantity.positive=La quantitat ha de ser superior a zero
validation.inventoryMovementRequestDTO.userId.notNull=L'ID de l'usuari és obligatori
validation.jwtProperties.expiration.positive=L'expiració JWT ha de ser un valor positiu
validation.jwtProperties.secret.notBlank=El secret JWT és obligatori
validation.loginRequestDTO.name.notBlank=El nom d'usuari és obligatori
validation.loginRequestDTO.password.notBlank=La contrasenya és obligatòria
validation.order.orderDate.notNull=La data de la comanda és obligatòria
validation.order.orderDate.pastOrPresent=La data de la comanda no pot ser futura
validation.order.status.notBlank=L'estat és obligatori
validation.order.users.notNull=L'usuari és obligatori
validation.orderAudit.action.notBlank=L'acció és obligatòria
validation.orderAudit.details.size=Els detalls no poden excedir 1000 caràcters
validation.orderDetail.order.notNull=La comanda és obligatòria
validation.orderDetail.product.notNull=El producte és obligatori
validation.orderDetail.quantity.decimalMin=La quantitat ha de ser superior a 0
validation.orderDetail.quantity.notNull=La quantitat sol·licitada és obligatòria
validation.orderDetail.quantityReceived.decimalMin=La quantitat rebuda no pot ser negativa
validation.orderDetailRequestDTO.productId.notNull=L'ID del producte és obligatori
validation.orderDetailRequestDTO.quantity.decimalMin=La quantitat ha de ser superior a zero
validation.orderDetailRequestDTO.quantity.digits=La quantitat ha de tenir com a màxim 10 dígits sencers i 3 decimals
validation.orderDetailRequestDTO.quantity.notNull=La quantitat és obligatòria
validation.orderReceptionDetailRequestDTO.productId.notNull=L'ID del producte és obligatori
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=La quantitat rebuda és obligatòria
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=La quantitat rebuda ha de ser superior o igual a zero
validation.orderReceptionRequestDTO.items.notEmpty=Cal especificar almenys un producte rebut
validation.orderReceptionRequestDTO.orderId.notNull=L'ID de la comanda és obligatori
validation.orderReceptionRequestDTO.status.notNull=L'estat és obligatori
validation.orderRequestDTO.details.notEmpty=La comanda ha de tenir almenys un detall
validation.orderRequestDTO.userId.notNull=L'ID de l'usuari és obligatori
validation.product.availabilityPercentage.decimalMax=El percentatge de disponibilitat no pot superar 100
validation.product.availabilityPercentage.decimalMin=El percentatge de disponibilitat no pot ser negatiu
validation.product.availabilityPercentage.digits=Format de disponibilitat no vàlid
validation.product.currentStock.decimalMin=L'estoc no pot ser negatiu
validation.product.currentStock.digits=Format d'estoc no vàlid
validation.product.currentStock.notNull=L'estoc actual és obligatori
validation.product.minimumStock.decimalMin=L'estoc mínim no pot ser negatiu
validation.product.minimumStock.digits=Format d'estoc mínim no vàlid
validation.product.name.notBlank=El nom del producte és obligatori
validation.product.name.size=Ha de tenir entre 2 i 100 caràcters
validation.product.productCode.notBlank=El codi del producte és obligatori
validation.product.unit.notBlank=La unitat de mesura és obligatòria
validation.product.unitPrice.decimalMin=El preu ha de ser superior a 0
validation.product.unitPrice.digits=Format de preu no vàlid
validation.product.unitPrice.notNull=El preu unitari és obligatori
validation.productRequestDTO.availabilityPercentage.decimalMax=El percentatge de disponibilitat no pot superar 100
validation.productRequestDTO.availabilityPercentage.decimalMin=El percentatge de disponibilitat no pot ser negatiu
validation.productRequestDTO.availabilityPercentage.digits=El percentatge ha de tenir com a màxim 3 dígits sencers i 2 decimals
validation.productRequestDTO.currentStock.decimalMin=L'estoc no pot ser negatiu
validation.productRequestDTO.currentStock.digits=L'estoc ha de tenir com a màxim 10 dígits sencers i 3 decimals
validation.productRequestDTO.currentStock.notNull=L'estoc actual és obligatori
validation.productRequestDTO.minimumStock.decimalMin=L'estoc mínim no pot ser negatiu
validation.productRequestDTO.minimumStock.digits=L'estoc mínim ha de tenir com a màxim 10 dígits sencers i 3 decimals
validation.productRequestDTO.minimumStock.notNull=L'estoc mínim és obligatori
validation.productRequestDTO.name.notBlank=El nom del producte és obligatori
validation.productRequestDTO.name.size=Ha de tenir entre 2 i 100 caràcters
validation.productRequestDTO.productCode.notBlank=El codi del producte és obligatori
validation.productRequestDTO.productCode.size=El codi no pot excedir 50 caràcters
validation.productRequestDTO.unit.notBlank=La unitat de mesura és obligatòria
validation.productRequestDTO.unit.size=La unitat no pot excedir 20 caràcters
validation.productRequestDTO.unitPrice.decimalMin=El preu ha de ser superior a zero
validation.productRequestDTO.unitPrice.digits=El preu ha de tenir com a màxim 10 dígits sencers i 2 decimals
validation.productRequestDTO.unitPrice.notNull=El preu unitari és obligatori
validation.recipe.elaboration.size=L'elaboració no pot excedir 2000 caràcters
validation.recipe.name.notBlank=El nom de la recepta és obligatori
validation.recipe.name.size=Ha de tenir entre 2 i 150 caràcters
validation.recipe.presentation.size=La presentació no pot excedir 1000 caràcters
validation.recipe.totalCost.decimalMin=El cost no pot ser negatiu
validation.recipeAudit.action.notBlank=L'acció és obligatòria
validation.recipeAudit.details.size=Els detalls no poden excedir 1000 caràcters
validation.recipeComponent.parentRecipe.notNull=La recepta és obligatòria
validation.recipeComponent.product.notNull=El producte és obligatori
validation.recipeComponent.quantity.decimalMin=La quantitat ha de ser superior a 0
validation.recipeComponent.quantity.notNull=La quantitat és obligatòria
validation.recipeComponentRequestDTO.productId.notNull=L'ID del producte és obligatori
validation.recipeComponentRequestDTO.quantity.decimalMin=La quantitat ha de ser superior a zero
validation.recipeComponentRequestDTO.quantity.digits=La quantitat ha de tenir com a màxim 10 dígits sencers i 3 decimals
validation.recipeComponentRequestDTO.quantity.notNull=La quantitat és obligatòria
validation.recipeCookingAudit.details.size=Els detalls no poden excedir 1000 caràcters
validation.recipeCookingAudit.quantityCooked.decimalMin=La quantitat ha de ser superior a 0
validation.recipeCookingAudit.quantityCooked.notNull=La quantitat cuinada és obligatòria
validation.recipeCookingAudit.recipe.notNull=La recepta és obligatòria
validation.recipeCookingRequestDTO.details.size=Els detalls no poden excedir 500 caràcters
validation.recipeCookingRequestDTO.quantity.decimalMin=La quantitat ha de ser superior a 0
validation.recipeCookingRequestDTO.quantity.digits=La quantitat ha de tenir com a màxim 10 dígits sencers i 3 decimals
validation.recipeCookingRequestDTO.quantity.notNull=La quantitat a cuinar és obligatòria
validation.recipeCookingRequestDTO.recipeId.notNull=L'ID de la recepta és obligatori
validation.recipeCookingRequestDTO.recipeId.positive=L'ID de la recepta ha de ser positiu
validation.recipeRequestDTO.components.notEmpty=La recepta ha d'incloure almenys un component
validation.recipeRequestDTO.elaboration.notBlank=L'elaboració és obligatòria
validation.recipeRequestDTO.elaboration.size=L'elaboració no pot excedir 2000 caràcters
validation.recipeRequestDTO.name.notBlank=El nom de la recepta és obligatori
validation.recipeRequestDTO.name.size=Ha de tenir entre 2 i 150 caràcters
validation.recipeRequestDTO.presentation.notBlank=La presentació és obligatòria
validation.recipeRequestDTO.presentation.size=La presentació no pot excedir 1000 caràcters
validation.roleEscalationRequestDTO.durationMinutes.max=La durada màxima permesa és de 1440 minuts (24 hores)
validation.roleEscalationRequestDTO.durationMinutes.min=La durada mínima ha de ser d'1 minut
validation.roleEscalationRequestDTO.durationMinutes.notNull=La durada en minuts és obligatòria
validation.stockLedger.currentHash.notBlank=El hash actual és obligatori
validation.stockLedger.movementType.notNull=El tipus de moviment és obligatori
validation.stockLedger.previousHash.notBlank=El hash anterior és obligatori
validation.stockLedger.product.notNull=El producte és obligatori
validation.stockLedger.quantityDelta.notNull=La quantitat és obligatòria
validation.stockLedger.resultingStock.notNull=L'estoc resultant és obligatori
validation.stockLedger.sequenceNumber.notNull=El número de seqüència és obligatori
validation.stockLedger.transactionTimestamp.notNull=La marca de temps és obligatòria
validation.stockMovementItemDTO.description.size=La descripció no pot excedir 500 caràcters
validation.stockMovementItemDTO.movementType.notNull=El tipus de moviment és obligatori
validation.stockMovementItemDTO.productId.notNull=L'ID del producte és obligatori
validation.stockMovementItemDTO.quantityDelta.digits=La quantitat ha de tenir com a màxim 10 dígits sencers i 3 decimals
validation.stockMovementItemDTO.quantityDelta.notNull=La quantitat és obligatòria
validation.stockSnapshot.currentStock.notNull=L'estoc actual és obligatori
validation.stockSnapshot.integrityStatus.notBlank=L'estat d'integritat és obligatori
validation.stockSnapshot.lastSequenceNumber.notNull=El número de seqüència és obligatori
validation.stockSnapshot.lastTransactionHash.notBlank=L'últim hash és obligatori
validation.stockSnapshot.lastUpdated.notNull=La data d'actualització és obligatòria
validation.supplier.name.notBlank=El nom del proveïdor és obligatori
validation.supplier.name.size=Ha de tenir entre 2 i 100 caràcters
validation.supplierRequestDTO.name.notBlank=El nom del proveïdor és obligatori
validation.supplierRequestDTO.name.size=Ha de tenir entre 2 i 100 caràcters
validation.user.name.notBlank=El nom és obligatori
validation.user.name.size=Ha de tenir entre 2 i 100 caràcters
validation.user.password.notBlank=La contrasenya és obligatòria
validation.user.role.notNull=El rol és obligatori
validation.user.user.notBlank=L'usuari és obligatori
validation.userRequestDTO.name.notBlank=El nom és obligatori
validation.userRequestDTO.name.size=Ha de tenir entre 2 i 100 caràcters
validation.userRequestDTO.password.notBlank=La contrasenya és obligatòria
validation.userRequestDTO.password.size=La contrasenya ha de tenir almenys 6 caràcters
validation.userRequestDTO.user.notBlank=L'usuari és obligatori
validation.userRequestDTO.user.size=L'usuari no pot excedir 100 caràcters
""",
}

for lang, content in FILES.items():
    path = os.path.join(VDIR, f"ValidationMessages_{lang}.properties")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content.strip() + "\n")
    lines = [l for l in content.strip().split("\n") if "=" in l]
    print(f"  {lang}: wrote {len(lines)} keys")
