#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Writes MT, GA ValidationMessages files."""
import os
VDIR = "src/main/resources/i18n/validation/"
FILES = {
"mt": """validation.allergen.name.notBlank=L-isem tal-allerġen huwa obbligatorju
validation.allergen.name.size=Irid ikun bejn 2 u 50 karattru
validation.allergenRequestDTO.name.notBlank=L-isem tal-allerġen huwa obbligatorju
validation.allergenRequestDTO.name.size=Irid ikun bejn 2 u 50 karattru
validation.batchStockMovementRequestDTO.movements.notEmpty=Trid tiġi inkluża mill-inqas moviment wieħed
validation.batchStockMovementRequestDTO.reason.size=Ir-raġuni ma tistax taqbeż l-1000 karattru
validation.changePasswordRequestDTO.newPassword.notBlank=Il-password il-ġdida hija obbligatorja
validation.changePasswordRequestDTO.newPassword.size=Il-password il-ġdida jrid ikollha mill-inqas 6 karattri
validation.inventoryAudit.actionDescription.size=Id-deskrizzjoni ma tistax taqbeż il-500 karattru
validation.inventoryAudit.product.notNull=Il-prodott huwa obbligatorju
validation.inventoryAudit.quantity.notNull=Il-kwantità hija obbligatorja
validation.inventoryAudit.unknown.notBlank=It-tip ta' moviment huwa obbligatorju
validation.inventoryMovementRequestDTO.movementType.notNull=It-tip ta' moviment huwa obbligatorju
validation.inventoryMovementRequestDTO.productId.notNull=L-ID tal-prodott huwa obbligatorju
validation.inventoryMovementRequestDTO.quantity.decimalMax=Il-kwantità ma tistax taqbeż is-9,999,999.99
validation.inventoryMovementRequestDTO.quantity.notNull=Il-kwantità hija obbligatorja
validation.inventoryMovementRequestDTO.quantity.positive=Il-kwantità trid tkun ikbar minn żero
validation.inventoryMovementRequestDTO.userId.notNull=L-ID tal-utent huwa obbligatorju
validation.jwtProperties.expiration.positive=L-iskadenza JWT trid tkun valur pożittiv
validation.jwtProperties.secret.notBlank=Is-sigriet JWT huwa obbligatorju
validation.loginRequestDTO.name.notBlank=L-isem tal-utent huwa obbligatorju
validation.loginRequestDTO.password.notBlank=Il-password hija obbligatorja
validation.order.orderDate.notNull=Id-data tal-ordni hija obbligatorja
validation.order.orderDate.pastOrPresent=Id-data tal-ordni ma tistax tkun fil-futur
validation.order.status.notBlank=L-istatus huwa obbligatorju
validation.order.users.notNull=L-utent huwa obbligatorju
validation.orderAudit.action.notBlank=L-azzjoni hija obbligatorja
validation.orderAudit.details.size=Id-dettalji ma jistgħux jaqbżu l-1000 karattru
validation.orderDetail.order.notNull=L-ordni hija obbligatorja
validation.orderDetail.product.notNull=Il-prodott huwa obbligatorju
validation.orderDetail.quantity.decimalMin=Il-kwantità trid tkun ikbar minn 0
validation.orderDetail.quantity.notNull=Il-kwantità mitluba hija obbligatorja
validation.orderDetail.quantityReceived.decimalMin=Il-kwantità riċevuta ma tistax tkun negattiva
validation.orderDetailRequestDTO.productId.notNull=L-ID tal-prodott huwa obbligatorju
validation.orderDetailRequestDTO.quantity.decimalMin=Il-kwantità trid tkun ikbar minn żero
validation.orderDetailRequestDTO.quantity.digits=Il-kwantità jista' jkollha massimu ta' 10 numri sħaħ u 3 deċimali
validation.orderDetailRequestDTO.quantity.notNull=Il-kwantità hija obbligatorja
validation.orderReceptionDetailRequestDTO.productId.notNull=L-ID tal-prodott huwa obbligatorju
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Il-kwantità riċevuta hija obbligatorja
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Il-kwantità riċevuta trid tkun żero jew ikbar
validation.orderReceptionRequestDTO.items.notEmpty=Irid jiġi speċifikat mill-inqas prodott wieħed riċevut
validation.orderReceptionRequestDTO.orderId.notNull=L-ID tal-ordni huwa obbligatorju
validation.orderReceptionRequestDTO.status.notNull=L-istatus huwa obbligatorju
validation.orderRequestDTO.details.notEmpty=L-ordni jrid ikollha mill-inqas dettall wieħed
validation.orderRequestDTO.userId.notNull=L-ID tal-utent huwa obbligatorju
validation.product.availabilityPercentage.decimalMax=Il-persentaġġ ta' disponibbiltà ma jistax jaqbeż il-100
validation.product.availabilityPercentage.decimalMin=Il-persentaġġ ta' disponibbiltà ma jistax jkun negattiv
validation.product.availabilityPercentage.digits=Format ta' disponibbiltà mhux validu
validation.product.currentStock.decimalMin=L-istokk ma jistax jkun negattiv
validation.product.currentStock.digits=Format ta' stokk mhux validu
validation.product.currentStock.notNull=L-istokk attwali huwa obbligatorju
validation.product.minimumStock.decimalMin=L-istokk minimu ma jistax jkun negattiv
validation.product.minimumStock.digits=Format ta' stokk minimu mhux validu
validation.product.name.notBlank=L-isem tal-prodott huwa obbligatorju
validation.product.name.size=Irid ikun bejn 2 u 100 karattru
validation.product.productCode.notBlank=Il-kodiċi tal-prodott huwa obbligatorju
validation.product.unit.notBlank=L-unità tal-kejl hija obbligatorja
validation.product.unitPrice.decimalMin=Il-prezz irid jkun ikbar minn 0
validation.product.unitPrice.digits=Format ta' prezz mhux validu
validation.product.unitPrice.notNull=Il-prezz tal-unità huwa obbligatorju
validation.productRequestDTO.availabilityPercentage.decimalMax=Il-persentaġġ ta' disponibbiltà ma jistax jaqbeż il-100
validation.productRequestDTO.availabilityPercentage.decimalMin=Il-persentaġġ ta' disponibbiltà ma jistax jkun negattiv
validation.productRequestDTO.availabilityPercentage.digits=Il-persentaġġ jista' jkollu massimu ta' 3 numri sħaħ u 2 deċimali
validation.productRequestDTO.currentStock.decimalMin=L-istokk ma jistax jkun negattiv
validation.productRequestDTO.currentStock.digits=L-istokk jista' jkollu massimu ta' 10 numri sħaħ u 3 deċimali
validation.productRequestDTO.currentStock.notNull=L-istokk attwali huwa obbligatorju
validation.productRequestDTO.minimumStock.decimalMin=L-istokk minimu ma jistax jkun negattiv
validation.productRequestDTO.minimumStock.digits=L-istokk minimu jista' jkollu massimu ta' 10 numri sħaħ u 3 deċimali
validation.productRequestDTO.minimumStock.notNull=L-istokk minimu huwa obbligatorju
validation.productRequestDTO.name.notBlank=L-isem tal-prodott huwa obbligatorju
validation.productRequestDTO.name.size=Irid ikun bejn 2 u 100 karattru
validation.productRequestDTO.productCode.notBlank=Il-kodiċi tal-prodott huwa obbligatorju
validation.productRequestDTO.productCode.size=Il-kodiċi ma jistax jaqbeż il-50 karattru
validation.productRequestDTO.unit.notBlank=L-unità tal-kejl hija obbligatorja
validation.productRequestDTO.unit.size=L-unità ma tistax taqbeż l-20 karattru
validation.productRequestDTO.unitPrice.decimalMin=Il-prezz irid jkun ikbar minn żero
validation.productRequestDTO.unitPrice.digits=Il-prezz jista' jkollu massimu ta' 10 numri sħaħ u 2 deċimali
validation.productRequestDTO.unitPrice.notNull=Il-prezz tal-unità huwa obbligatorju
validation.recipe.elaboration.size=Il-preparazzjoni ma tistax taqbeż is-2000 karattru
validation.recipe.name.notBlank=L-isem tar-riċetta huwa obbligatorju
validation.recipe.name.size=Irid ikun bejn 2 u 150 karattru
validation.recipe.presentation.size=Il-preżentazzjoni ma tistax taqbeż l-1000 karattru
validation.recipe.totalCost.decimalMin=L-ispiża ma tistax tkun negattiva
validation.recipeAudit.action.notBlank=L-azzjoni hija obbligatorja
validation.recipeAudit.details.size=Id-dettalji ma jistgħux jaqbżu l-1000 karattru
validation.recipeComponent.parentRecipe.notNull=Ir-riċetta hija obbligatorja
validation.recipeComponent.product.notNull=Il-prodott huwa obbligatorju
validation.recipeComponent.quantity.decimalMin=Il-kwantità trid tkun ikbar minn 0
validation.recipeComponent.quantity.notNull=Il-kwantità hija obbligatorja
validation.recipeComponentRequestDTO.productId.notNull=L-ID tal-prodott huwa obbligatorju
validation.recipeComponentRequestDTO.quantity.decimalMin=Il-kwantità trid tkun ikbar minn żero
validation.recipeComponentRequestDTO.quantity.digits=Il-kwantità jista' jkollha massimu ta' 10 numri sħaħ u 3 deċimali
validation.recipeComponentRequestDTO.quantity.notNull=Il-kwantità hija obbligatorja
validation.recipeCookingAudit.details.size=Id-dettalji ma jistgħux jaqbżu l-1000 karattru
validation.recipeCookingAudit.quantityCooked.decimalMin=Il-kwantità trid tkun ikbar minn 0
validation.recipeCookingAudit.quantityCooked.notNull=Il-kwantità msajra hija obbligatorja
validation.recipeCookingAudit.recipe.notNull=Ir-riċetta hija obbligatorja
validation.recipeCookingRequestDTO.details.size=Id-dettalji ma jistgħux jaqbżu l-500 karattru
validation.recipeCookingRequestDTO.quantity.decimalMin=Il-kwantità trid tkun ikbar minn 0
validation.recipeCookingRequestDTO.quantity.digits=Il-kwantità jista' jkollha massimu ta' 10 numri sħaħ u 3 deċimali
validation.recipeCookingRequestDTO.quantity.notNull=Il-kwantità għat-tisjir hija obbligatorja
validation.recipeCookingRequestDTO.recipeId.notNull=L-ID tar-riċetta huwa obbligatorju
validation.recipeCookingRequestDTO.recipeId.positive=L-ID tar-riċetta jrid ikun pożittiv
validation.recipeRequestDTO.components.notEmpty=Ir-riċetta jrid ikollha mill-inqas komponent wieħed
validation.recipeRequestDTO.elaboration.notBlank=Il-preparazzjoni hija obbligatorja
validation.recipeRequestDTO.elaboration.size=Il-preparazzjoni ma tistax taqbeż is-2000 karattru
validation.recipeRequestDTO.name.notBlank=L-isem tar-riċetta huwa obbligatorju
validation.recipeRequestDTO.name.size=Irid ikun bejn 2 u 150 karattru
validation.recipeRequestDTO.presentation.notBlank=Il-preżentazzjoni hija obbligatorja
validation.recipeRequestDTO.presentation.size=Il-preżentazzjoni ma tistax taqbeż l-1000 karattru
validation.roleEscalationRequestDTO.durationMinutes.max=It-tul massimu permess huwa l-1440 minuta (24 siegħa)
validation.roleEscalationRequestDTO.durationMinutes.min=It-tul minimu jrid ikun minuta 1
validation.roleEscalationRequestDTO.durationMinutes.notNull=It-tul f'minuti huwa obbligatorju
validation.stockLedger.currentHash.notBlank=Il-hash attwali huwa obbligatorju
validation.stockLedger.movementType.notNull=It-tip ta' moviment huwa obbligatorju
validation.stockLedger.previousHash.notBlank=Il-hash preċedenti huwa obbligatorju
validation.stockLedger.product.notNull=Il-prodott huwa obbligatorju
validation.stockLedger.quantityDelta.notNull=Il-kwantità hija obbligatorja
validation.stockLedger.resultingStock.notNull=L-istokk li jirriżulta huwa obbligatorju
validation.stockLedger.sequenceNumber.notNull=In-numru tas-sekwenza huwa obbligatorju
validation.stockLedger.transactionTimestamp.notNull=It-timbru tal-ħin huwa obbligatorju
validation.stockMovementItemDTO.description.size=Id-deskrizzjoni ma tistax taqbeż il-500 karattru
validation.stockMovementItemDTO.movementType.notNull=It-tip ta' moviment huwa obbligatorju
validation.stockMovementItemDTO.productId.notNull=L-ID tal-prodott huwa obbligatorju
validation.stockMovementItemDTO.quantityDelta.digits=Il-kwantità jista' jkollha massimu ta' 10 numri sħaħ u 3 deċimali
validation.stockMovementItemDTO.quantityDelta.notNull=Il-kwantità hija obbligatorja
validation.stockSnapshot.currentStock.notNull=L-istokk attwali huwa obbligatorju
validation.stockSnapshot.integrityStatus.notBlank=L-istatus tal-integrità huwa obbligatorju
validation.stockSnapshot.lastSequenceNumber.notNull=In-numru tas-sekwenza huwa obbligatorju
validation.stockSnapshot.lastTransactionHash.notBlank=L-aħħar hash huwa obbligatorju
validation.stockSnapshot.lastUpdated.notNull=Id-data tal-aġġornament hija obbligatorja
validation.supplier.name.notBlank=L-isem tal-fornitur huwa obbligatorju
validation.supplier.name.size=Irid ikun bejn 2 u 100 karattru
validation.supplierRequestDTO.name.notBlank=L-isem tal-fornitur huwa obbligatorju
validation.supplierRequestDTO.name.size=Irid ikun bejn 2 u 100 karattru
validation.user.name.notBlank=L-isem huwa obbligatorju
validation.user.name.size=Irid ikun bejn 2 u 100 karattru
validation.user.password.notBlank=Il-password hija obbligatorja
validation.user.role.notNull=Ir-rwol huwa obbligatorju
validation.user.user.notBlank=L-isem tal-utent huwa obbligatorju
validation.userRequestDTO.name.notBlank=L-isem huwa obbligatorju
validation.userRequestDTO.name.size=Irid ikun bejn 2 u 100 karattru
validation.userRequestDTO.password.notBlank=Il-password hija obbligatorja
validation.userRequestDTO.password.size=Il-password jrid ikollha mill-inqas 6 karattri
validation.userRequestDTO.user.notBlank=L-isem tal-utent huwa obbligatorju
validation.userRequestDTO.user.size=L-isem tal-utent ma jistax jaqbeż il-100 karattru
""",

"ga": """validation.allergen.name.notBlank=Tá ainm an ailléirgin éigeantach
validation.allergen.name.size=Caithfidh sé a bheith idir 2 agus 50 carachtar
validation.allergenRequestDTO.name.notBlank=Tá ainm an ailléirgin éigeantach
validation.allergenRequestDTO.name.size=Caithfidh sé a bheith idir 2 agus 50 carachtar
validation.batchStockMovementRequestDTO.movements.notEmpty=Caithfear gluaiseacht amháin ar a laghad a chur san áireamh
validation.batchStockMovementRequestDTO.reason.size=Ní fhéadfaidh an chúis dul thar 1000 carachtar
validation.changePasswordRequestDTO.newPassword.notBlank=Tá an pasfhocal nua éigeantach
validation.changePasswordRequestDTO.newPassword.size=Caithfidh ar a laghad 6 charachtar a bheith sa phasfhocal nua
validation.inventoryAudit.actionDescription.size=Ní fhéadfaidh an tuairisc dul thar 500 carachtar
validation.inventoryAudit.product.notNull=Tá an táirge éigeantach
validation.inventoryAudit.quantity.notNull=Tá an chainníocht éigeantach
validation.inventoryAudit.unknown.notBlank=Tá an cineál gluaiseachta éigeantach
validation.inventoryMovementRequestDTO.movementType.notNull=Tá an cineál gluaiseachta éigeantach
validation.inventoryMovementRequestDTO.productId.notNull=Tá ID an táirge éigeantach
validation.inventoryMovementRequestDTO.quantity.decimalMax=Ní fhéadfaidh an chainníocht dul thar 9,999,999.99
validation.inventoryMovementRequestDTO.quantity.notNull=Tá an chainníocht éigeantach
validation.inventoryMovementRequestDTO.quantity.positive=Caithfidh an chainníocht a bheith níos mó ná nialas
validation.inventoryMovementRequestDTO.userId.notNull=Tá ID an úsáideora éigeantach
validation.jwtProperties.expiration.positive=Caithfidh luach dearfach a bheith i ndul in éag an JWT
validation.jwtProperties.secret.notBlank=Tá rún an JWT éigeantach
validation.loginRequestDTO.name.notBlank=Tá an t-ainm úsáideora éigeantach
validation.loginRequestDTO.password.notBlank=Tá an pasfhocal éigeantach
validation.order.orderDate.notNull=Tá dáta an ordaithe éigeantach
validation.order.orderDate.pastOrPresent=Ní fhéadfaidh dáta an ordaithe a bheith sa todhchaí
validation.order.status.notBlank=Tá an stádas éigeantach
validation.order.users.notNull=Tá an t-úsáideoir éigeantach
validation.orderAudit.action.notBlank=Tá an gníomh éigeantach
validation.orderAudit.details.size=Ní fhéadfaidh na sonraí dul thar 1000 carachtar
validation.orderDetail.order.notNull=Tá an t-ordú éigeantach
validation.orderDetail.product.notNull=Tá an táirge éigeantach
validation.orderDetail.quantity.decimalMin=Caithfidh an chainníocht a bheith níos mó ná 0
validation.orderDetail.quantity.notNull=Tá an chainníocht iarrtha éigeantach
validation.orderDetail.quantityReceived.decimalMin=Ní fhéadfaidh an chainníocht faighte a bheith diúltach
validation.orderDetailRequestDTO.productId.notNull=Tá ID an táirge éigeantach
validation.orderDetailRequestDTO.quantity.decimalMin=Caithfidh an chainníocht a bheith níos mó ná nialas
validation.orderDetailRequestDTO.quantity.digits=Is féidir uasmhéid de 10 slánuimhir agus 3 ionad dheachúil a bheith sa chainníocht
validation.orderDetailRequestDTO.quantity.notNull=Tá an chainníocht éigeantach
validation.orderReceptionDetailRequestDTO.productId.notNull=Tá ID an táirge éigeantach
validation.orderReceptionDetailRequestDTO.quantityReceived.notNull=Tá an chainníocht faighte éigeantach
validation.orderReceptionDetailRequestDTO.quantityReceived.positiveOrZero=Caithfidh an chainníocht faighte a bheith nialas nó níos mó
validation.orderReceptionRequestDTO.items.notEmpty=Caithfear táirge amháin faighte ar a laghad a shonrú
validation.orderReceptionRequestDTO.orderId.notNull=Tá ID an ordaithe éigeantach
validation.orderReceptionRequestDTO.status.notNull=Tá an stádas éigeantach
validation.orderRequestDTO.details.notEmpty=Caithfidh mionsonra amháin ar a laghad a bheith san ordú
validation.orderRequestDTO.userId.notNull=Tá ID an úsáideora éigeantach
validation.product.availabilityPercentage.decimalMax=Ní fhéadfaidh an céatadán infhaighteachta dul thar 100
validation.product.availabilityPercentage.decimalMin=Ní fhéadfaidh an céatadán infhaighteachta a bheith diúltach
validation.product.availabilityPercentage.digits=Formáid neamhbhailí infhaighteachta
validation.product.currentStock.decimalMin=Ní fhéadfaidh an stoc a bheith diúltach
validation.product.currentStock.digits=Formáid neamhbhailí stoic
validation.product.currentStock.notNull=Tá an stoc reatha éigeantach
validation.product.minimumStock.decimalMin=Ní fhéadfaidh an t-íosmhéid stoic a bheith diúltach
validation.product.minimumStock.digits=Formáid neamhbhailí don íosmhéid stoic
validation.product.name.notBlank=Tá ainm an táirge éigeantach
validation.product.name.size=Caithfidh sé a bheith idir 2 agus 100 carachtar
validation.product.productCode.notBlank=Tá cód an táirge éigeantach
validation.product.unit.notBlank=Tá an t-aonad tomhais éigeantach
validation.product.unitPrice.decimalMin=Caithfidh an praghas a bheith níos mó ná 0
validation.product.unitPrice.digits=Formáid neamhbhailí praghais
validation.product.unitPrice.notNull=Tá praghas an aonaid éigeantach
validation.productRequestDTO.availabilityPercentage.decimalMax=Ní fhéadfaidh an céatadán infhaighteachta dul thar 100
validation.productRequestDTO.availabilityPercentage.decimalMin=Ní fhéadfaidh an céatadán infhaighteachta a bheith diúltach
validation.productRequestDTO.availabilityPercentage.digits=Is féidir uasmhéid de 3 slánuimhir agus 2 ionad dheachúil a bheith sa chéatadán
validation.productRequestDTO.currentStock.decimalMin=Ní fhéadfaidh an stoc a bheith diúltach
validation.productRequestDTO.currentStock.digits=Is féidir uasmhéid de 10 slánuimhir agus 3 ionad dheachúil a bheith sa stoc
validation.productRequestDTO.currentStock.notNull=Tá an stoc reatha éigeantach
validation.productRequestDTO.minimumStock.decimalMin=Ní fhéadfaidh an t-íosmhéid stoic a bheith diúltach
validation.productRequestDTO.minimumStock.digits=Is féidir uasmhéid de 10 slánuimhir agus 3 ionad dheachúil a bheith san íosmhéid stoic
validation.productRequestDTO.minimumStock.notNull=Tá an t-íosmhéid stoic éigeantach
validation.productRequestDTO.name.notBlank=Tá ainm an táirge éigeantach
validation.productRequestDTO.name.size=Caithfidh sé a bheith idir 2 agus 100 carachtar
validation.productRequestDTO.productCode.notBlank=Tá cód an táirge éigeantach
validation.productRequestDTO.productCode.size=Ní fhéadfaidh an cód dul thar 50 carachtar
validation.productRequestDTO.unit.notBlank=Tá an t-aonad tomhais éigeantach
validation.productRequestDTO.unit.size=Ní fhéadfaidh an t-aonad dul thar 20 carachtar
validation.productRequestDTO.unitPrice.decimalMin=Caithfidh an praghas a bheith níos mó ná nialas
validation.productRequestDTO.unitPrice.digits=Is féidir uasmhéid de 10 slánuimhir agus 2 ionad dheachúil a bheith sa phraghas
validation.productRequestDTO.unitPrice.notNull=Tá praghas an aonaid éigeantach
validation.recipe.elaboration.size=Ní fhéadfaidh an t-ullmhúchán dul thar 2000 carachtar
validation.recipe.name.notBlank=Tá ainm an oidis éigeantach
validation.recipe.name.size=Caithfidh sé a bheith idir 2 agus 150 carachtar
validation.recipe.presentation.size=Ní fhéadfaidh an cur i láthair dul thar 1000 carachtar
validation.recipe.totalCost.decimalMin=Ní fhéadfaidh an costas a bheith diúltach
validation.recipeAudit.action.notBlank=Tá an gníomh éigeantach
validation.recipeAudit.details.size=Ní fhéadfaidh na sonraí dul thar 1000 carachtar
validation.recipeComponent.parentRecipe.notNull=Tá an t-oideas éigeantach
validation.recipeComponent.product.notNull=Tá an táirge éigeantach
validation.recipeComponent.quantity.decimalMin=Caithfidh an chainníocht a bheith níos mó ná 0
validation.recipeComponent.quantity.notNull=Tá an chainníocht éigeantach
validation.recipeComponentRequestDTO.productId.notNull=Tá ID an táirge éigeantach
validation.recipeComponentRequestDTO.quantity.decimalMin=Caithfidh an chainníocht a bheith níos mó ná nialas
validation.recipeComponentRequestDTO.quantity.digits=Is féidir uasmhéid de 10 slánuimhir agus 3 ionad dheachúil a bheith sa chainníocht
validation.recipeComponentRequestDTO.quantity.notNull=Tá an chainníocht éigeantach
validation.recipeCookingAudit.details.size=Ní fhéadfaidh na sonraí dul thar 1000 carachtar
validation.recipeCookingAudit.quantityCooked.decimalMin=Caithfidh an chainníocht a bheith níos mó ná 0
validation.recipeCookingAudit.quantityCooked.notNull=Tá an chainníocht atá cócaráilte éigeantach
validation.recipeCookingAudit.recipe.notNull=Tá an t-oideas éigeantach
validation.recipeCookingRequestDTO.details.size=Ní fhéadfaidh na sonraí dul thar 500 carachtar
validation.recipeCookingRequestDTO.quantity.decimalMin=Caithfidh an chainníocht a bheith níos mó ná 0
validation.recipeCookingRequestDTO.quantity.digits=Is féidir uasmhéid de 10 slánuimhir agus 3 ionad dheachúil a bheith sa chainníocht
validation.recipeCookingRequestDTO.quantity.notNull=Tá an chainníocht le cócaráil éigeantach
validation.recipeCookingRequestDTO.recipeId.notNull=Tá ID an oidis éigeantach
validation.recipeCookingRequestDTO.recipeId.positive=Caithfidh ID an oidis a bheith dearfach
validation.recipeRequestDTO.components.notEmpty=Caithfidh comhábhar amháin ar a laghad a bheith san oideas
validation.recipeRequestDTO.elaboration.notBlank=Tá an t-ullmhúchán éigeantach
validation.recipeRequestDTO.elaboration.size=Ní fhéadfaidh an t-ullmhúchán dul thar 2000 carachtar
validation.recipeRequestDTO.name.notBlank=Tá ainm an oidis éigeantach
validation.recipeRequestDTO.name.size=Caithfidh sé a bheith idir 2 agus 150 carachtar
validation.recipeRequestDTO.presentation.notBlank=Tá an cur i láthair éigeantach
validation.recipeRequestDTO.presentation.size=Ní fhéadfaidh an cur i láthair dul thar 1000 carachtar
validation.roleEscalationRequestDTO.durationMinutes.max=Is é 1440 nóiméad (24 uair an chloig) an t-achar is faide a cheadaítear
validation.roleEscalationRequestDTO.durationMinutes.min=Caithfidh an t-achar a bheith 1 nóiméad ar a laghad
validation.roleEscalationRequestDTO.durationMinutes.notNull=Tá an t-achar i nóiméid éigeantach
validation.stockLedger.currentHash.notBlank=Tá an hais reatha éigeantach
validation.stockLedger.movementType.notNull=Tá an cineál gluaiseachta éigeantach
validation.stockLedger.previousHash.notBlank=Tá an hais roimhe seo éigeantach
validation.stockLedger.product.notNull=Tá an táirge éigeantach
validation.stockLedger.quantityDelta.notNull=Tá an chainníocht éigeantach
validation.stockLedger.resultingStock.notNull=Tá an stoc a leanann as éigeantach
validation.stockLedger.sequenceNumber.notNull=Tá an tsraithuimhir éigeantach
validation.stockLedger.transactionTimestamp.notNull=Tá an stampa ama éigeantach
validation.stockMovementItemDTO.description.size=Ní fhéadfaidh an tuairisc dul thar 500 carachtar
validation.stockMovementItemDTO.movementType.notNull=Tá an cineál gluaiseachta éigeantach
validation.stockMovementItemDTO.productId.notNull=Tá ID an táirge éigeantach
validation.stockMovementItemDTO.quantityDelta.digits=Is féidir uasmhéid de 10 slánuimhir agus 3 ionad dheachúil a bheith sa chainníocht
validation.stockMovementItemDTO.quantityDelta.notNull=Tá an chainníocht éigeantach
validation.stockSnapshot.currentStock.notNull=Tá an stoc reatha éigeantach
validation.stockSnapshot.integrityStatus.notBlank=Tá stádas na sláine éigeantach
validation.stockSnapshot.lastSequenceNumber.notNull=Tá an tsraithuimhir éigeantach
validation.stockSnapshot.lastTransactionHash.notBlank=Tá an hais dheireanach éigeantach
validation.stockSnapshot.lastUpdated.notNull=Tá dáta an nuashonraithe éigeantach
validation.supplier.name.notBlank=Tá ainm an tsoláthraí éigeantach
validation.supplier.name.size=Caithfidh sé a bheith idir 2 agus 100 carachtar
validation.supplierRequestDTO.name.notBlank=Tá ainm an tsoláthraí éigeantach
validation.supplierRequestDTO.name.size=Caithfidh sé a bheith idir 2 agus 100 carachtar
validation.user.name.notBlank=Tá an t-ainm éigeantach
validation.user.name.size=Caithfidh sé a bheith idir 2 agus 100 carachtar
validation.user.password.notBlank=Tá an pasfhocal éigeantach
validation.user.role.notNull=Tá an ról éigeantach
validation.user.user.notBlank=Tá an t-ainm úsáideora éigeantach
validation.userRequestDTO.name.notBlank=Tá an t-ainm éigeantach
validation.userRequestDTO.name.size=Caithfidh sé a bheith idir 2 agus 100 carachtar
validation.userRequestDTO.password.notBlank=Tá an pasfhocal éigeantach
validation.userRequestDTO.password.size=Caithfidh ar a laghad 6 charachtar a bheith sa phasfhocal
validation.userRequestDTO.user.notBlank=Tá an t-ainm úsáideora éigeantach
validation.userRequestDTO.user.size=Ní fhéadfaidh an t-ainm úsáideora dul thar 100 carachtar
"""
}

for lang, content in FILES.items():
    path = os.path.join(VDIR, f"ValidationMessages_{lang}.properties")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content.strip() + "\n")
    lines = [l for l in content.strip().split("\n") if "=" in l]
    print(f"  {lang}: wrote {len(lines)} keys")
